### ISSUE TITLE
String index out of range error

### ISSUE THREAD

**Issue by ERasnier** [instaloader/instaloader#1009]
My arg.txt file generally is this:
```
--login=USERNAME
--password=PASSWORD
--no-posts
--no-metadata-json
--no-captions
--no-videos
--no-video-thumbnails
--filename-pattern={target}
```

I'm pretty much trying to just download profile photos of the accounts. At first I was downloading primarily ID files but after a bit of changes which is the above code, all I'm getting is this.
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 449, in <module>
    main()
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 442, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 196, in _main
    }.get(target[0], 'username')
IndexError: string index out of range
```
 Even if I cut down the amount of commands to just login and just have the target it'll still pop up.

**Comment by aandergr** [comment]
Welcome to the community! Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.
