### ISSUE TITLE
Highlights may have bad characters that cause the program to break

### ISSUE THREAD

**Issue by AplhaSlayer1964** [instaloader/instaloader#1032]
**Describe the bug**
Some highlights titles gives this error:
UnicodeEncodeError: 'charmap' codec can't encode characters
This error breaks instaloader entirely so nothing else will be downloaded after this error occurs. 

**To Reproduce**
--dirname-pattern=Z:/Instagram/Instaloader/{target} --highlights
One of this accounts highlights causes the error when trying to name the highlights folder
https://www.instagram.com/irina.away/

**Expected behavior**
Remove bad characters in the highlight title?

**Error messages and tracebacks**
Traceback (most recent call last):
  File "Z:\Programs\instaloader\instaloader-upcoming-v4.7\instaloader.py", line 6, in <module>
    main()
  File "Z:\COOM\Programs\instaloader\instaloader-upcoming-v4.7\instaloader\__main__.py", line 445, in main
    _main(loader,
  File "Z:\Programs\instaloader\instaloader-upcoming-v4.7\instaloader\__main__.py", line 211, in _main
    instaloader.download_profiles(profiles,
  File "Z:\Programs\instaloader\instaloader-upcoming-v4.7\instaloader\instaloader.py", line 1253, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "Z:\Programs\instaloader\instaloader-upcoming-v4.7\instaloader\instaloader.py", line 64, in call
    return func(instaloader, *args, **kwargs)
  File "Z:\Programs\instaloader\instaloader-upcoming-v4.7\instaloader\instaloader.py", line 807, in download_highlights
    self.context.log("Retrieving highlights \"{}\" from profile {}".format(user_highlight.title, name))
  File "Z:\Programs\instaloader\instaloader-upcoming-v4.7\instaloader\instaloadercontext.py", line 105, in log
    print(*msg, sep=sep, end=end, flush=flush)
  File "C:\Users\User 1\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>

**Instaloader version**
upcoming/V4.7

**Additional context**
I think it just has to do with something in the title of the highlights.

**Comment by Showmaster3000** [comment]
The naming of highlight folders is currently problematic. We already have some other issues dealing with that problem, #859, #710, #185

**Comment by AplhaSlayer1964** [comment]
Thanks for letting me know! Sorry for the duplicate post.
