### ISSUE TITLE
Command Line - {owner_id} cannot be used as --dirname-pattern

### ISSUE THREAD

**Issue by SkyBread** [instaloader/instaloader#1037]
**Describe the bug**

**To Reproduce**
1. Update instaloader using `pip install --upgrade instaloader`
2. Type `instaloader --no-metadata-json --no-compress-json --dirname-pattern={owner_id} --no-captions --login=USER TARGET_USER`
3. Run

**Expected behavior**
The Program Start download posts of the TARGET_USER, dirname shall be his/her user id(int)

**Error messages and tracebacks**
Copied from the Output:
```
Loaded session from /root/.config/instaloader/session-USER.
Logged in as USER.
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/instaloader/__main__.py", line 431, in main
    _main(loader,
  File "/usr/local/lib/python3.9/site-packages/instaloader/__main__.py", line 167, in _main
    profile = instaloader.check_profile_id(target)
  File "/usr/local/lib/python3.9/site-packages/instaloader/instaloader.py", line 1095, in check_profile_id
    id_filename = self._get_id_filename(profile_name)
  File "/usr/local/lib/python3.9/site-packages/instaloader/instaloader.py", line 1066, in _get_id_filename
    return os.path.join(self.dirname_pattern.format(),
KeyError: 'owner_id'
```

**Instaloader version**
4.6.2

**Additional context**
Besides, there is a bug found when the instagram username have "dot" (for example: skybrea.d), the program will rename the other's folder dirname (that's why I wants change the dirname pattern to {owner_id} )

**Comment by Thammus** [comment]
See #168, #955.
