### ISSUE TITLE
Compatibility Issue Windows

### ISSUE THREAD

**Issue by Rcola1987** [instaloader/instaloader#107]
It seems that the application cannot be ran on a system that is in a Microsoft Windows Domain. Every time I try to run the program either from an elevated CLI or from non elevated I get a Python call back error looking for a non existent user home folder. I would assume it is the home folder on one of the developers computers with the way the error is formed.

I think the error has something to do with where the session file is being stored. Is there a way to change the default location of that file to say the execution directory of the application? If anything this will make it easier for me to manage than having it in the appdata folder.

The ERROR:
V:\IL>instaloader --login XXXXX XXXXXX
Session file does not exist yet - Logging in.
Enter Instagram password for XXXXXX:
Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000000035E3F98>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection o
bject at 0x00000000035E3F98>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader.py", line 1832, in <module>
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader.py", line 1828, in _main
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader.py", line 1804, in main
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader.py", line 1571, in main
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader.py", line 1541, in interactive_login
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader.py", line 1001, in login
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 521, in get
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnectio
n object at 0x00000000035E3F98>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
[2016] Failed to execute script instaloader

**Comment by Thammus** [comment]
Hello,
thanks for supporting Instaloader. I think this error neither has to do with "looking for a non existent user home folder" nor "with where the session file is being stored". By the way, you can easily set the location of the session file using the [`--sessionfile`](https://instaloader.github.io/cli-options.html#login-download-private-profiles) flag. 
Do not be confused by the strange looking home folder. Since the provided Windows executable is meant to be standalone, it ships all the python stuff that is needed. In case of an error, the runtime environment simply wants to show in which file and at which line the error occurred. Therefore, it prints the path to the source files that were used during compilation. Since the precompilation took place on another machine, these paths are shown to reference the files.
Having said that, the error message you provided shows a `requests.exceptions.ConnectionError` and I think this is a problem concerning requests and some network configurations in connection with the Windows domain. 
Could you please install [Python3](https://www.python.org/downloads/windows/) and [Requests](http://docs.python-requests.org/en/master/user/install/#install) on the machine in question and execute the following simple python code:
```python
import requests
requests.get('https://www.instagram.com/')
```
If this results in a similar error, then it is not a problem that resides inside Instaloader.

**Comment by Rcola1987** [comment]
Thanks for the quick update! I dont program in the languages that you guys are using so i'm a little unfamiliar with some of the error messages.

After digging into it with your suggestions it seems some of the ad blocking that we have setup in our global host files was causing it to fail. The only thing I can suggest is maybe modify error checking in the binary to produce easier to read or more meaningful (to the end user) error messages?

What this does mean is that we cannot run it on a system that has our ad blocking enabled so I will have to spin up a VM to run it on that is not getting used for web surfing due to the amount of infected ads out there.

But again thanks for the quick and helpful response!
