### ISSUE TITLE
Python Module: AttributeError: 'Story' object has no attribute 'date_local'

### ISSUE THREAD

**Issue by Tydoki** [instaloader/instaloader#1089]
**Describe the bug**
Python is telling me that the Instagram 'Story' object has no attribute 'date_local'

**To Reproduce**
just call L.download_storyitem(story, filename)

**Error messages and tracebacks**
~~~
_ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_command_error coro=<bound method Bot.on_command_error of <lib.bot.Bot object at 0x0000027628ECA0D0>> exception=AttributeError("'Story' object has no attribute 'date_local'")>
Traceback (most recent call last):
  File "C:\Users\K\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 348, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Users\K\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\K\Documents\GitHub\KittenBot\lib\bot\__init__.py", line 135, in on_command_error
    raise exc.original
  File "C:\Users\K\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\K\Documents\GitHub\KittenBot\lib\cogs\fun.py", line 92, in test
    L.download_storyitem(story, filename)
  File "C:\Users\K\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 767, in download_storyitem
    date_local = item.date_local
AttributeError: 'Story' object has no attribute 'date_local'
~~~

**Instaloader version**
4.7.1

**Comment by Abioux** [comment]
how did you fixed this?
