### ISSUE TITLE
Instaloader doesn't work again [KeyError: 'graphql'] 

### ISSUE THREAD

**Issue by sofiavlachou28** [instaloader/instaloader#1093]
Using Ιstaloader for 2 months and no problem appeared.
 I tried to download a Hastag and I get this error many times today and yesterday:

```
Traceback (most recent call last):
  File "C:/Users/USER/pythonProject/Instaloader.py", line 18, in <module>
    bot.download_hashtag(hashtag="moodoftheday",max_count=30)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 1023, in download_hashtag
    hashtag = Hashtag.from_name(self.context, hashtag)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 1302, in from_name
    hashtag._obtain_metadata()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 1316, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 1312, in _query
    params)["graphql"]["hashtag"]
KeyError: 'graphql'

```

I tried different versions, and the latest 4.7.1. But the problem remains!!
When I running the code, the downloads start, but after a few seconds appears the error above.  

Here is my code: 
```
import instaloader
instance = instaloader.Instaloader()
instance.load_session_from_file("myfile")
instance.download_hashtag(hashtag="moodoftheday",max_count=30)
```

Can someone help me? 

Thank you in advance

**Comment by Showmaster3000** [comment]
see also #1084.
Please do not open multiple issues with the same problem!
