### ISSUE TITLE
v4.7.1: KeyError: 'graphql' on instaloader.Hashtag.from_name

### ISSUE THREAD

**Issue by nyanofthemoon** [instaloader/instaloader#1096]
Problem occurs with both version 4.6.2 and latest 4.7.1

Previously working code now throws error with `instaloader.Hashtag.from_name(L.context, "cats")`

```
Traceback (most recent call last):
  File "run.py", line 118, in <module>
    ihashtag = instaloader.Hashtag.from_name(L.context, hashtag)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 1323, in from_name
    hashtag._obtain_metadata()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 1337, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 1333, in _query
    params)["graphql"]["hashtag"]
KeyError: 'graphql'
```

**Comment by jcharvet** [comment]
I am having the same issue

**Comment by nyanofthemoon** [comment]
Sorry - this was already reported in:
- https://github.com/instaloader/instaloader/issues/1084
- https://github.com/instaloader/instaloader/issues/1093
