### ISSUE TITLE
graphql key error

### ISSUE THREAD

**Issue by TaffPlaysYT** [instaloader/instaloader#1103]
**Describe the bug**
I get an error with some instagram accounts where it gives me a key error for graphql

**To Reproduce**
instaloader --login username hashtag
**Expected behavior**
It will download what hashtag you want as that username

**Error messages and tracebacks**
Traceback (most recent call last):
  File "E:\Misc\INSTAGRAM\Python39\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.7.1', 'console_scripts', 'instaloader')())
  File "c:\users\bunji\appdata\local\programs\python\python39\lib\site-packages\instaloader\__main__.py", line 445, in main
    _main(loader,
  File "c:\users\bunji\appdata\local\programs\python\python39\lib\site-packages\instaloader\__main__.py", line 157, in _main
    instaloader.download_hashtag(hashtag=target[1:], max_count=max_count, fast_update=fast_update,
  File "c:\users\bunji\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloader.py", line 1095, in download_hashtag
    hashtag = Hashtag.from_name(self.context, hashtag)
  File "c:\users\bunji\appdata\local\programs\python\python39\lib\site-packages\instaloader\structures.py", line 1323, in from_name
    hashtag._obtain_metadata()
  File "c:\users\bunji\appdata\local\programs\python\python39\lib\site-packages\instaloader\structures.py", line 1337, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "c:\users\bunji\appdata\local\programs\python\python39\lib\site-packages\instaloader\structures.py", line 1332, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'

**Instaloader version**
4.7.1

**Additional context**
It only happens on some accounts with hashtags

**Comment by Showmaster3000** [comment]
duplicate issue, see pinned #1080
