### ISSUE TITLE
Post.location: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tom-s-ukgwa** [instaloader/instaloader#1109]
I'd been running Instaloader for a few weeks and it was working really well for me. Great tool!

Then, a few days ago, when I ran the following:

`instaloader profile envagency --geotags --stories --highlights --igtv --login` (with login details)

I got the following error messages:

```
File "/home/work/anaconda3/bin/instaloader", line 8, in <module>
  sys.exit(main())
File "/home/work/anaconda3/lib/python3.8/site-packages/instaloader/__main__.py", line 445, in main
  _main(loader,
File "/home/work/anaconda3/lib/python3.8/site-packages/instaloader/__main__.py", line 211, in _main
  instaloader.download_profiles(profiles,
File "/home/work/anaconda3/lib/python3.8/site-packages/instaloader/instaloader.py", line 1289, in download_profiles
  self.posts_download_loop(profile.get_posts(), profile_name, fast_update, post_filter,
File "/home/work/anaconda3/lib/python3.8/site-packages/instaloader/instaloader.py", line 922, in posts_download_loop
  downloaded = self.download_post(post, target=target)
File "/home/work/anaconda3/lib/python3.8/site-packages/instaloader/instaloader.py", line 670, in download_post
  if self.download_geotags and post.location:
File "/home/work/anaconda3/lib/python3.8/site-packages/instaloader/structures.py", line 554, in location
  loc = self._context.get_json("explore/locations/{0}/".format(location_id),
TypeError: 'NoneType' object is not subscriptable
```

Instaloader downloads stories fine, and the first post after them but displays the above error when attempting to download the second post.

I'm running the latest version (4.7.1)

Any idea how I might fix this? 

Thank you

**Comment by aandergr** [comment]
Thanks for reporting!

> `instaloader profile envagency --geotags --stories --highlights --igtv --login` (with login details)

Also reproducible by downloading the failing post directly: `instaloader --login=LOGIN --geotags -- -CNXwMo1C24i`

**Comment by faaip** [comment]
I have still have this problem using version 4.8.1 with the #1244 fix by @aandergr . Should it be working now?

```
Retrieving pictures for location 1425361787550852...
Traceback (most recent call last):
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/lib/python3.9/site-packages/instaloader/__main__.py", line 467, in main
    _main(loader,
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/lib/python3.9/site-packages/instaloader/__main__.py", line 170, in _main
    instaloader.download_location(location=target[1:], max_count=max_count, fast_update=fast_update,
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/lib/python3.9/site-packages/instaloader/instaloader.py", line 80, in call
    return func(instaloader, *args, **kwargs)
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/lib/python3.9/site-packages/instaloader/instaloader.py", line 1128, in download_location
    self.posts_download_loop(self.get_location_posts(location), "%" + location, fast_update, post_filter,
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/lib/python3.9/site-packages/instaloader/instaloader.py", line 978, in posts_download_loop
    for number, post in enumerate(posts, start=start_index + 1):
  File "/Users/frederik/.pyenv/versions/instaloader_cli_wrapper/lib/python3.9/site-packages/instaloader/instaloader.py", line 1098, in get_location_posts
    location_data = self.context.get_json('explore/locations/{0}/'.format(location),
TypeError: 'NoneType' object is not subscriptable
```

**Comment by aandergr** [comment]
@faaip As you can see in your entirely different stack trace, you are not having *this* problem, as opposed to what your comment says. Hence, I will mark it as offtopic.
