### ISSUE TITLE
KeyError: 'graphql' using -l on command line

### ISSUE THREAD

**Issue by hobzcalvin** [instaloader/instaloader#1110]
To reproduce:
`instaloader -l myaccountname "#ahashtag"`
Also happens with `-p` option.

Output:
```
Session file does not exist yet - Logging in.
Enter Instagram password for justgranttestaccount:
Logged in as justgranttestaccount.
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "/usr/local/lib/python3.9/site-packages/instaloader/__main__.py", line 157, in _main
    instaloader.download_hashtag(hashtag=target[1:], max_count=max_count, fast_update=fast_update,
  File "/usr/local/lib/python3.9/site-packages/instaloader/instaloader.py", line 1095, in download_hashtag
    hashtag = Hashtag.from_name(self.context, hashtag)
  File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 1323, in from_name
    hashtag._obtain_metadata()
  File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 1337, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 1332, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'
```

Instaloader version 4.7.1
MacOS 10.14.6 (18G6020)

**Comment by hobzcalvin** [comment]
Sorry, clearly a duplicate of others.

**Comment by aandergr** [comment]
Duplicate of #1080.
