### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" on some accounts.

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#1133]
**Describe the bug**
Instaloader downloads one post and then returns error.

**To Reproduce**
I'm running this:
```
-l=login
-p=password
--geotags
--igtv
--no-video-thumbnails
--no-compress-json
--filename-pattern={date_local:%y%m%d_%Hкћ‰%Mкћ‰%S} {profile} [{shortcode}]
profile
```

**Error messages and tracebacks**
```
... unchanged Traceback (most recent call last):
  File "/home/pi/.local/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 459, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 214, in _main
    fast_update, post_filter, storyitem_filter)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 1290, in download_profiles
    total_count=profile.mediacount, owner_profile=profile)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 922, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 670, in download_post
    if self.download_geotags and post.location:
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/structures.py", line 555, in location
    params={'__a': 1})['graphql']['location']
TypeError: 'NoneType' object is not subscriptable

```
**Instaloader version**
4.7.1

**Additional context**
It's working if I change the profile I use to download. The only 2 differences for the one that doesn't work: it pretty new (2-4 weeks old) and it doesn't have an instaloader session file (even though it downloads first post, every time I re-run it, it says there's no session file yet.

Apparently session file is not a problem either. Created one using `instaloader -l login` and still got this error.

**Comment by Showmaster3000** [comment]
This problem is already discussed in #1117 and #1109.
The problem refers to parameter `--geotags` where something changed on instagram. So not using it is a workaraound at the moment.
