### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by sillibird** [instaloader/instaloader#114]
When trying to download with the new version, 4.0, either right away or after a few second it will error out with:

```
[  1/100] %username%_/%year%-%month%-%day%_23-14-50_UTC.jpg exists [%desc%] updated [%desc%] Traceback (most recent call last):
  File "C:\Users\Koch-\Desktop\Instaloader\__main__.py", line 364, in <module>
  File "C:\Users\Koch-\Desktop\Instaloader\__main__.py", line 360, in __main
  File "C:\Users\Koch-\Desktop\Instaloader\__main__.py", line 335, in main
  File "C:\Users\Koch-\Desktop\Instaloader\__main__.py", line 150, in _main
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader\instaloader.py", line 718, in download_profile
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader\instaloader.py", line 369, in download_post
  File "C:\Users\Koch-\Desktop\Instaloader\instaloader\instaloader.py", line 192, in update_comments
TypeError: '<' not supported between instances of 'int' and 'str'
[14464] Failed to execute script __main__
```

"Koch-" Is not my user directory, nor does it exist, so I don't know where that is from.

(Where, %username% is their username, %year% is the year of post, %desc% is the post description, etc...)

**Comment by aandergr** [comment]
Thanks for reporting. This is now fixed in version 4.0.1.

> "Koch-" Is not my user directory, nor does it exist, so I don't know where that is from.

As @Thammus noted in another issue:
> Do not be confused by the strange looking home folder. Since the provided Windows executable is meant to be standalone, it ships all the python stuff that is needed. In case of an error, the runtime environment simply wants to show in which file and at which line the error occurred. Therefore, it prints the path to the source files that were used during compilation. Since the precompilation took place on another machine, these paths are shown to reference the files.
