### ISSUE TITLE
Unable to Retriev Stories/Highlights [KeyError: 'caption']

### ISSUE THREAD

**Issue by fosam** [instaloader/instaloader#1140]
**Describe the bug**
Getting an error when trying to download stories and/or highlights when using the below command.

**To Reproduce**
Copy the commad i used exactly and try to run it.

**Expected behavior**
Expected behavior is to succeed in running the command without errors while being able to download stories and/or highlights.

**Error messages and tracebacks**

<pre>
C:\Users\myUser>instaloader --filename-pattern={date_utc:%Y-%m-%d_%H-%M-%S}_{caption} --no-posts --no-captions --no-metadata-json --login myUser --sessionfile C:\Users\myUser\Desktop\session-myUser +C:\Users\myUser\Desktop\args.txt
Loaded session from C:\Users\myUser\Desktop\session-myUser.
Logged in as myUser.
Stored ID 25025320 for profile instagram.
instagram\2020-09-16_04-08-58_UTC_profile_pic.jpg
Retrieving highlights "Made Us 😊" from profile instagram
instagram\Made Us 😊\2021-05-14_18-13-44_UTC_cover.jpg
[  1/ 11] Traceback (most recent call last):
  File "__main__.py", line 478, in <module>
  File "__main__.py", line 475, in __main
  File "__main__.py", line 445, in main
  File "__main__.py", line 211, in _main
  File "instaloader\instaloader.py", line 1284, in download_profiles
  File "instaloader\instaloader.py", line 64, in call
  File "instaloader\instaloader.py", line 850, in download_highlights
  File "instaloader\instaloader.py", line 769, in download_storyitem
  File "instaloader\instaloader.py", line 575, in format_filename
  File "string.py", line 161, in format
  File "string.py", line 165, in vformat
  File "string.py", line 205, in _vformat
  File "string.py", line 270, in get_field
  File "instaloader\instaloader.py", line 124, in get_value
  File "instaloader\instaloader.py", line 109, in get_value
  File "string.py", line 227, in get_value
<b>KeyError: 'caption'
[5528] Failed to execute script __main__</b>
</pre>

**Instaloader version**
`Version 4.7.1`  
Windows 10 x64

**Additional context**
The issue only occurs when i try to download stories and/or highlights.
If i remove `--stories` and/or `--highlights` from the arguments then the command runs without any issues.

**+args.txt**
```
instagram
--highlights
```
Why is this happening?

**Comment by aandergr** [comment]
You get a `KeyError: 'caption'` error because you use the token `{caption}` in your filename pattern, which is not supported, since it is not defined for story items. Here is described how to use `--filename-pattern` and `--dirname-pattern`: https://instaloader.github.io/basic-usage.html#filename-specification

**Comment by fosam** [comment]
In other words, `{caption}` is not to be used when retreiving stories and highlights?
Because i tried `{caption}` for posts and it works.

**Comment by aandergr** [comment]
Exactly.

There is #253, suggesting to split the filename pattern into separate patterns for posts and storyitems.

**Comment by fosam** [comment]
@aandergr What is the length limit for `{caption}` in the filename? because some posts have long captions and they return an error, while for the shorter ones it is no problem.
