### ISSUE TITLE
JSON Decode Error caused by Python

### ISSUE THREAD

**Issue by justusjonas9** [instaloader/instaloader#1168]
**Describe the bug**
Can't download any profile or content of any profile

**To Reproduce**
instaloader therock --stories --login MyPROFILE

**Expected behavior**
Download profile content

**Error messages and tracebacks**
File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "/home/alex/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 104, in _main
    instaloader.login(username, password)
  File "/home/alex/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "/home/alex/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Instaloader version**
4.7.1

**Additional context**
python version:
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by Showmaster3000** [comment]
Looks like its a duplicate of #1150, is it?
Do you have a session file saved from a former run?

**Comment by justusjonas9** [comment]
Now it'ts working again.

**Comment by HackwithSharu** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/toutatis/core.py", line 84, in main
    infos = getInfo(args.username, sessionsId)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/toutatis/core.py", line 32, in getInfo
    userId = getUserId(username, sessionId)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/toutatis/core.py", line 25, in getUserId
    id = api.json()["logging_page_id"].strip("profilePage_")
         ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 help this error
