### ISSUE TITLE
Log in not working

### ISSUE THREAD

**Issue by socialrupt** [instaloader/instaloader#1191]
My code use to work but now it doesn't allow me to log into my Instagram account when I click run.

**To Reproduce**
To reproduce the behaviour just copy, paste and run this: 
https://del.dog/instaloader

**Expected behaviour**
It should not produce any errors.

**Error messages and tracebacks**

Traceback (most recent call last):
  File "C:\Users\44744\Documents\Project2\venv\lib\site-packages\instaloader\instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "C:\Users\44744\Documents\Project2\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\44744\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\44744\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\44744\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\44744\Documents\Project2\Group_1\Leeching_Bot\Testing file.py", line 9, in <module>
    L.login(USER, PASSWORD)        # (login)
  File "C:\Users\44744\Documents\Project2\venv\lib\site-packages\instaloader\instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "C:\Users\44744\Documents\Project2\venv\lib\site-packages\instaloader\instaloadercontext.py", line 226, in login
    raise ConnectionException(
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 403 - Forbidden.

**Instaloader version**
4.7.2

**Additional context**
I've tried this https://instaloader.github.io/troubleshooting.html#login-error but doesn't fix the problem. It does download the firefox files but still doesn't fix the solution.

I've also seen this but it didn't help me. https://github.com/instaloader/instaloader/issues/1150
Also, I am in the UK.

**Comment by ZeevoX** [comment]
Ah, at last someone who shares my troubles! I've also been having issues logging in, and I too am based in the UK.

**Comment by jojojojojoj5564656465465** [comment]
SAME

```
Traceback (most recent call last):
  File "/home/neon/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/neon/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "/home/neon/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 96, in _main
    instaloader.load_session_from_file(username, sessionfile)
  File "/home/neon/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 531, in load_session_from_file
    self.context.load_session_from_file(username, sessionfile)
  File "/home/neon/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 179, in load_session_from_file
    session.cookies = requests.utils.cookiejar_from_dict(pickle.load(sessionfile))
_pickle.UnpicklingError: invalid load key, '-'.
```

**Comment by topotamadre023** [comment]
My error is quite similar, also while login in

``Session file does not exist yet - Logging in.
Traceback (most recent call last):
  File "/home/user/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/home/user/instaloader/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "/home/user/instaloader/instaloader/__main__.py", line 104, in _main
    instaloader.login(username, password)
  File "/home/user/instaloader/instaloader/instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "/home/user/instaloader/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/home/user/.local/lib/python3.9/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by christoarmani** [comment]
I am unable to log on using +args.txt it just hangs.

**Comment by aandergr** [comment]
> I've also seen this but it didn't help me. #1150

How does this issue differ from #1150? They seem to report the same bug with the exact same error message.

**Comment by socialrupt** [comment]
> > I've also seen this but it didn't help me. #1150
> 
> How does this issue differ from #1150? They seem to report the same bug with the exact same error message.

**Comment by socialrupt** [comment]
> > I've also seen this but it didn't help me. #1150
> 
> How does this issue differ from #1150? They seem to report the same bug with the exact same error message.

It is the same, but there is no solution that works for me.
