### ISSUE TITLE
UnboundLocalError: local variable 'last_scraped'

### ISSUE THREAD

**Issue by UnixCro** [instaloader/instaloader#1203]
Hello dear developers of the impressive program. 

This morning I get this error message. Any ideas what that could be?

```
home@hostname ~ % instaloader --login=user --stories --no-posts theuserwhatiwant

Loaded session from /Users/home/.config/instaloader/session-user.
Logged in as user
[1/1] Downloading profile theuserwhatiwant
theuserwhatiwant/2019-07-04_16-28-11_UTC_profile_pic.jpg already exists
Downloading stories
[1/1] Retrieving stories from profile theuserwhatiwant.
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/instaloader/__main__.py", line 466, in main
    _main(loader,
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/instaloader/instaloader.py", line 1437, in download_profiles
    self.download_stories(userids=list(profiles), fast_update=fast_update, filename_target=None,
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/instaloader/instaloader.py", line 80, in call
    return func(instaloader, *args, **kwargs)
  File "/Users/home/Library/Python/3.8/lib/python/site-packages/instaloader/instaloader.py", line 810, in download_stories
    if last_scraped is not None and item.date_utc.replace(tzinfo=timezone.utc) <= last_scraped:
UnboundLocalError: local variable 'last_scraped' referenced before assignment
```

macOS Big Sur 10.16, instaloader version 4.8rc2

**Comment by aandergr** [comment]
Thanks for reporting! I released [4.8rc3](https://github.com/instaloader/instaloader/releases/tag/v4.8rc3) which includes the fix for this (#1204).
