### ISSUE TITLE
KeyError: 'graphql' on --fast-update

### ISSUE THREAD

**Issue by Leonardomorn** [instaloader/instaloader#1213]
So, i'm using the terminal to get some hashtags, when I use the command 

`   instaloader --login $VARLOGIN --password $VARPASS  "$VARHASHTAG" `

it works really well, but when I try 
 

`instaloader --login $VARLOGIN --password $VARSENHA --fast-update  "$VARHASHTAG"`

**I receive the output :**

Loaded session from /home/leonardo/.config/instaloader/session-caarvela.
Logged in as caarvela.
Traceback (most recent call last):
  File "/home/leonardo/anaconda3/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/leonardo/anaconda3/lib/python3.8/site-packages/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "/home/leonardo/anaconda3/lib/python3.8/site-packages/instaloader/__main__.py", line 157, in _main
    instaloader.download_hashtag(hashtag=target[1:], max_count=max_count, fast_update=fast_update,
  File "/home/leonardo/anaconda3/lib/python3.8/site-packages/instaloader/instaloader.py", line 1095, in download_hashtag
    hashtag = Hashtag.from_name(self.context, hashtag)
  File "/home/leonardo/anaconda3/lib/python3.8/site-packages/instaloader/structures.py", line 1325, in from_name
    hashtag._obtain_metadata()
  File "/home/leonardo/anaconda3/lib/python3.8/site-packages/instaloader/structures.py", line 1339, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "/home/leonardo/anaconda3/lib/python3.8/site-packages/instaloader/structures.py", line 1334, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'

**Comment by Leonardomorn** [comment]
it is the same thing as #1080 , i'm closing this post.
