### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None" for every action

### ISSUE THREAD

**Issue by aseques** [instaloader/instaloader#122]
About a week ago, instaloador was working fine in my pc, since today I get this error when calling instaloader from command line. I cheked with the current version both in windows and linux and the issue is the same.

```
Session file does not exist yet - Logging in.
Traceback (most recent call last):
  File "C:\Python36\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.0.2', 'console_scripts', 'instaloader')()
  File "c:\python36\lib\site-packages\instaloader\__main__.py", line 334, in main
    storyitem_filter_str=args.storyitem_filter)
  File "c:\python36\lib\site-packages\instaloader\__main__.py", line 87, in _main
    instaloader.login(username, password)
  File "c:\python36\lib\site-packages\instaloader\instaloader.py", line 324, in login
    self.context.login(user, passwd)
  File "c:\python36\lib\site-packages\instaloader\instaloadercontext.py", line 181, in login
    session.headers.update({'X-CSRFToken': resp.cookies['csrftoken']})
  File "c:\python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "c:\python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by aandergr** [comment]
Thanks for reporting this! I fixed it in version 4.0.3.
