### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by neutrongenious** [instaloader/instaloader#1224]
Does instaloader supports MFA (2FA)?

```
2FA error: This code is no longer valid. Please request a new one.
Enter 2FA verification code: 84513209         
2FA error: This code is no longer valid. Please request a new one.
Enter 2FA verification code: ^CTraceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 1385, in interactive_login
    self.login(username, password)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 236, in login
    raise TwoFactorAuthRequiredException("Login error: two-factor authentication required.")
instaloader.exceptions.TwoFactorAuthRequiredException: Login error: two-factor authentication required.

```

**Comment by neutrongenious** [comment]
Duplicate of #1217
