### ISSUE TITLE
Issue with +args.txt 

### ISSUE THREAD

**Issue by chrisl106** [instaloader/instaloader#1247]
I'm on v4.8 and I have made an args.txt document for public profiles which consists of:
```
--fast-update
--no-comments
--no-metadata-json
profile1
profile 2
profile 3
```

But when I run instaloader.exe +args.txt, I'm getting this error:
`Traceback (most recent call last):
  File "__main__.py", line 501, in <module>
  File "__main__.py", line 498, in __main
  File "__main__.py", line 467, in main
  File "__main__.py", line 212, in _main
IndexError: string index out of range
[22424] Failed to execute script __main__`

I'm pretty noobish so I'm sure this is a user error which is why I didn't want to post as a bug and instead a question. If anyone can shed light on this, I'd appreciate it, thanks!

**Comment by aandergr** [comment]
Hi. This error can be caused by an empty line in the `args.txt` file.
