### ISSUE TITLE
[3592] Failed to execute script __main__

### ISSUE THREAD

**Issue by BB159753** [instaloader/instaloader#1251]
[ 258/2639] [Do it] unchanged Traceback (most recent call last):
  File "__main__.py", line 501, in <module>
  File "__main__.py", line 498, in __main
  File "__main__.py", line 467, in main
  File "__main__.py", line 220, in _main
  File "instaloader\instaloader.py", line 1429, in download_profiles
  File "instaloader\instaloader.py", line 1002, in posts_download_loop
  File "instaloader\instaloader.py", line 720, in download_post
  File "instaloader\structures.py", line 382, in video_url
KeyError: 'video_versions'
[3592] Failed to execute script __main__

Using the newest version, not really sure what's happening here.

**Comment by Showmaster3000** [comment]
Your issus is incomplete.
You missed:
- the command line you used
- the version NUMBER
- the complete error output (in my opinion there is something missing)

**Comment by BB159753** [comment]
Ah, my bad.

- the command line you used
"./instaloader.exe [TargetProfile] --login [MyProfile]" 
- the version NUMBER
Latest one, 4.8.
- the complete error output (in my opinion there is something missing)
Nope, that's all sadly.

**Comment by aandergr** [comment]
Thanks for reporting. This is fixed in Version 4.8.1: if accessing the high-quality video candidates fails, Instaloader will log an error and fallback to a lower-quality version of the video.

If you like this tool, see https://instaloader.github.io/sponsors.html for how you can help the development of Instaloader.
