### ISSUE TITLE
KeyError when using {date_utc} in --dirname-pattern

### ISSUE THREAD

**Issue by mathisdt** [instaloader/instaloader#1254]
**Describe the bug**
I want to download all of my followees' content - posts, highlights, stories and IGTV. I want to have one directory per year in which all the followee's profiles are put as subdirectories, for example `/opt/instagram/2021/followee1` and `/opt/instagram/2021/followee2`. But when using the pattern `{date_utc}` (or to be more precise: `{date_utc:%Y}` in my case) in the `--dirname-pattern`, then a `KeyError` is raised and InstaLoader quits.
This dirname pattern used to work in an older version of InstaLoader (sadly I didn't take note which version it was).

**To Reproduce**
example command line:
```
/usr/local/bin/instaloader -l $USERNAME --password $PASSWORD --sessionfile $SESSIONFILE \
    --dirname-pattern /opt/instagram/{date_utc:%Y}/{profile} \
    --filename-pattern {date_utc}_{profile} \
    --no-metadata-json --no-video-thumbnails --fast-update --quiet \
    --highlights \
    --stories \
    --igtv \
    @myprofile
```

**Expected behavior**
The directory `/opt/instagram/2021/followeeprofilename` is created for all my followees' profile names.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/instaloader/__main__.py", line 467, in main
    _main(loader,
  File "/usr/local/lib/python3.9/dist-packages/instaloader/__main__.py", line 161, in _main
    instaloader.save_profile_id(followee)
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloader.py", line 1265, in save_profile_id
    os.makedirs(self.dirname_pattern.format(profile=profile.username,
KeyError: 'date_utc'
```

**Instaloader version**
4.8.1

**Additional context**
Maybe there's another way to achive my goal? If so, I'd be very happy to learn about it.

**Comment by mathisdt** [comment]
By experimenting a bit, I found the following way:

```
/usr/local/bin/instaloader -l $USERNAME --password $PASSWORD --sessionfile $SESSIONFILE \
    --dirname-pattern /opt/instagram/_ids \
    --filename-pattern ../{date_utc:%Y}/{profile}/{date_utc}_{profile} \
    --no-metadata-json --no-video-thumbnails --fast-update --quiet \
    --highlights \
    --stories \
    --igtv \
    @myprofile
```

All profile IDs are put into the directory `_ids` and the content is sorted into directories by year. :+1:
