### ISSUE TITLE
Not able to login when password contains a `:`

### ISSUE THREAD

**Issue by eelcovdw** [instaloader/instaloader#1292]
**Describe the bug**
I'm not able to login when password contains a `:`. It seems that instagram splits the password on `:`, which changes the password and causes a `BadCredentialsException` in Instaloader.

I've tried escaping with both `\:` and `%3A`, neither works.

**To Reproduce**
- change your password to something containing a `:`. Mine was generated by a password manager.
- in Python 3.8.8, attempt to login with the password.
- Change password to something without `:`, login works again. Other symbols don't seem to cause any issues.

**Expected behavior**
Succesful login with a password containing a `:`

**Error messages and tracebacks**

```
>>> import instaloader
>>> instaloader.__version__
'4.8.1'
>>> instaloader.Instaloader().login(username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eelco\Anaconda3\lib\site-packages\instaloader\instaloader.py", line 598, in login
    self.context.login(user, passwd)
  File "C:\Users\eelco\Anaconda3\lib\site-packages\instaloader\instaloadercontext.py", line 257, in login
    raise BadCredentialsException('Login error: Wrong password.')
instaloader.exceptions.BadCredentialsException: Login error: Wrong password.
```

**Instaloader version**
`4.8.1`, also tried with ` `feature/encrypt-password`, see below.

**Additional context**
I've attempted logging in with the `feature/encrypt-password` branch, this should solve the issue but causes a 403 - Forbidden:

```
~/dev/instaloader/instaloader/instaloadercontext.py in login(self, user, passwd)
    226             resp_json = login.json()
    227         except json.decoder.JSONDecodeError:
--> 228             raise ConnectionException("Login error: JSON decode fail, {} - {}.".format(login.status_code, login.reason))
    229         if resp_json.get('two_factor_required'):
    230             two_factor_session = copy_session(session, self.request_timeout)

ConnectionException: Login error: JSON decode fail, 403 - Forbidden.
```

**Comment by Showmaster3000** [comment]
The problem is already described in #741 and #849 including a workaround.

**Comment by aandergr** [comment]
Thanks for reporting, indeed, Instaloader's login fails when the password contains a colon.

`feature/encrypt-password` was outdated, I rebased it to current master, so that it now may be a functioning workaround. The firefox cookie import workaround described in our documentation should work fine; also the trivial workaround of using a password that does not contain a colon should work.
