### ISSUE TITLE
KeyError: 'post'

### ISSUE THREAD

**Issue by davispuh** [instaloader/instaloader#132]
Need better error message.
This used to work.

```
$ instaloader -F -G -C --metadata-json -l <XXX> -f ./instagram.session --filename-pattern '{post.mediaid} - {date:%Y-%m-%d_%H-%M-%S}' --dirname-pattern ./ <XXX>
Loaded session from ./instagram.session.
Logged in as <XXX>

profile <XXX> could also be downloaded anonymously.
Retrieving posts from profile <XXX>.
[  1/ 87] Traceback (most recent call last):
  File "/usr/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.0.3', 'console_scripts', 'instaloader')()
  File "/usr/lib/python3.6/site-packages/instaloader/__main__.py", line 334, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/lib/python3.6/site-packages/instaloader/__main__.py", line 147, in _main
    storyitem_filter=storyitem_filter)
  File "/usr/lib/python3.6/site-packages/instaloader/instaloader.py", line 732, in download_profile
    downloaded = self.download_post(post, target=profile_name)
  File "/usr/lib/python3.6/site-packages/instaloader/instaloader.py", line 340, in download_post
    filename = dirname + '/' + _PostPathFormatter(post).format(self.filename_pattern, target=target)
  File "/usr/lib/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib/python3.6/site-packages/instaloader/instaloader.py", line 72, in vformat
    ret = super().vformat(format_string, args, kwargs)
  File "/usr/lib/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.6/string.py", line 234, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib/python3.6/site-packages/instaloader/instaloader.py", line 56, in get_field
    return super().get_field(field_name, args, kwargs)
  File "/usr/lib/python3.6/string.py", line 299, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/lib/python3.6/string.py", line 256, in get_value
    return kwargs[key]
KeyError: 'post'
```

changed `{post.mediaid}` to `{mediaid}` and it works.

**Comment by aandergr** [comment]
Your filename pattern requests the key `post`, which is not defined. Also, our error message obviously helped you to solve the problem. Hence `KeyError: 'post'` is a perfect error message. So what's the point.
