### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by LordNyrox** [instaloader/instaloader#1323]
**Describe the bug**
I cant login 

**To Reproduce**
instaloader -login MY USER NAME

**Error messages and tracebacks**
Session file does not exist yet - Logging in.
Enter Instagram password  for MY USER NAME
Traceback (most recent call last):
  File "/usr/share/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/usr/share/instaloader/instaloader/__main__.py", line 423, in main
    _main(loader,
  File "/usr/share/instaloader/instaloader/__main__.py", line 106, in _main
    instaloader.interactive_login(username)
  File "/usr/share/instaloader/instaloader/instaloader.py", line 1241, in interactive_login
    self.login(username, password)
  File "/usr/share/instaloader/instaloader/instaloader.py", line 476, in login
    self.context.login(user, passwd)
  File "/usr/share/instaloader/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Instaloader version**
4.4.5

im on kali linux

**Comment by LordNyrox** [comment]
i try but 
sudo apt-get upgrade instaloader       
[sudo] password for nyrox: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
instaloader is already the newest version (4.4.5-0kali1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Showmaster3000** [comment]
This package is rather old. Its from july 2020.
The easiest thing is to use pip, see manual: https://instaloader.github.io/
Remove the package you installed before, just to make sure there is no conflict.
Another possibility is to download the latest release from github. Then install python3 and use the script version.

**Comment by LordNyrox** [comment]
Thanks for the help it worked
