### ISSUE TITLE
resume info not saved with ConnectionException

### ISSUE THREAD

**Issue by bipsen** [instaloader/instaloader#1339]
**Describe the bug**
I am using the python module to download followers of profiles with the resumable_iteration context manager, so that a resume_info file is saved on errors. However, for some reason, if the error thrown is an Instaloader ConnectionException, no resume info file is saved. I think this is a bug.

**To Reproduce**
I run something like the following script, and sometimes encounter a ConnectionException.

```
with instaloader.resumable_iteration(
    context=L.context,
    iterator=dl_iterator,
    load=instaloader.load_structure_from_file,
    save=instaloader.save_structure_to_file,
    format_path=lambda magic: f"resume_info_{magic}.json.xz",
) as (is_resuming, start_index):
    if is_resuming:
        next(dl_iterator)
    for follower in dl_iterator:
        print(follower)
```

**Expected behavior**
I expect a resume_info file to be saved, just as if the script had crashed with any other error.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4533a6c610>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a6c610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 325, in get_json
    resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a6c610>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/bertil/anaconda3/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4533a6cbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a6cbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 325, in get_json
    resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a6cbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/bertil/anaconda3/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4533a761c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a761c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 325, in get_json
    resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a761c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "script.py", line 73, in <module>
    for fol in tqdm(dl_iterator, desc=user_id, initial=start_index, total=profile.followers):
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 135, in __next__
    query_response = self._query(self._data['page_info']['end_cursor'])
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 101, in _query
    self._context.graphql_query(
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 428, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/home/bertil/anaconda3/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 384, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /graphql/query?query_hash=37479f2b8209594dde7facb0d904896a&variables=%7B%22id%22%3A%227117485047%22%2C%22first%22%3A50%2C%22after%22%3A%22QVFDaG1mci1JOWJTdjRYaE1JUUh6UmdtMC1hR2dUT3JaOC1keDRlUkxkLTlLRHJzZlhqRzY2QlNPV2pSR1NtRk85ZldVMk1vdXdYeW8xbGptNUpiV1VEVA%3D%3D%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4533a761c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Instaloader version**
4.8.1

**Comment by aandergr** [comment]
Hi! As stated in the documentation for [resumable_iteration()](https://instaloader.github.io/module/nodeiterator.html#resumable-iteration), and in https://github.com/instaloader/instaloader/issues/1164#issuecomment-882478809, the resumable_iteration() context saves the resume file only if a KeyboardInterrupt or an AbortDownloadException occurs. However, you can catch any exception inside the resumable_iteration() context, and re-raise it as an AbortDownloadException to save the resume file.
