### ISSUE TITLE
ProfileNotExistException but it is there

### ISSUE THREAD

**Issue by evan533** [instaloader/instaloader#1343]
Hi, I've been using instaloader lately and I found this error. I run this with a lot of data in a list and encounter this exception. Its suggesting a similar username which is the same that I provided.

```
Traceback (most recent call last):
  File "D:\Work\PROJECTS\igscraping\env\lib\site-packages\instaloader\structures.py", line 691, in _obtain_metadata
    self._node = metadata['entry_data']['ProfilePage'][0]['graphql']['user']
KeyError: 'ProfilePage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Work\PROJECTS\igscraping\username_instaloader.py", line 72, in <module>
    profile = get_username_data(username)
  File "D:\Work\PROJECTS\igscraping\username_instaloader.py", line 44, in get_username_data
    profile = instaloader.Profile.from_username(L.context,text)
  File "D:\Work\PROJECTS\igscraping\env\lib\site-packages\instaloader\structures.py", line 635, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
  File "D:\Work\PROJECTS\igscraping\env\lib\site-packages\instaloader\structures.py", line 697, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.\nThe most similar profile{}: {}.'
instaloader.exceptions.ProfileNotExistsException: Profile babyfood_fiezakhazali does not exist.
The most similar profile is: babyfood_fiezakhazali.
```

**Comment by Showmaster3000** [comment]
Your issue description is incomplete. At least you didn't mention the instaloader version and your commandline.

But if I open the profile in browser without being logged in, I see the following message:
`Restricted profile - You must be 20 years old or over to see this profile`
So this can be the problem.

**Comment by evan533** [comment]
Yeah sorry about that, I'm using instaloader v 4.8.1 and I'm using the module in python not commandline, basically its just function returning a user profile, but I'm using a list of usernames (thousands and more).

```
def get_username_data(text):
    profile = instaloader.Profile.from_username(L.context,text)
    return profile
```
