### ISSUE TITLE
Issue in :saved

### ISSUE THREAD

**Issue by UnixCro** [instaloader/instaloader#1357]
```
instaloader version: 4.9b1
```
<br>

```
.../files/instaloader $ instaloader --login=username :saved

Loaded session from /data/data/com.termux/files/home/.config/instaloader/session-username.
Logged in as username
Retrieving saved posts...
[   1/1332] Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instaloader", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9b1', 'console_scripts', 'instaloader')())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/__main__.py", line 467, in main
    _main(loader,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/__main__.py", line 178, in _main
    instaloader.download_saved_posts(fast_update=fast_update, max_count=max_count,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/instaloader.py", line 1076, in download_saved_posts
    self.posts_download_loop(node_iterator, ":saved",
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/instaloader.py", line 1007, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/instaloader.py", line 667, in download_post
    filename = self.__prepare_filename(filename_template, lambda: post.url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/instaloader/instaloader.py", line 625, in __prepare_filename
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/data/data/com.termux/files/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: ':saved'
```

**Comment by Thammus** [comment]
This is a known problem on file systems that do not support certain characters (#575) like `:`. However, you can use [--dirname-pattern](https://instaloader.github.io/basic-usage.html#filename-specification) to specify a different target directory.

**Comment by Thammus** [comment]
This is a known problem on file systems that do not support certain characters (#575) like `:`. However, you can use [--dirname-pattern](https://instaloader.github.io/basic-usage.html#filename-specification) to specify a different target directory.

**Comment by UnixCro** [comment]
Thanks for your helpful answer @Thammus.

But this parameter also works when downloading highlights.  Because this did not work for me, because instaloader tries for me with the `--dirname-pattern=` argument to download only into the folder shown, but `subdirectories` are created for highlights that have the same name as the highlights.  

And highlights with the name `<3` cause a problem for me on the external SD card.

**Comment by Thammus** [comment]
The current logic to download highlights into subdirectories that are named according to the name of the respective highlight is not adjustable by a flag. In order to be able to download highlights with uncommon characters in their name one must use a capable filesystem or implement a custom logic to download highlights into directories that do not use the name.

**Comment by UnixCro** [comment]
All right, maybe there will be a parameter that Instaloader says, for example, if the character `>` comes, it should ignore the character and instead leave it blank.  Like `—ignore='>'`

**Comment by Thammus** [comment]
Such a functionality has been discussed in #576 and related issues (like PR #854).
