### ISSUE TITLE
ImportError: DLL load failed while importing _lzma

### ISSUE THREAD

**Issue by ussaohelcim** [instaloader/instaloader#1368]
**Describe the bug**
I cant use, it stopped to work today.

**To Reproduce**
It just doesn't open. 
``instaloader --version``
```
Traceback (most recent call last):
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.8.2', 'console_scripts', 'instaloader')())
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\defal\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\defal\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloader.py", line 24, in <module>
    from .nodeiterator import NodeIterator, resumable_iteration
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\nodeiterator.py", line 7, in <module>
    from lzma import LZMAError
  File "c:\users\defal\appdata\local\programs\python\python39\lib\lzma.py", line 27, in <module>
    from _lzma import *
ImportError: DLL load failed while importing _lzma: Não foi possível encontrar o procedimento especificado.
```
If i use as a module it also doesnt work. 

**Expected behavior**
It was expected to work.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "D:\20212\projetosGit\instalker\instalker.py", line 1, in <module>
    import instaloader, json, sys
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 24, in <module>
    from .nodeiterator import NodeIterator, resumable_iteration
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\nodeiterator.py", line 7, in <module>
    from lzma import LZMAError
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\lib\lzma.py", line 27, in <module>
    from _lzma import *
ImportError: DLL load failed while importing _lzma: Não foi possível encontrar o procedimento especificado.
```
**Instaloader version**
`instaloader --version` output.
I cant use this command, but the version is instaloader-4.8.2.

**Comment by ussaohelcim** [comment]
Same thing with v 4.8.1
```
instaloader --version
Traceback (most recent call last):
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.8.1', 'console_scripts', 'instaloader')())
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\defal\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\defal\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloader.py", line 24, in <module>
    from .nodeiterator import NodeIterator, resumable_iteration
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\nodeiterator.py", line 7, in <module>
    from lzma import LZMAError
  File "c:\users\defal\appdata\local\programs\python\python39\lib\lzma.py", line 27, in <module>
    from _lzma import *
ImportError: DLL load failed while importing _lzma: Não foi possível encontrar o procedimento especificado.
```
Same thing with v 4.8
```
instaloader --version
Traceback (most recent call last):
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.8', 'console_scripts', 'instaloader')())
  File "C:\Users\defal\AppData\Local\Programs\Python\Python39\Scripts\instaloader-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\defal\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\defal\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\instaloader.py", line 24, in <module>
    from .nodeiterator import NodeIterator, resumable_iteration
  File "c:\users\defal\appdata\local\programs\python\python39\lib\site-packages\instaloader\nodeiterator.py", line 7, in <module>
    from lzma import LZMAError
  File "c:\users\defal\appdata\local\programs\python\python39\lib\lzma.py", line 27, in <module>
    from _lzma import *
ImportError: DLL load failed while importing _lzma: Não foi possível encontrar o procedimento especificado.
```

**Comment by ussaohelcim** [comment]
Started to work again, i did nothing.
