### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 500 when get comments from Post

### ISSUE THREAD

**Issue by comedsh** [instaloader/instaloader#1389]
With instaloader v4.8.2. About 2 days ago, if get comments from Post raised the errors below,
```bash
Traceback (most recent call last):
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 351, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 500.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instacrawler/crawler.py", line 1255, in _crawl_entity
    comments = CommentHelper.extract_comments(post)
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instacrawler/helper.py", line 230, in extract_comments
    for c in post.get_comments():  
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/structures.py", line 507, in get_comments
    return NodeIterator(
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 92, in __init__
    self._data = self._query()
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 101, in _query
    self._context.graphql_query(
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 428, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/Users/shangyang/workspace/spider/instaspider/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 384, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 500.
```
and the error is continuous thrown recent days, so I'm sure it is NOT the issue from INS side. and the sample code as below, 
```python
L = instaloader.Instaloader(.....)
L.load_session_from_file(username=username, filename=session_save_path)
post = Post.from_shortcode(L.context, shortcode)
for c in post.get_comments():  
      .....
```
if try to get_comments from post will raise the error above. Has someone met the same errors? is INS changes backend API?

**Comment by rsa408** [comment]
@comedsh 
try this, it works for me.
```
L.load_session_from_file(username)
post = instaloader.Post.from_shortcode(L.context, SHORTCODE)
for c in post.get_comments():
	print(c)

```

**Comment by aandergr** [comment]
I cannot reproduce this error. Does it still occur? Is there a specific post where this error raised when attempting to access its comments?
