### ISSUE TITLE
CMD: KeyError: 'graphql'

### ISSUE THREAD

**Issue by jcjms** [instaloader/instaloader#1450]
**Description**
I get this error when I type the line (shown below) in the cmd.

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\__main__.py", line 467, in main
    _main(loader,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\__main__.py", line 164, in _main
    instaloader.download_hashtag(hashtag=target[1:], max_count=max_count, fast_update=fast_update,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\instaloader.py", line 1178, in download_hashtag
    hashtag = Hashtag.from_name(self.context, hashtag)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\structures.py", line 1381, in from_name
    hashtag._obtain_metadata()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\structures.py", line 1395, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\structures.py", line 1390, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'
```

**To Reproduce**
`instaloader --login <your_username> --count 10 --no-captions --no-metadata-json --filename-pattern={profile}_{date_utc}_UTC "#car"`

**Expected behavior**
It should download 10 images with the hashtag 'car' and the specific file caption.

**Instaloader version**
4.8.4

**Comment by OfraKlein** [comment]
I get the same error "keyerror: Graphql" after searching for hashtags. Seems liek this is an old issue, any solutions? 

![image](https://user-images.githubusercontent.com/26406791/158779496-150a21b2-76fe-4ba1-8da0-76531fb2e615.png)

**Comment by OfraKlein** [comment]
Thank you, this is great and indeed the error does not occur. Now I get a new problem, in that no matter how big the hashtag (how many posts are grouped below it), it only gathers 30 hashtags - or 30 json files if I try that alone. It keeps giving the message that the image or file exists, even though it does not, as shown in the image here:
![image](https://user-images.githubusercontent.com/26406791/159034953-08db96dc-156e-4c06-a01a-39071b4c9f2d.png)
