### ISSUE TITLE
list index out of range 

### ISSUE THREAD

**Issue by i998979** [instaloader/instaloader#1460]
**Describe the bug**
I just run the following command, and an list index out of range error is thrown

**To Reproduce**
```C:\Users\brian\Downloads\instaloader.exe --login=MY_ACC --filename-pattern="Story\{filename}" --no-video-thumbnails --no-captions --no-metadata-json --no-posts --no-iphone --highlights profile "ho_pui"```

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).
Expected to download properly...

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
```
[ 89/ 97] Warning: Unable to fetch video from graphql of <StoryItem 2618268297992604248>: list index out of range
Warning: Unable to fetch video from graphql of <StoryItem 2618268297992604248>: list index out of range
Traceback (most recent call last):
  File "__main__.py", line 501, in <module>
  File "__main__.py", line 498, in __main
  File "__main__.py", line 467, in main
  File "__main__.py", line 220, in _main
  File "instaloader\instaloader.py", line 1421, in download_profiles
  File "instaloader\instaloader.py", line 80, in call
  File "instaloader\instaloader.py", line 926, in download_highlights
  File "instaloader\instaloader.py", line 854, in download_storyitem
  File "instaloader\instaloader.py", line 96, in call
  File "instaloader\instaloader.py", line 315, in download_pic
  File "C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\re.py", line 201, in search
TypeError: expected string or bytes-like object
[3396] Failed to execute script __main__
```

**Instaloader version**
`instaloader --version` output.
4.8.4, 4.8.5

**Additional context**
Running the command without --no-iphone works fine but slower, with --no-iphone runs faster but stopped at that place

**Comment by aandergr** [comment]
Thanks for reporting. Indeed, this is reproducible. Instaloader seems to fail on a data inconsistency on this StoryItem. The field `video_resources` is empty, even though the StoryItem in question actually is a video, and the iPhone query does return video URLs.

**Comment by DReaper** [comment]
I am getting this error too.

[ 19/ 99] \Q&A\2022-04-26_04-37-23_UTC.jpg exists Warning: Unable to fetch video from graphql of <StoryItem 2824677720604339095>: list index out of range
Unable to fetch high-quality video version of <StoryItem 2824677720604339095>: 'video_versions'
Traceback (most recent call last):
  File "__main__.py", line 505, in <module>
  File "__main__.py", line 502, in __main
  File "__main__.py", line 471, in main
  File "__main__.py", line 220, in _main
  File "instaloader\instaloader.py", line 1456, in download_profiles
  File "instaloader\instaloader.py", line 81, in call
  File "instaloader\instaloader.py", line 960, in download_highlights
  File "instaloader\instaloader.py", line 887, in download_storyitem
  File "instaloader\instaloader.py", line 97, in call
  File "instaloader\instaloader.py", line 340, in download_pic
  File "re.py", line 201, in search
TypeError: expected string or bytes-like object
[25588] Failed to execute script '__main__' due to unhandled exception!

**Comment by Xomps** [comment]
I am also getting this error on latest version (4.9.3), using --no-iphone made no difference.

**Comment by IljaM13** [comment]
As workaround: run with --highlights and --fast-update
This will skip already downloaded highlights and won't run into exception.
Maybe it will crash with one of the following highlights. Just go on until you got them all. :-)
