### ISSUE TITLE
SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version)

### ISSUE THREAD

**Issue by RVFET** [instaloader/instaloader#1485]
**Describe the bug**
I made a script that automatically downloads videos from various Instagram profiles. It was working fine but today it's broken. Instaloader can't log in anymore.

**To Reproduce**
**SOURCE CODE OF MY SCRIPT**

```from datetime import datetime, timedelta
import time
import os
import instaloader

def gen(start, end, posts):
    for post in posts:
        if post.date > start and post.date > end:
            pass
        elif post.date >= start and post.date <= end:
            yield post
        elif post.date <= start:
            break


L = instaloader.Instaloader(
    save_metadata=False,
    download_pictures=False,
    post_metadata_txt_pattern='',
    filename_pattern="{profile}_{shortcode}",
    user_agent="useragent")
L.login("username", "password")

IGusernames = [
    "user"
]

def downloadVideos(in_last_x_hours):
    startDate = datetime.now() - timedelta(hours=in_last_x_hours)
    endDate = datetime.today()
    script_start = time.time()
    checked_post_count = 0
    for IGusername in IGusernames:
        profile = instaloader.Profile.from_username(L.context, IGusername)
        posts = profile.get_posts()
        for post in gen(start=startDate, end=endDate, posts=posts):
            script_end = time.time()
            past_time = ""
            date_time_spent = float(str(script_end - script_start)[:4])
            if float(str(date_time_spent)) // 60 >=1.0:
                past_time = str(date_time_spent//60) + " minutes, and " + str(round(date_time_spent % 60)) + " seconds."
            else:
                past_time = str(round(date_time_spent % 60)) + " seconds."

            os.system("cls")
            print("==================================================")
            print(f"Total time spent: {past_time}".center( 50, " "))
            print(f"Checked post count: {checked_post_count}".center(50, " "))
            print(f"Publish date: {post.date}".center(50, " "))
            print(f"Url: https://instagram.com/p/{post.shortcode}".center(50, " "))
            print(f"Is video: {post.is_video}".center(50, " "))
            L.download_post(post, "videos")
            checked_post_count += 1


print("\n========================= RUNNING SCRIPT =========================\n")
downloadVideos(in_last_x_hours = 20)
print("Done.")
```

**Expected behavior**
As I said, it was working fine until today and it was just downloading "video" posts from various Instagram profiles that I defined inside IGUsernames variable.

**Error messages and tracebacks**
```JSON Query to accounts/login/: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)'))) [retrying; skip with ^C]
JSON Query to accounts/login/: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)'))) [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 325, in get_json
    resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 325, in get_json
    resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 325, in get_json
    resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 22, in <module>
    L.login("username", "password")
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 611, in login
    self.context.login(user, passwd)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 214, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "C:\Users\RVFET\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 384, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to accounts/login/: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /accounts/login/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)')))
```

**Instaloader version**
`instaloader --version` 4.8.5.

*EDITED BECAUSE ACCIDENTALLY LEAKED MY INSTAGRAM PASSWORD INSIDE ERROR LOG*

**Comment by aandergr** [comment]
Not related to Instaloader.
