### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by gggggg116** [instaloader/instaloader#149]
I used instaloader for two days and it worked fine but today every time that I tried to use it I got this error:
`Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.5/site-packages/instaloader/__main__.py", line 324, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/pi/.local/lib/python3.5/site-packages/instaloader/__main__.py", line 87, in _main
    instaloader.login(username, password)
  File "/home/pi/.local/lib/python3.5/site-packages/instaloader/instaloader.py", line 317, in login
    self.context.login(user, passwd)
  File "/home/pi/.local/lib/python3.5/site-packages/instaloader/instaloadercontext.py", line 169, in login
    session.headers.update({'X-CSRFToken': resp.cookies['csrftoken']})
  File "/home/pi/.local/lib/python3.5/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

Edit: when only instaloader is installed I get the "Too many queries in the last time" error and if I use: 
`pip3 install --upgrade git+https://github.com/instaloader/instaloader@issue_112_fix`
I get the error above.

**Comment by FinnMal** [comment]
Any updates on this? I still get this error :/
