### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by jesuschirst523** [instaloader/instaloader#1505]
**Describe the bug**
i can't login 

**To Reproduce**
instaloader --login username --password pswd

**Expected behavior**
i expect to get a link and sign through that link 

**Error messages and tracebacks**
Session file does not exist yet - Logging in.
Traceback (most recent call last):
  File "/usr/share/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/usr/share/instaloader/instaloader/__main__.py", line 423, in main
    _main(loader,
  File "/usr/share/instaloader/instaloader/__main__.py", line 96, in _main
    instaloader.login(username, password)
  File "/usr/share/instaloader/instaloader/instaloader.py", line 476, in login
    self.context.login(user, passwd)
  File "/usr/share/instaloader/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/home/kali/.local/lib/python3.9/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Instaloader version** - 4.9 *latest*

**Additional context**
i am using kali linux on vmware.
how i did it:
pip3 install instaloader
also i git clone https://github.com/instaloader/instaloader.git

anyone know how to solve it thanks

**Comment by aandergr** [comment]
Reminds me of #62.

Does uninstalling the `simplejson` python package resolve this problem?
