### ISSUE TITLE
Failed to establish a new connection: [Errno 1100 4] getaddrinfo failed'))

### ISSUE THREAD

**Issue by tania010** [instaloader/instaloader#1515]
**Describe the bug**
download ends in error while downloading stories, the 5th story (set?). but there are a LOT more stories. (not sure how to be more precise, error log attached)

**To Reproduce**
(e.g. Instaloader command line)

instaloader --login=username profile [profile ...] --stories --igtv --highlights

**Expected behavior**
for instaloader to download all the posts + stories + igtv videos + all the highlights

**Error messages and tracebacks**

Too many queries in the last time. Need to wait 39 seconds, until 15:53.
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 174, in _new_
conn
    conn = connection.create_connection(
  File "C:\Python38\lib\site-packages\urllib3\util\connection.py", line 72, in c
reate_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 703, in u
rlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 386, in _
make_request
    self._validate_conn(conn)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 1040, in
_validate_conn
    conn.connect()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 358, in conne
ct
    conn = self._new_conn()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 186, in _new_
conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection objec
t at 0x000000000365C280>: Failed to establish a new connection: [Errno 11004] ge
taddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 785, in u
rlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='scontent-ort2-2.cdni
nstagram.com', port=443): Max retries exceeded with url: /v/t50.12441-16/5548285
4_322219588437034_4283658331024198201_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2Rf
dXJsZ2VuLjY0MC5zdG9yeS5kZWZhdWx0IiwicWVfZ3JvdXBzIjoiW1wiaWdfd2ViX2RlbGl2ZXJ5X3Z0
c19vdGZcIl0ifQ&_nc_ht=scontent-ort2-2.cdninstagram.com&_nc_cat=110&_nc_ohc=C07Ih
2JSnT8AX-BBizb&tn=MvjvbnC80PpRj-YD&edm=AHlfZHwBAAAA&vs=17984560918207161_1938544
162&_nc_vs=HBksFQAYJEdPYVpUZ01xeEJ1WURpVUJBRGtLMTJlT25ISTdicGt3QUFBRhUAAsgBABUAG
CRHSUZkVGdNM0RLbTM3ajBIQUctOXRESFl5MEp5YnBrd0FBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBM
RUAACao7emn%2FpOLQBUCKAJDMywXQC49cKPXCj0YEmRhc2hfYmFzZWxpbmVfMV92MREAdegHAA%3D%3
D&ccb=7-4&oe=626D10F3&oh=00_AT8EKdQSy8a60gwXrO8_nNKtbPQs2Kry3_8qBCfXkjLPmw&_nc_s
id=21929d (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection obj
ect at 0x000000000365C280>: Failed to establish a new connection: [Errno 11004]
getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\instaloader\__main__.py", line 471, in mai
n
    _main(loader,
  File "C:\Python38\lib\site-packages\instaloader\__main__.py", line 220, in _ma
in
    instaloader.download_profiles(profiles,
  File "C:\Python38\lib\site-packages\instaloader\instaloader.py", line 1450, in
 download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=
storyitem_filter)
  File "C:\Python38\lib\site-packages\instaloader\instaloader.py", line 81, in c
all
    return func(instaloader, *args, **kwargs)
  File "C:\Python38\lib\site-packages\instaloader\instaloader.py", line 961, in
download_highlights
    downloaded = self.download_storyitem(item, highlight_target)
  File "C:\Python38\lib\site-packages\instaloader\instaloader.py", line 888, in
download_storyitem
    self.download_pic(filename=filename, url=item.video_url, mtime=date_local))
  File "C:\Python38\lib\site-packages\instaloader\structures.py", line 1240, in
video_url
    int(self._context.head(version_url, allow_redirects=True).headers.get('Conte
nt-Length', 0)),
  File "C:\Python38\lib\site-packages\instaloader\instaloadercontext.py", line 5
42, in head
    resp = anonymous_session.head(url, allow_redirects=allow_redirects)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 564, in head
    return self.request('HEAD', url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 529, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scontent-ort2-2.c
dninstagram.com', port=443): Max retries exceeded with url: /v/t50.12441-16/5548
2854_322219588437034_4283658331024198201_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b
2RfdXJsZ2VuLjY0MC5zdG9yeS5kZWZhdWx0IiwicWVfZ3JvdXBzIjoiW1wiaWdfd2ViX2RlbGl2ZXJ5X
3Z0c19vdGZcIl0ifQ&_nc_ht=scontent-ort2-2.cdninstagram.com&_nc_cat=110&_nc_ohc=C0
7Ih2JSnT8AX-BBizb&tn=MvjvbnC80PpRj-YD&edm=AHlfZHwBAAAA&vs=17984560918207161_1938
544162&_nc_vs=HBksFQAYJEdPYVpUZ01xeEJ1WURpVUJBRGtLMTJlT25ISTdicGt3QUFBRhUAAsgBAB
UAGCRHSUZkVGdNM0RLbTM3ajBIQUctOXRESFl5MEp5YnBrd0FBQUYVAgLIAQAoABgAGwGIB3VzZV9vaW
wBMRUAACao7emn%2FpOLQBUCKAJDMywXQC49cKPXCj0YEmRhc2hfYmFzZWxpbmVfMV92MREAdegHAA%3
D%3D&ccb=7-4&oe=626D10F3&oh=00_AT8EKdQSy8a60gwXrO8_nNKtbPQs2Kry3_8qBCfXkjLPmw&_n
c_sid=21929d (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection
object at 0x000000000365C280>: Failed to establish a new connection: [Errno 1100
4] getaddrinfo failed'))

**Instaloader version**
`instaloader --version` output.
4.9

**Additional context**

**Comment by Showmaster3000** [comment]
`[Errno 11004] getaddrinfo failed` looks like a connection problem on your side.

**Comment by aandergr** [comment]
Similar errors have been reported in https://github.com/instaloader/instaloader/issues/107 and https://github.com/instaloader/instaloader/issues/138.  Is there a DNS blocking in your country, or a firewall or ad blocker installed on your network? I am closing this since it seems like a problem on behalf of your network, which we cannot fix. If it still cannot be solved, please reopen this issue and provide us more information.
