### ISSUE TITLE
 --latest-stamps permission error

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [instaloader/instaloader#1538]
**Describe the bug**
running with  --latest-stamps gives permission error.

it runs fine the first time. not any time after that.

runs fine without --latest-stamps. runs fine with --fast-update.

**To Reproduce**
args.txt
--login=
--password=
--stories
--highlights
--igtv
--no-captions
--sanitize-paths
--no-video-thumbnails
--no-iphone
--latest-stamps
nymphzhu
kittycatmayb
olivelingerie
pastel.bunni
dentelle.doll

**Expected behavior**
I expect it to download the newest posts

**Error messages and tracebacks**
D:\insta>cmd /k instaloader +args.txt
Using latest stamps from nymphzhu.
Loaded session from C:\Users\user\AppData\Local\Instaloader\session-user.
Logged in as user.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9', 'console_scripts', 'instaloader')())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\__main__.py", line 471, in main
    _main(loader,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\__main__.py", line 182, in _main
    profile = instaloader.check_profile_id(target, latest_stamps)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\instaloader.py", line 1357, in check_profile_id
    latest_stamps.save_profile_id(profile.username, profile.userid)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\lateststamps.py", line 46, in save_profile_id
    self._save()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\lateststamps.py", line 28, in _save
    with open(self.file, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'nymphzhu'

**Instaloader version**
4.9

**Comment by ekalin** [comment]
`--latest-stamps` takes an (optional) argument specifying the file in which to save the timestamps. In your case, `nymphzhu` is being considered as a filename, and it seems you don't have write permissions in the current directory.

Either add a `--` before the profiles to stop option parsing (`... --latest-stamps -- nymphzhu ...`) or move that options before another (if what follows is another option, the command line parser knows no argument has been passed to `--latest-stamps`: `... --no-video-thumbnails --latest-stamps --no-iphone nymphzhu ...`).
