### ISSUE TITLE
Frequent ConnectionExceptions started yesterday

### ISSUE THREAD

**Issue by twitter-79** [instaloader/instaloader#1616]
**Describe the bug**
Since yesterday around midday I'm starting to get a lot more ConnectionExceptions than before. My sockpuppets mostly have around 3-4 profiles that get scraped randomly twice a day downloading the latest new posts (at maximum 10) and all new stories. This was working like a charm till we had to fix the missing window.shared_data in version 4.9.1. Afterwards I started to see 429 Errors more frequently and today most of the sockpuppets got logged out.

**To Reproduce**
My code is something like this (broken down to relevant part):
```
profile = Profile.from_id(api.context, int(identifier))
posts = list()
for count, element in enumerate(profile.get_posts(), start=1):
    if count > 10:
        break
    posts.append(element)

stories = [item for story in api.get_stories([profile.userid]) for item in story.get_items()]
return posts + stories
```

**Expected behavior**
It should still be possible to scrape around ~15-20 profiles saving only the new posts and stories twice a day when using 5 sockpuppets from one machine. This is not "that much" of data.

**Error messages and tracebacks**
Relevant part is this one for example:
```
raised unexpected: ConnectionException('JSON Query to graphql/query: Redirected to login')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 338, in get_json
    raise TooManyRequestsException("Redirected to login")
instaloader.exceptions.TooManyRequestsException: Redirected to login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 338, in get_json
    raise TooManyRequestsException("Redirected to login")
instaloader.exceptions.TooManyRequestsException: Redirected to login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 338, in get_json
    raise TooManyRequestsException("Redirected to login")
instaloader.exceptions.TooManyRequestsException: Redirected to login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 [... my code ...]
    stories = [item for story in api.get_stories([profile.userid]) for item in story.get_items()]
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 798, in get_stories
    stories = self.context.graphql_query("303a4ae99711322310f25250d988f3b7",
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 428, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 384, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: Redirected to login
```

**Instaloader version**
Was using instaloader version 4.9.1, but it does not seem that there are relevant changes to this in 4.9.2

**Additional context**
Maximum number of requests in 429 warning I could find in the logs of the last days was 21 iPhone requests. I remember times where I have seen those errors with way higher 3-digit numbers and nothing happened. Seems instagram is getting stricter every day.

**Comment by aandergr** [comment]
Thanks for reporting! I have not yet fully confirmed it, but that suggests that we may have to verify and eventually adjust the default rate controller.
