### ISSUE TITLE
[Git Bash] UnicodeEncodeError

### ISSUE THREAD

**Issue by victoryy2003** [instaloader/instaloader#1631]
**Describe the bug**
When using Git Bash to run the following code threw out the following exceptions.
I had used Windows Python interpreter and MSYS2 Python interpreter for testing, both given the same results.

**To Reproduce**
Run it using Git Bash:
`C:/Git/bin/bash.exe -lic "stdbuf -o0 -e0 instaloader.exe --login=username --password=password --no-captions --no-metadata-json --igtv --highlights --latest-stamps stamps.ini --sessionfile=session --abort-on=400,403,429 > Instaloader.log 2>&1"`

**Error messages and tracebacks**
```
Retrieving IGTV videos for profile XXXXXXXX.
Traceback (most recent call last):
  File "C:/MSYS64/mingw64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/MSYS64/mingw64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:/MSYS64/mingw64/bin/instaloader.exe/__main__.py", line 7, in <module>
  File "C:/MSYS64/mingw64/lib/python3.10/site-packages/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "C:/MSYS64/mingw64/lib/python3.10/site-packages/instaloader/__main__.py", line 220, in _main
    instaloader.download_profiles(profiles,
  File "C:/MSYS64/mingw64/lib/python3.10/site-packages/instaloader/instaloader.py", line 1457, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "C:/MSYS64/mingw64/lib/python3.10/site-packages/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "C:/MSYS64/mingw64/lib/python3.10/site-packages/instaloader/instaloader.py", line 949, in download_highlights
    self.context.log("Retrieving highlights \"{}\" from profile {}".format(user_highlight.title, name))
  File "C:/MSYS64/mingw64/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 107, in log
    print(*msg, sep=sep, end=end, flush=flush)
  File "C:/MSYS64/mingw64/lib/python3.10/encodings/cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 23-25: character maps to <undefined>
```

**Instaloader version**
MSYS2 / Windows == `4.9.2`

**Python version**
MSYS2 / Windows == `3.10.5`

**Comment by fireattack** [comment]
I don't think it's related to instaloader at all. Windows by default don't use any flavor of unicode in text file so it will error out all the time when trying to redirect stdout with non-ANSI (in your case, assuming English language Windows, non CP-1252) content to a text file.

Try simply this:
text.py:
```
print('日本語')
```

Then (with cmd, git-bash, or whatever you like)

```cmd
python.exe text.py > out.txt
```

**Comment by victoryy2003** [comment]
I had found out the solution, thanks for your helping 🙂👍

In terminal:
`set PYTHONIOENCODING=utf8`
`python -m instaloader ... ...`
