### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by mindjek07** [instaloader/instaloader#1634]
**Describe the bug**
OSError: [Errno 36] File name too long

**To Reproduce**
`instaloader --login=user --no-metadata-json --no-captions --filename-pattern={caption} karelyruiz`

**Error messages and tracebacks**
```
[ 32/108] karelyruiz/Enamorada de ti 😍😍_1.jpg karelyruiz/Enamorada de ti 😍😍_2.jpg karelyruiz/Enamorada de ti 😍😍_3.jpg
[ 33/108] karelyruiz/Me siento diosa 😍😍😍😍_1.jpg karelyruiz/Me siento diosa 😍😍😍😍_2.jpg karelyruiz/Me siento diosa 😍😍😍😍_3.jpg karelyruiz/Me siento diosa 😍😍😍😍_4.jpg
[ 34/108] karelyruiz/Esta soy yo antes de operarme , bonita a mi manera y si decidí operarme fue por gusto y por qué tuve la manera de hacerlo ❤️ todas son HERMOSAS dejen de acomplejarse y si tienen el dinero para operarse HÁGANLO , si quieren entrenar y tener cuerpo fit háganlo, no estamos para darle el gusto a nadie , más que a nosotros mismos ❤️ todas tenemos imperfecciones y eso nos hace vernos PERFECTAS ❤️❤️.jpg Traceback (most recent call last):
  File "/home/mindjek/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/__main__.py", line 486, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/__main__.py", line 223, in _main
    fast_update, post_filter, storyitem_filter, latest_stamps=latest_stamps)
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/instaloader.py", line 1470, in download_profiles    takewhile=posts_takewhile)
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/instaloader.py", line 1043, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/instaloader.py", line 739, in download_post
    self.download_pic(filename=filename, url=post.url, mtime=post.date_local))
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/instaloader.py", line 356, in download_pic
    self.context.write_raw(resp, filename)
  File "/home/mindjek/.local/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 495, in write_raw
    with open(filename + '.temp', 'wb') as file:
OSError: [Errno 36] File name too long: 'karelyruiz/Esta soy yo antes de operarme , bonita a mi manera y si decidí operarme fue por gusto y por qué tuve la manera de hacerlo ❤️ todas son HERMOSAS dejen de acomplejarse y si tienen el dinero para operarse HÁGANLO , si quieren entrenar y tener cuerpo fit háganlo, no estamos para darle el gusto a nadie , más que a nosotros mismos ❤️ todas tenemos imperfecciones y eso nos hace vernos PERFECTAS ❤️❤️.jpg.temp'
```

**Instaloader version**
`instaloader --version` 4.9.2.

**Additional context**
how to skip big caption posts ?

**Comment by watain666** [comment]
Could we give a limit number to trim the caption long? I think that will be pretty useful
