### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by ernikus** [instaloader/instaloader#1653]
Hi,
I was using script same as always I do to download files from Saved and that bug happened:

```
Retrieving saved posts...
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/usr/lib/python3/dist-packages/instaloader/__main__.py", line 178, in _main
    instaloader.download_saved_posts(fast_update=fast_update, max_count=max_count,
  File "/usr/lib/python3/dist-packages/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/instaloader/instaloader.py", line 1112, in download_saved_posts
    self.posts_download_loop(node_iterator, ":saved",
  File "/usr/lib/python3/dist-packages/instaloader/instaloader.py", line 1001, in posts_download_loop
    with resumable_iteration(
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/instaloader/nodeiterator.py", line 283, in resumable_iteration
    fni = load(context, resume_file_path)
  File "/usr/lib/python3/dist-packages/instaloader/structures.py", line 1877, in load_structure_from_file
    json_structure = json.load(fp)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/usr/lib/python3.10/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Instaloader Version**
latest (`4.9.2`)

I tried to update script, software reloading session cookies, login to account using terminal - but nothing of that helped.
In that case even count limit (`-c`) didn't help.

Also is important that I used that script after a long break - meanwhile adding more files to Saved.

**I think that it looks like I break some kind of limit of total files there and even with set up count limit - it still shows the same error. Like it needs some kind of divide of total data**

**Comment by Showmaster3000** [comment]
You missed important things like your commandline/script snippet.
Anyway it looks like this error doesn't come from instaloader.

**Comment by ernikus** [comment]
Sorry for not including such important thing. Here it comes:

```
sudo instaloader -l <USERNAME> :saved
Session file does not exist yet - Logging in.
Enter Instagram password for <USERNAME>: 
Logged in as <USERNAME>.
Retrieving saved posts...
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9.2', 'console_scripts', 'instaloader')())
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/__main__.py", line 178, in _main
    instaloader.download_saved_posts(fast_update=fast_update, max_count=max_count,
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/instaloader.py", line 1111, in download_saved_posts
    self.posts_download_loop(node_iterator, ":saved",
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/instaloader.py", line 1000, in posts_download_loop
    with resumable_iteration(
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/nodeiterator.py", line 283, in resumable_iteration
    fni = load(context, resume_file_path)
  File "/usr/local/lib/python3.10/dist-packages/instaloader-4.9.2-py3.10.egg/instaloader/structures.py", line 1877, in load_structure_from_file
    json_structure = json.load(fp)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/usr/lib/python3.10/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```


Error related to reading the file.

**Comment by aandergr** [comment]
Bug report lacks how to reproduce the error.
