### ISSUE TITLE
Error when trying to log in to instaloader

### ISSUE THREAD

**Issue by bezumka** [instaloader/instaloader#1759]
About a week ago, instaloador was working fine for me, since today I get this error when run python script:
```
Traceback (most recent call last):
  File "/Users/otarasov/PycharmProjects/insta/test.py", line 7, in <module>
    L.login(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instaloader/instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 265, in login
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by RakSrinaNa** [comment]
Duplicates #1758
