### ISSUE TITLE
File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 413, in _find_no_duplicates     raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")

### ISSUE THREAD

**Issue by Drjacky** [instaloader/instaloader#1773]
```bash
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/usr/local/lib/python3.10/site-packages/instaloader/__main__.py", line 121, in _main
    instaloader.interactive_login(username)
  File "/usr/local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1572, in interactive_login
    self.login(username, password)
  File "/usr/local/lib/python3.10/site-packages/instaloader/instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "/usr/local/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 265, in login
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"
```

Version: 4.9.5

There was 2FA enabled but when I inserted the code, it said: `2FA error: This code is no longer valid. Please request a new one.`. but it was valid and new. So, I disabled the 2FA and I got the above error.

**Comment by Drjacky** [comment]
I tried with an account without 2FA, and got this:
```bash
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXFOb52balbalblablaban8tQZ/ - follow the instructions, then retry.
```

And when I click on it, it just asks if it was you or not and change your password. That's it.

**Comment by Drjacky** [comment]
I used this fork https://github.com/instaloader/instaloader/issues/1758#issuecomment-1272618465 and it work but after a couple of downloads, it displayed 403. and when I logged in again, I get 400 and now the account is disabled!

**Comment by HubbaBubba666** [comment]
I use instaloader.exe and since today I always get such an error message:

Traceback (most recent call last):
  File "__main__.py", line 505, in <module>
  File "__main__.py", line 502, in __main
  File "__main__.py", line 471, in main
  File "__main__.py", line 110, in _main
  File "instaloader\instaloader.py", line 634, in login
  File "instaloader\instaloadercontext.py", line 265, in login
  File "requests\cookies.py", line 328, in __getitem__
  File "requests\cookies.py", line 399, in _find_no_duplicates
KeyError: "name='csrftoken', domain=None, path=None"
[14000] Failed to execute script '__main__' due to unhandled exception!

**Comment by Drjacky** [comment]
@HubbaBubba666 The best one is [4K Stogram](https://www.4kdownload.com/downloads/20#stogram). tested and works perfectly.

**Comment by Drjacky** [comment]
The issue had not been creating because of the forked one. As you said in your first [comment](https://github.com/instaloader/instaloader/issues/1773#issuecomment-1282477550) it's for this repo. So, feel free to close it as a Duplicate of https://github.com/instaloader/instaloader/issues/1758

Introducing another software/option was because of helping another person.

Thanks for the repo BTW.
