### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by curya** [instaloader/instaloader#1802]
**Describe the bug**
Got this error when trying to download a post.

**To Reproduce**
Try to download post CXANBS5IXVt
Must be logged in.

**Expected behavior**
Post should download.

**Error messages and tracebacks**
JSON Query to api/v1/media/2720231438541747565/info/: HTTP error code 403. [retrying; skip with ^C]
JSON Query to api/v1/media/2720231438541747565/info/: HTTP error code 403. [retrying; skip with ^C]
Unable to fetch high-quality video version of <Post CXANBS5IXVt>: JSON Query to api/v1/media/2720231438541747565/info/: HTTP error code 403.
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\instaloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9.5', 'console_scripts', 'instaloader')())
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\__main__.py", line 471, in main
    _main(loader,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\__main__.py", line 220, in _main
    instaloader.download_profiles(profiles,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 1472, in download_profiles
    self.posts_download_loop(posts_to_download, profile_name, fast_update, post_filter,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 1047, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 756, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Instaloader version**
4.9.5

**Additional context**

**Comment by aandergr** [comment]
Thanks for reporting. Indeed, this post does not work. It presents itself as video post, despite the video URL being None.
