### ISSUE TITLE
Unable to fetch videos of a given account - JSON Query to graphql/query: HTTP error code 401

### ISSUE THREAD

**Issue by mayankchauhan971** [instaloader/instaloader#1805]
Hi everyone, 

I am writing a piece of code to download just the videos less than 60 seconds from a IG account without logging in but getting the following error. I am not sure why video_duration is giving an error, without this the code seems to be working fine.

Version - 4.9.5

Script

    profiles = [ARRAY OF IG USERNAMES]

    session = instaloader.Instaloader(download_pictures=False,
                                download_video_thumbnails=False, 
                                save_metadata=False, 
                                title_pattern= '{target}_{date_utc}_UTC',
                                max_connection_attempts=2)
    Profile = instaloader.Profile
    for profile in profiles:
        print("Fetching posts from " + profile)

        il_profile_instance = Profile.from_username(session.context, profile)
        posts = il_profile_instance.get_posts()
        
        for post in posts:
            if(post.is_video):
                video_length = post.video_duration
                print(video_length)
                
                if(video_length != None and video_length < 60.0):
                    session.download_post(post, target=profile)

Error

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 351, in get_json
      raise ConnectionException("HTTP error code {}.".format(resp.status_code))
  instaloader.exceptions.ConnectionException: HTTP error code 401.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/Users/mayankchauhan/Desktop/odium/downloads/downloadscript.py", line 83, in <module>
      main()
    File "/Users/mayankchauhan/Desktop/odium/downloads/downloadscript.py", line 74, in main
      fetchPostsData(session, profiles)
    File "/Users/mayankchauhan/Desktop/odium/downloads/downloadscript.py", line 16, in fetchPostsData
      video_length = post.video_duration
                     ^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/structures.py", line 485, in video_duration
      return self._field('video_duration')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/structures.py", line 228, in _field
      d = self._full_metadata
          ^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/structures.py", line 205, in _full_metadata
      self._obtain_metadata()
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/structures.py", line 192, in _obtain_metadata
      pic_json = self._context.graphql_query(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 428, in graphql_query
      resp_json = self.get_json('graphql/query',
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
      return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 384, in get_json
      raise ConnectionException(error_string) from err
  instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.

**Comment by ImitatorBoy** [comment]
Use --login and if you are using it just delete your profile and login again

**Comment by thariq-nugrohotomo** [comment]
> just delete your profile and login again

Thanks. That solves my issue. All of my account accounts for downloading stories got 401 since yesterday. After deleting the saved session files, instaloader will ask for password again, but this time it will download stories successfully.

Does this mean that our saved session getting stale and need to be refreshed after several interval period? Probably instaloader should be able to attempt to do this automatically?
