### ISSUE TITLE
Latest stamp not working

### ISSUE THREAD

**Issue by DeathWithKebab** [instaloader/instaloader#1815]
**Describe the bug**
When entering --latest-stamps argument the script gives back an directory error

**To Reproduce**
Insert the --latest-stamps argument into the command

**Expected behavior**
Download each profiles latest media

**Error messages and tracebacks**
`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instaloader", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9.5', 'console_scripts', 'instaloader')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/__main__.py", line 471, in main
    _main(loader,
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/__main__.py", line 182, in _main
    profile = instaloader.check_profile_id(target, latest_stamps)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 1368, in check_profile_id
    latest_stamps.save_profile_id(profile.username, profile.userid)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/lateststamps.py", line 46, in save_profile_id
    self._save()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/lateststamps.py", line 28, in _save
    with open(self.file, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'profile name'`

**Instaloader version**
4.9.5

**Additional context**
I'm working on Termux 0.118.0 on an android device. Other functions of instaloader are all fully functional without any problems.

**Comment by ekalin** [comment]
The exact command line would help; and also the traceback has lost the line breaks and is somewhat hard to read.

However, one can see the error:
`IsADirectoryError: [Errno 21] Is a directory`
so it seems you're passing a directory (and not a file) to `--latest-stamps`.
