### ISSUE TITLE
Invalid windows directory starting with "aux."

### ISSUE THREAD

**Issue by MatthieuBonenfant** [instaloader/instaloader#185]
Hi,

it appears that you cannot create a folder in Windows starting with "aux." The script crashed after saving a few hundred images from a random hashtag until I hit this specific error. I was able to reproduce directly by trying to grab the images from the account.

Microsoft MS-DOS had reserved these names for these system device drivers. Also, for this specific example, all folders starting with these names + "." + anything are also not supported (CON.test or PRN.test or COM1.test, or LPT1.test, etc.) .

https://www.thewindowsclub.com/create-restricted-files-folders-con-aux-nul-click-windows

CON : Keyboard and display
PRN : System list device, usually a parallel port
AUX : Auxiliary device, usually a serial port
CLOCK$ : System real-time clock
NUL: Bit-bucket device
A:-Z: : Drive letters
COM1 : First serial communications port
LPT1 : First parallel printer port
LPT2 : Second parallel printer port
LPT3 : Third parallel printer port
COM2 : Second serial communications port
COM3 : Third serial communications port
COM4 : Fourth serial communications port

I would suggest that instead of crashing, the script should just skip the image(s) and report the directory creation error when it ends instead of killing the queue. 

Alternatively, the script could potentially generate an alternate name, but since this probably just a windows specific issue it would not be cool to non-windows users. Skipping the file would probably the best for everybody at this point.

With the skip rule in place, and if someone would really want to save images for a non-supported account, maybe there is a function already to force a different folder name to be created that is different from the user account name would someone want to target specifically an account with a non-supported folder name. But the chances that it happens again are very slim.

Thank you.

c:\python\scripts\instaloader aux.redkop --fast-update --filename-pattern={profile}_{date_utc}_UTC --no-captions --no-metadata-json
Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.1.1', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader\__main__.py", line 388, in main
    storyitem_filter_str=args.storyitem_filter)
  File "c:\python\lib\site-packages\instaloader\__main__.py", line 143, in _main
    profile = instaloader.check_profile_id(target)
  File "c:\python\lib\site-packages\instaloader\instaloader.py", line 776, in check_profile_id
    self.save_profile_id(profile)
  File "c:\python\lib\site-packages\instaloader\instaloader.py", line 730, in save_profile_id
    target=profile.username), exist_ok=True)
  File "c:\python\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'aux.redkop'

Thanks!

**Comment by jimbo108** [comment]
I would like to give this a shot, can you confirm that skipping the affected file is an appropriate solution @aandergr ?  I could also generate an alternative file name on Windows only, I just wouldn't know what the naming scheme would be.

**Comment by aandergr** [comment]
Just stumbled upon the [\\\\?\ bypass method](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file), which I consider a more appropriate solution for this issue, as well as other windows filesystem related issues such as #84. I don't like the idea of just skipping affected files, if there is a way to avoid having to do that.

**Comment by aandergr** [comment]
@jimbo108 Are you still interested in giving this a shot? I would appreciate it a lot. In instaloader/instaloader.py we already have the _PostPathFormatter class to workaround the windows filesystem path naming problems we encountered so far. I think that would be a good starting point for implementing to use the `\\?\` bypass.

https://github.com/instaloader/instaloader/blob/ece0d11915e955721203f1751201d180f73f1e80/instaloader/instaloader.py#L69-L76

**Comment by aandergr** [comment]
It seems that the abovely-mentioned [\\\\?\ bypass method](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file) works fine. However, it requires that the Windows-native `\` (backslash) is consistently used as a path seperator, which we fixed in #693. After checking out that pull request, you can manually instruct Instaloader to use the \\\\?\ bypass method with:

```
instaloader --dirname-pattern=\\?\D:\{target} ...
```

(to save files in `D:\{target}`. The path after `\\?\` must be absolute.)

This alleviates or worksaround the problem for now. However, I think it might be worth considering using the \\\\?\ bypass method per default and transparently.
