### ISSUE TITLE
Stuck in Password Reset Loop

### ISSUE THREAD

**Issue by robjbrain** [instaloader/instaloader#1873]
I'm trying to use `instaloader -l USERNAME` to save a session that I can then use with my own python script. But every single time I get checkpoint required and it requires me to make a new password.

I'm connecting from the same machine and same wifi and click "It was me" every time but it still warns that someone might have access to my password and forces the password change.

I'm tentative to try anymore times incase I get blocked completely.

Is there a step i'm missing?

All i've done so far is `instaloader -l USERNAME` and it worked the first time and then never again since.

Running this python script from the guide: https://instaloader.github.io/codesnippets.html#likes-of-a-profile-ghost-followers fails with the following error which is why I was trying to do the session again:

```
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    L.load_session_from_file(USER)
  File "/Users/rob/Library/Python/3.8/lib/python/site-packages/instaloader/instaloader.py", line 618, in load_session_from_file
    with open(filename, 'rb') as sessionfile:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/kg/ggvcmr3j6f743btcvrjl_0yr0000gn/t/.instaloader-myname/session-myname'
```

**Comment by UnderControl23** [comment]
I am facing the same problem right now

**Comment by SirFahr** [comment]
Same here.. They force you to change it everytime

**Comment by Jon8RFC** [comment]
I'm having a similar issue, and no session is saved:

> Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/[redacted] - follow the instructions, then retry.

I then attempt to access that page, which is unusable and redirects me to instagram.com.
I attempt to login via web and succeed but receive this, which then requires a password reset:
![instaloader](https://user-images.githubusercontent.com/12204953/215592653-a4ea062d-fac1-493f-b796-6f5d7070e8d4.png)

**Comment by BeefBaby** [comment]
Tried the same python script on the troubleshooting page. Mine also isn't being saved nothing in "\AppData\Local\Instaloader\".

**Comment by BeefBaby** [comment]
> > Tried the same python script on the troubleshooting page. Mine also isn't being saved nothing in "\AppData\Local\Instaloader".
> 
> Did you try to run the script in cmd-window and admin rights? worked for me

Yeah just retried. It says it's being saved in that directory, but nothing is there. Ran with admin rights.

**Comment by SirFahr** [comment]
> > > Tried the same python script on the troubleshooting page. Mine also isn't being saved nothing in "\AppData\Local\Instaloader".
> > 
> > 
> > Did you try to run the script in cmd-window and admin rights? worked for me
> 
> Yeah just retried. It says it's being saved in that directory, but nothing is there. Ran with admin rights.

you surley use firefox? the script only works with firefox

**Comment by BeefBaby** [comment]
> > > > Tried the same python script on the troubleshooting page. Mine also isn't being saved nothing in "\AppData\Local\Instaloader".
> > > 
> > > 
> > > Did you try to run the script in cmd-window and admin rights? worked for me
> > 
> > 
> > Yeah just retried. It says it's being saved in that directory, but nothing is there. Ran with admin rights.
> 
> you surley use firefox? the script only works with firefox

Yeah I used firefox. I think my python installation might be a mess. It was saving the session files in "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\Instaloader" I then created the directory "C:\Users\USER\AppData\Local\Instaloader" and moved the session file there. It worked. 👍

**Comment by ipaqmaster** [comment]
Same issue here. Cannot continue, telling Instagram that it's me trying to login instantly sends me to a password change screen regardless. Using Firefox to generate an entirely random and cryptographically safe password only lands me on the same page my next attempt...

**Comment by ipaqmaster** [comment]
Tried activating 2FA to work around this problem and get 
![image](https://user-images.githubusercontent.com/26422790/218640000-0439f26b-16df-45b6-9f69-4e5014850e43.png)


Wow they've really botched their "suspicious login" handling system..

**Comment by SpartacusIam** [comment]
I'm having this same issue.  This script is essentially useless at this point.

**Comment by ipaqmaster** [comment]
Yeah I don't think it should be ignored or auto-closed by a bot. The script can't be used in this state.
