### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by LunianDE** [instaloader/instaloader#1905]
**Describe the bug**
After downloading between 350 and 370 profiles (out of 450 total) instaloader keeps crashing with the attached Error Message

**To Reproduce**
.\instaloader.exe --login=username --latest-stamps --no-video-thumbnails --no-captions --no-metadata-json --igtv --dirname-pattern="C:\path\to\file\{profile}" --filename-pattern="{profile} - {shortcode}" --no-iphone --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 270.0.0.13.83 (iPhone15,2; iOS 16_3_1; de_DE; de-DE; scale=3.00; 1179x2556; 445843881)" @profilename

**Expected behavior**
I expect it to not abort the download and continue downloading the remaining profiles.

**Error messages and tracebacks**
Traceback (most recent call last):
  File "__main__.py", line 504, in <module>
  File "__main__.py", line 501, in __main
  File "__main__.py", line 470, in main
  File "__main__.py", line 219, in _main
  File "instaloader\instaloader.py", line 1472, in download_profiles
  File "instaloader\instaloader.py", line 1005, in posts_download_loop
  File "contextlib.py", line 119, in __enter__
  File "instaloader\nodeiterator.py", line 283, in resumable_iteration
  File "instaloader\structures.py", line 1910, in load_structure_from_file
  File "json\__init__.py", line 293, in load
  File "lzma.py", line 200, in read
  File "_compression.py", line 99, in read
EOFError: Compressed file ended before the end-of-stream marker was reached
[23068] Failed to execute script '__main__' due to unhandled exception!

**Instaloader version**
4.9.6

**Additional context**
-

**Comment by LunianDE** [comment]
Any help?

**Comment by LunianDE** [comment]
Still occuring

**Comment by aandergr** [comment]
Thanks for reporting. Instaloader did not handle empty resume files well. This will be fixed with the next release by simply ignoring empty resume files and issuing a warning on the terminal.

Until then, you can just delete the faulty resume file.

**Comment by LunianDE** [comment]
> Thanks for reporting. Instaloader did not handle empty resume files well. This will be fixed with the next release by simply ignoring empty resume files and issuing a warning on the terminal.
> 
> Until then, you can just delete the faulty resume file.

Thanks for your message. Until i wait for the fix, could you maybe tell me where the resume file is stored?
