### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by rohanmohapatra** [instaloader/instaloader#192]
While trying to download images through this
`instaloader --filename-pattern={date_utc}_UTC_{profile} --post-filter="'4 letters' in caption" --no-metadata-json --no-compress-json <profile-name>`

I got this error

**[170/1382] Traceback (most recent call last):
  File "d:\python 35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python 35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python 35\Scripts\instaloader.exe\__main__.py", line 9, in <module>
  File "d:\python 35\lib\site-packages\instaloader\__main__.py", line 388, in main
    storyitem_filter_str=args.storyitem_filter)
  File "d:\python 35\lib\site-packages\instaloader\__main__.py", line 171, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "d:\python 35\lib\site-packages\instaloader\instaloader.py", line 850, in download_profiles
    if post_filter is not None and not post_filter(post):
  File "d:\python 35\lib\site-packages\instaloader\__main__.py", line 54, in filterfunc
    return bool(eval(compiled_filter, {'item': item, 'datetime': datetime.datetime}))
  File "<command line filter parameter>", line 1, in <module>
TypeError: argument of type 'NoneType' is not iterable**

Running Instaloader 4.1.1

This kind of error is not handled? or is it an issue from my end?

**Comment by rohanmohapatra** [comment]
> `--post-filter="'4 letters' in caption"` fails with a TypeError exception if caption is None. Better use `--post-filter="caption and '4 letters' in caption"`.

Thank You

**Comment by aandergr** [comment]
You're welcome :)

Anyway I want to keep this issue open since I like your suggestion of catching exceptions that are raised during evaluation of the `--post-filter`, instead of failing and terminating the whole program.
