### ISSUE TITLE
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login. on AWS

### ISSUE THREAD

**Issue by tungrix** [instaloader/instaloader#1925]
```python
L = instaloader.Instaloader(download_pictures=False, save_metadata=False, download_videos=False)
SINCE = datetime(2023, 4, 1)
UNTIL = datetime(2019, 12, 1)
for name in ig_list[:100]:
    posts = instaloader.Profile.from_username(L.context, name).get_posts()
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        L.download_post(post, name)
    sl = round(random.uniform(5, 10), 3)
    time.sleep(sl)
```
I am trying to run the above code in AWS EC2, however:
```cmd
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
app_1  |   File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
app_1  |     __import__(pkg_name)
app_1  |   File "/code/main.py", line 16, in <module>
app_1  |     posts = instaloader.Profile.from_username(L.context, name).get_posts()
app_1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 704, in from_username
app_1  |     profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
app_1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 773, in _obtain_metadata
app_1  |     metadata = self._context.get_iphone_json(f'api/v1/users/web_profile_info/?username={self.username}',
app_1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 489, in get_iphone_json
app_1  |     return self.get_json(path, params, 'i.instagram.com', tempsession)
app_1  |   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 337, in get_json
app_1  |     raise LoginRequiredException("Redirected to login page. Use --login.")
app_1  | instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.
app_1  |
app_1  | HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=stephenchow to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
```
Can I follow any workaround to avoid login/how to login in the server(it doesn't have firefox browser for me to apply [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py)))? I can't do it locally cause keeps getting JSON Query to graphql/query: HTTP error code 401., I also have no idea how to solve it.
#1617 didn't help.

**Comment by babuus** [comment]
I got the same. did you manage to solve the error?

**Comment by aladynjr** [comment]
same here
