### ISSUE TITLE
New python updates produce errors

### ISSUE THREAD

**Issue by EmJotGeh** [instaloader/instaloader#1962]
After the New Python Updates on Arch:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/instaloader", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.9.6', 'console_scripts', 'instaloader')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/instaloader", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for instaloader
```

**Comment by JunedKhan101** [comment]
I just tried using it with Python 3.11.3 and it is working fine for me.

Could you please provide more context what are you trying to do? or what are you doing such that you are getting this sort of error.

Can't get any clue just by looking at the logs.

**Comment by Steccah** [comment]
I have python 3.11.3 and even calling instaloader without args produces the same error

**Comment by Steccah** [comment]
Reinstalling instaloader fixed the issue

**Comment by JunedKhan101** [comment]
Okay, If it's fixed then we can close this issue.

**Comment by EmJotGeh** [comment]
I can confirm that a reinstalling solve the problem. Thank You!
