### ISSUE TITLE
KeyError: 'entry_data'

### ISSUE THREAD

**Issue by ElCiocio** [instaloader/instaloader#1964]
Traceback (most recent call last):
  File "C:\Users\****\Desktop\chad money\main.py", line 5, in <module>
    user = InstagramUser('xxxx', sessionid=session_id)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\instagramy\InstagramUser.py", line 63, in __init__
    username, data["entry_data"]["ProfilePage"][0]["graphql"]["user"]
KeyError: 'entry_data'

With a code as simple as

from instagramy import InstagramUser

session_id = ""
user = InstagramUser('xxxx', sessionid=session_id)

Session_id was good. Username was existent and public.

Thanks.

**Comment by Showmaster3000** [comment]
Looks like your are in the wrong project. We are instaloader, not instagramy.
