### ISSUE TITLE
Downloading a highlight with a non ascii character

### ISSUE THREAD

**Issue by OrangutanGaming** [instaloader/instaloader#197]
**Describe the bug**
When downloading highlights with an emote in it's name, I get `UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f576' in position 23: ordinal not in range(128)`

**To Reproduce**
(e.g. Instaloader command line)
Try to download a profile's highlights with an emote in it's name e.g. haileesteinfeld

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).
It works or maybe changes the name

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
```py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.1.1', 'console_scripts', 'instaloader')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/__main__.py", line 388, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/__main__.py", line 171, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 840, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 42, in call
    return func(instaloader, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 540, in download_highlights
    self.context.log("Retrieving highlights \"{}\" from profile {}".format(user_highlight.title, name))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 96, in log
    print(*msg, sep=sep, end=end, flush=flush)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f576' in position 23: ordinal not in range(128)
```

**Instaloader version**
`instaloader --version` output.
4.1.1

**Comment by aandergr** [comment]
I successfully downloaded that profile's highlights, despite the emojis in the name of one of them.

The line that raises the UnicodeEncodeError according your traceback is not executed if you pass `--quiet` to Instaloader, so this might workaround the problem for now.

**Comment by OrangutanGaming** [comment]
It's possibly a MacOS issue, haven't tested on Windows

**Comment by PhantomTech** [comment]
I get the same UnicodeEncodeError when downloading entire profiles. The error happens when Instaloader tries to create a directory with a Unicode character as the directory name. Using something like `.encode('ascii','backslashreplace')` on the titles of highlights can fix the issue. I modified the title property of the highlight structure as a quick fix but that might cause other issues and there is likely a better place to make the modification.

**Comment by PhantomTech** [comment]
I'm on Ubuntu 18.04

**Comment by OrangutanGaming** [comment]
A possible fix is to catch the error and then replace any invalid characters with something like `_` and have an argument that disables this.

**Comment by aandergr** [comment]
I cannot reproduce this. Please reopen this issue if you have new information.

**Comment by hgkmaxymus** [comment]
I had to download the highlights for a friend and I found this bug too. I am using git bash, Windows 10 Pro (Brazilian Portuguese).

Here's another random public profile with emotes in the name of some highlights: federicodiazz

```
Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\Scripts\instaloader-script.py", line 10, in <module>
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 961, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 47, in call
    return func(instaloader, *args, **kwargs)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 608, in download_highlights
    self.context.log("Retrieving highlights \"{}\" from profile {}".format(user_highlight.title, name))
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloadercontext.py", line 96, in log
    print(*msg, sep=sep, end=end, flush=flush)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f30a' in position 29: character maps to <undefined>
```
**Instaloader version:**
4.2.3, installed using `pip3 install instaloader`.

**Comment by aandergr** [comment]
@hgkmaxymus looks like this could also avoided with `--quiet`. Does this error also occur with a recent version of Python? I believe they made some unicode-related improvements with Python 3.6.

**Comment by hgkmaxymus** [comment]
Hello,

Funny, I just started the `--quiet` test about 5 minutes before your comment here. At the start it looked like it downloaded only the first "problematic" highlight and hang (since it didn't download the other ones after that) but when the command finally finished I went back to the folder and all the highlights were there.

About the python version, I tried with version 3.7.2 (I installed it, reinstalled instaloader and for some reason I had to change the `instaloader-script.py` inside the old python version to use the python37), got another error:
```
Traceback (most recent call last):
  File "C:\Instaloader\__main__.py", line 442, in <module>
  File "C:\Instaloader\__main__.py", line 438, in __main
  File "C:\Instaloader\__main__.py", line 413, in main
  File "C:\Instaloader\__main__.py", line 187, in _main
  File "C:\Instaloader\instaloader\instaloader.py", line 920, in download_profiles
  File "C:\Instaloader\instaloader\instaloader.py", line 43, in call
  File "C:\Instaloader\instaloader\instaloader.py", line 567, in download_highlights
  File "C:\Instaloader\instaloader\instaloadercontext.py", line 97, in log
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f30a' in position 29: character maps to <undefined>
```

I tried with Python 3.6, same thing.

I think (ok, I am sure) I don't know how to make instaloader use the other python versions, since there are no instaloader folders inside the `pythonxx/lib/site-packages` folders. Can you help me on how to proceed?

**Comment by e5150** [comment]
An ugly workaround could be something like:
```msg = sep.join(*msg).encode(sys.stdout.encoding or 'ascii', errors='replace').decode()```
I've beaten my head against a wall trying to do the right thing wrt unicode and python, and eventually just given up...

**Comment by Fukken-Saved** [comment]
Same problem as hgkmaxymus - --quiet solves the problem.
I speculate the source of the problem is that the Windows command prompt cannot handle Unicode characters, or some intermediate function that prepares logs for the command prompt - charmap?

**Comment by Fukken-Saved** [comment]
Setting the command prompt code page with chcp 65001 does not help
Looks like the solution would be to call something in Python that supports Unicode instead, but in the meantime --quiet should be added to the Troubleshooting page

**Comment by mdPlusPlus** [comment]
Have you tried running it in PowerShell instead?

**Comment by LoliWizard** [comment]
I am also having this issue trying to download highlights with names of emojis and --quiet does not fix this issue for me. installed using pip version 4.2.10

**Comment by LouisVA** [comment]
I currently can't download any profile that uses some special symbol?

>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 1140, in download_profiles
>     self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 992, in download_tagged
>     fast_update, post_filter)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 791, in posts_download_loop
>     downloaded = self.download_post(post, target=target)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 521, in download_post
>     mtime=post.date_local, filename_suffix=str(edge_number))
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 79, in call
>     return func(instaloader, *args, **kwargs)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 257, in download_pic
>     self.context.get_and_write_raw(url, filename)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 520, in get_and_write_raw
>     self.write_raw(self.get_raw(url), filename)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 484, in write_raw
>     self.log(filename, end=' ', flush=True)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 102, in log
>     print(*msg, sep=sep, end=end, flush=flush)
>   File "C:\Users\chick\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\uff1a' in position 15: character maps to <undefined>

**Comment by dontbanmeplz** [comment]
Same, quiet does absolutely nothing
