### ISSUE TITLE
Fails to download stories maybe due to some char symbols or something

### ISSUE THREAD

**Issue by sapphirepro** [instaloader/instaloader#1976]
**Describe the bug**
Fails to download stories maybe due to some char symbols or something

**To Reproduce**
Attempt to download profile fully with stories, highlights etc fully. On highlights stage it will fail and crash (not immediately)
(e.g. Instaloader command line)
/Additional/instaloader-4.9.6/instaloader.py --login some_user --stories --highlights --igtv tanka__abro

login username replaced with "some_user" for security purposes and privacy, actual login must be used
**Expected behavior**
Download all stories, highlights and posts

**Error messages and tracebacks**
Traceback (most recent call last):
  File "/Additional/instaloader-4.9.6/instaloader.py", line 6, in <module>
    main()
  File "/Additional/instaloader-4.9.6/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/Additional/instaloader-4.9.6/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/Additional/instaloader-4.9.6/instaloader/instaloader.py", line 1461, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/Additional/instaloader-4.9.6/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "/Additional/instaloader-4.9.6/instaloader/instaloader.py", line 957, in download_highlights
    for item in user_highlight.get_items():
  File "/Additional/instaloader-4.9.6/instaloader/structures.py", line 1491, in get_items
    self._fetch_iphone_struct()
  File "/Additional/instaloader-4.9.6/instaloader/structures.py", line 1479, in _fetch_iphone_struct
    self._iphone_struct_ = data['reels']['highlight:{}'.format(self.unique_id)]
KeyError: 'highlight:18066546337318578'

**Instaloader version**
4.9.6

**Additional context**
About 1/3 of highlights downloaded, then crashed with error above, maybe due to some special chars or something. I don't fully understand the error

**Comment by sapphirepro** [comment]
Similar example with another instagram profile to download:

`Retrieving highlights "Modeling📸" from profile ___nastyal___
___nastyal___/Modeling📸/2022-01-17_13-45-17_UTC_cover.jpg already exists
Traceback (most recent call last):
  File "/Additional/instaloader-4.9.6/instaloader.py", line 6, in <module>
    main()
  File "/Additional/instaloader-4.9.6/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/Additional/instaloader-4.9.6/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/Additional/instaloader-4.9.6/instaloader/instaloader.py", line 1461, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/Additional/instaloader-4.9.6/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "/Additional/instaloader-4.9.6/instaloader/instaloader.py", line 957, in download_highlights
    for item in user_highlight.get_items():
  File "/Additional/instaloader-4.9.6/instaloader/structures.py", line 1491, in get_items
    self._fetch_iphone_struct()
  File "/Additional/instaloader-4.9.6/instaloader/structures.py", line 1479, in _fetch_iphone_struct
    self._iphone_struct_ = data['reels']['highlight:{}'.format(self.unique_id)]
KeyError: 'highlight:18193785088221178'
`

**Comment by aandergr** [comment]
Thanks for reporting. Downloading the highlights of the two profiles works for me. However, the code is not robust against e.g. deleting a certain highlight after the download loop has started. This might be the cause of the here-described problem.
