### ISSUE TITLE
use --login

### ISSUE THREAD

**Issue by ihabpalamino** [instaloader/instaloader#1992]
i am getting this error while trying to scrape a public account

Traceback (most recent call last):
  File "C:\Users\HP Probook\PycharmProjects\firstproject\Instaloader.py", line 24, in <module>

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=al_aoula to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
    posts = instaloader.Profile.from_username(L.context, f"{username}").get_posts()
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\structures.py", line 704, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\structures.py", line 773, in _obtain_metadata
    metadata = self._context.get_iphone_json(f'api/v1/users/web_profile_info/?username={self.username}',
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 489, in get_iphone_json
    return self.get_json(path, params, 'i.instagram.com', tempsession)
  File "C:\Users\HP Probook\PycharmProjects\firstproject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 337, in get_json
    raise LoginRequiredException("Redirected to login page. Use --login.")
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.
here is my code 

def get_cookiefile():
    default_cookiefile = {
        "Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite",
        "Darwin": "~/Library/Application Support/Firefox/Profiles/*/cookies.sqlite",
    }.get(system(), "~/.mozilla/firefox/*/cookies.sqlite")
    cookiefiles = glob(expanduser(default_cookiefile))
    if not cookiefiles:
        raise SystemExit("No Firefox cookies.sqlite file found. Use -c COOKIEFILE.")
    return cookiefiles[0]

def import_session(cookiefile, sessionfile):
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
    try:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
        )
    except OperationalError:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'"
        )
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    print("Imported session cookie for {}.".format(username))
    instaloader.context.username = username
    instaloader.save_session_to_file(sessionfile)

if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument("-c", "--cookiefile")
    p.add_argument("-f", "--sessionfile")
    args = p.parse_args()
    try:
        import_session(args.cookiefile or get_cookiefile(), args.sessionfile)
    except (ConnectionException, OperationalError) as e:
        raise SystemExit("Cookie import failed: {}".format(e))

L = instaloader.Instaloader()

username="al_aoula"

posts = instaloader.Profile.from_username(L.context, f"{username}").get_posts()
Since="2023/05/39"
until="2023/05/38"
SINCE = datetime.strptime(Since,"%Y/%m/%d")
UNTIL = datetime.strptime(until,"%Y/%m/%d")

PLATFORM_NAME ="instagram"
a=[]
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    pu=[]

    if post.is_video:
        viewVideo = post.video_view_count
    else:
        viewVideo = None  # or set a default value if needed

    data = {
        "id_post": post.mediaid,
        "Date": post.date.strftime("%Y-%m-%d"),
        "Heure": post.date.strftime("%H:%M:%S"),
        "content": post.caption,
        "username": post.owner_username,
        "likecount": post.likes,
        "viewVideo": viewVideo,
        "replycount": post.comments,
        "platformname": PLATFORM_NAME

    }
    # pu=[id_post,post_owner,post_date,post_caption,post_likes,post_comments]
    a.append(data)
    # L.download_post(post, "instagram")
df = pd.DataFrame(a, columns=["id_post","Date","Heure", "content", "username", "likecount","viewVideo", "replycount","platformname"])

df.to_csv("C:/Users/HP Probook/OneDrive/Images/Bureau/CsvScraping/instagram.csv", mode="w", sep=";",encoding='utf-8', index=False)
Infos_json = df.to_json(orient='records', indent=4)
print(Infos_json.encode('utf-8').decode('utf-8'))

**Comment by ihabpalamino** [comment]
i found the solution was to add     L.load_session_from_file(sessionfile)
