### ISSUE TITLE
Challange Problem

### ISSUE THREAD

**Issue by shanmugad** [instaloader/instaloader#2016]
```

Downloading images from prachi.256...
Traceback (most recent call last):
  File "C:\Users\aza\desktop\qDiffusion-master\insta-face-scraper-main\hassan-insta.py", line 145, in <module>
    download_images(username, max_photos)
  File "C:\Users\aza\desktop\qDiffusion-master\insta-face-scraper-main\hassan-insta.py", line 37, in download_images
    loader.login(ig_username, ig_password)
  File "C:\Users\aza\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloader.py", line 601, in login
    self.context.login(user, passwd)
  File "C:\Users\aza\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloadercontext.py", line 239, in login
    raise ConnectionException("Login: Checkpoint required. Point your browser to "
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXFNeZtNEal5v4YDmjCQWXewNzbhQTU_BEeSFj5B_SxgXN99LhTs5me87MsfT0UVnjE_EQ/Afz9EgwZV4AEkLYDFmrRN2wk0Ry5f6X8ICX4OtEZILv6RoJv3PFqacGB9-_R4M3XQ5LSX9OMGxJfTA/ffc_SxqfaaUs6NWdBFbIEFLPlTcbnLxXRQhkFBU4ELed9Dk9IhhGHtQiwdejT1ymH6TB/ - follow the instructions, then retry.
```

I am getting Challenge problem. even after login and completing in browser and when i retry. it same problem again and again

**Comment by ArtDanger** [comment]
when i use. i get same traceback 
```python
Traceback (most recent call last):

> File "/home/albedo/PycharmProjects/posting_insta_to_tg_group/InstagramPostsToTelegram/test_instaloader.py", line 24, in <module>
    main()
    └ <function main at 0x7f9961011c60>

  File "/home/system_user/PycharmProjects/posting_insta_to_tg_group/InstagramPostsToTelegram/test_instaloader.py", line 14, in main
    L.login(USER, PASSWORD)        # (login)
    │ │          │                  └ 'pswd'
    │ │          └ 'login'
    │ └ <function Instaloader.login at 0x7f995fd19260>
    └ <instaloader.instaloader.Instaloader object at 0x7f99610280d0>

  File "/home/system_userPycharmProjects/posting_insta_to_tg_group/venv/lib/python3.11/site-packages/instaloader/instaloader.py", line 634, in login
    self.context.login(user, passwd)
    │    │       │                 │     └ 'pswd'
    │    │       │                 └ 'login'
    │    │       └ <function InstaloaderContext.login at 0x7f995fea47c0>
    │    └ <instaloader.instaloadercontext.InstaloaderContext object at 0x7f99604d4850>
    └ <instaloader.instaloader.Instaloader object at 0x7f99610280d0>
  File "/home/system_user/PycharmProjects/posting_insta_to_tg_group/venv/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 239, in login
    raise ConnectionException("Login: Checkpoint required. Point your browser to "
          └ <class 'instaloader.exceptions.ConnectionException'>

instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.comhttps://www.instagram.com/challenge/AXFmauZBSXy4a3DGi7PxyRCm2F3urHJR1ageLg5tPzBaEMP6psBg-7pZ2p0edTo9d93HJJo/Afx3VCz6BdtGtx6wTB1HkN9-uuioQt5m6bW_XRvwo5X6620v_9sUfCvsJq9R3z432DpDQbFn8JBlaw/?challenge_context=Af7AOfd7rGIW-vRS6lLHIFrhk2NYxs1BFoixvVDXdMt5Cf7S5SB_9_N-jKas4SBFFhJqv29BEgE4lw0GMS-TqkmOFtZ7MccresJa5XAQPg6Ds7hXcIAQyIIXWzOv_mu2U3TZb-7iXnuvYjJANoyX7psyS1z0eqW1pl9wSGBjIQ6Bm0KTgyG9d77iNvM1RQwrxLRVKuGViSApf0mIbynKXFkJJAV_GhHKjEfsZ0WszRE9yMafawGHV9VgTc_lGzTC2pH5vBG0WwqmZtTsSgapGgWp_Ecp5H4hsz6DvztXYrnMG8fE0uwmLMpB2q54B0R3089bF9VsCgbbUkHtgIGujhqW8L6sX8acLLgvDHwcOTNPjxfwjLDH47Wtp9e9MNa-Qg7XSh59KmJYxlBJOprES9U6z0QMzKRsMYJtnHD7N5PXEyem2HBI7DsUAmfp0echOOSJaAWKgBxF0JSASHRKZeXCvQHUms-fVp3fMtWsQmUYjAy6Ieai_LZx8ql5crkq_Mv5n7PMU_eB_kOTy_x_AjkGSCjZoz0HQ8AwOfecA0FZY8SUZ6PkO8SmQ-_mwVEL-uFqM-SK3x6BoSonD_4Rq6w5YXtXMOKVSM232TlW212ppeLWQi3xZSCRjVuW7pCUpVDudNqGDbsZcnbSnp1pNtrLK2hTLmUR7TDpG2SYy-qhb_BiQlzqPU_mbzYFiMMynNiTnPIvWDJ4oBsdMRTimS1WTd1rvqA0G0o58NwZHbF3A6OTsvv0qoz8cSvJ2H0GGc8_SH53L8XeWvYAnp7eVuTYd9zcR1Ewxnam2Lr5Oaohkw537nwyb3xVHOspC1cA33hzu4Ys8KenXxap3GL0XqGwOrTJ9zd5W8GF2s9pv2BaQeWdYxDJ6y7ejyt_Fg1WlynvPr-Pl0_3tQ4JYCcJOhhYfqV-9koywmuh-p0sX9LHE-d03UKAwS3cCCKQXJBF-SdlKaYGcqMN6dTz0j5NBL0OeMX868zaatcBtri5u8tgeT1SuVKtckY8jJLDhogFt5u78JWYxWIM0se_9trlhfQ5ZqLDdwNv-v_SNa6ocv94Mx1gyUL3rTUwnsn63ZWGcsCSjFKmqw8_A7rC8u8aWxRW8GMubBfzys21MXRsfj4YaH8zaHA-7mIKHE1pHxQTB87TSAnjb1J-D_ollIAWreeNqOAIi1b4cxDMpLzdglWLzzv6pbl0b6Mywu4kX7tU-Q - follow the instructions, then retry.
```

my test code 

```python
from loguru import logger
from instaloader import Instaloader, Profile


@logger.catch
def main():
    USER = 'your login'
    PASSWORD = 'your password'

    # Get instance
    L = Instaloader()

    # Optionally, login or load session
    L.login(USER, PASSWORD)        # (login)  <----------------------------------------- line 24 (error)
    L.interactive_login(USER)      # (ask password on terminal)
    L.load_session_from_file(USER) # (load session created w/
                               #  `instaloader -l USERNAME`)
    profile = Profile.from_username(L.context, USER)
    print(f'username {profile.username}')
    print(f'followers {profile.get_followers()}')


if __name__ == '__main__':
    main()

```
