### ISSUE TITLE
Login error: JSON decode fail, 403 - Forbidden.

### ISSUE THREAD

**Issue by ImTheFakeOne** [instaloader/instaloader#2025]
**Describe the bug**
When trying to log in to a instagram account it will throw 

"Exception has occurred: ConnectionException
Login error: JSON decode fail, 403 - Forbidden."

and fails to log in also when using cmd gives

"JSON Query to user/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to user/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]"
 

**To Reproduce**
case 1:
python script

instaloader.Instaloader().login(user, pass)
Passing the correct parameters checked in debug

case 2:
using cmd 

instaLoader [profile] --login [myloginUsername]

**Expected behavior**
Should log in and keep that session open to retrieve data from that profile

**Error messages and tracebacks**
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instaloader\instaloadercontext.py", line 224, in login       
    resp_json = login.json()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\insta\DownloadVids\main.py", line 145, in <module>
    attemptRoutine()
  File "C:\Users\user\Desktop\insta\DownloadVids\main.py", line 136, in attemptRoutine
    routine()
  File "C:\Users\user\Desktop\insta\DownloadVids\main.py", line 90, in routine
    scrapeVideos(username = IG_USERNAME,
  File "C:\Users\user\Desktop\insta\DownloadVids\scrape_videos.py", line 18, in scrapeVideos
    L.login(username, password)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instaloader\instaloader.py", line 483, in login
    self.context.login(user, passwd)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instaloader\instaloadercontext.py", line 226, in login       
    raise ConnectionException("Login error: JSON decode fail, {} - {}.".format(login.status_code, login.reason))
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 403 - Forbidden.

**Instaloader version**
instaloader              4.5.5

**Additional context**
Instagram account is not private and doesn't possess any authentication just logging in anything works but with this script

**Comment by Showmaster3000** [comment]
You are using an outdated version! Please update to the latest one!
