### ISSUE TITLE
Max retries exceeded with url 

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#2041]
What means " Max retries exceeded with url:" ? Because i can continue to download other profiles in the same time. So this error is from instaloader or from instagram?

`instaloader --login=user --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0" --abort-on=302,400,401,429,403 --fast-update --highlights --stories --tagged thehiddensphere/`

```
Downloading stories
[1/1] Retrieving stories from profile thehiddensphere.
[  1/  3] thehiddensphere/2023-07-24_18-48-16_UTC.jpg json 
[  2/  3] thehiddensphere/2023-07-23_21-56-56_UTC.mp4 thehiddensphere/2023-07-23_21-56-56_UTC.jpg json 
[  3/  3] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1045, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='instagram.fath7-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /o1/v/t16/f1/m78/8F4E00624DD0BFAE3A967BA3F5267686_video_dashinit.mp4?efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uNzIwLnN0b3J5LmJhc2VsaW5lIn0&_nc_ht=instagram.fath7-1.fna.fbcdn.net&_nc_cat=102&vs=672674650917383_1476867135&_nc_vs=HBksFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzhGNEUwMDYyNEREMEJGQUUzQTk2N0JBM0Y1MjY3Njg2X3ZpZGVvX2Rhc2hpbml0Lm1wNBUAAsgBABUAGCRHTmROOGhPMlhfYl8xTjRDQU0wOGdsZ2laclZEYnBSMUFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMRUAACby6pSZpN3SPxUCKAJDMywXQCPdsi0OVgQYEmRhc2hfYmFzZWxpbmVfMV92MREAdegHAA%3D%3D&ccb=9-4&oh=00_AfAdJQSvC9TKL-m8baSPiUsyTKe-kHB66Nxmls8PfWck_A&oe=64C07A85&_nc_sid=d8d02b (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:992)')))

```

**Comment by estatistics** [comment]
instaloader is already the latest version (4.9.5+ds-1).

**Comment by Showmaster3000** [comment]
> instaloader is already the latest version (4.9.5+ds-1).

This version is 10 months old. Latest 4.10 is two weeks old.
Nevertheless your problem seems to be a connection problem for me which is not caused by instaloader.
