### ISSUE TITLE
Crash when using --latest-stamps filename-with-empty-dirname.ini

### ISSUE THREAD

**Issue by sczerniawski** [instaloader/instaloader#2055]
**Describe the bug**
Specifying `--latest-stamps latest-stamps.ini` on the command line leads to the following error (at least on linux using python-3.8):
```Using latest stamps from latest-stamps.ini.
Loaded session from ***.
Logged in as ***.
[1/1] Downloading profile ***
Retrieving tagged posts for profile ***.
Traceback (most recent call last):
  File "/home/stasiek/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 1466, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter,
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 1270, in download_tagged
    latest_stamps.set_last_tagged_timestamp(profile.username, tagged_posts.first_item.date_local)
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/lateststamps.py", line 87, in set_last_tagged_timestamp
    self._set_timestamp(profile_name, self.TAGGED_TIMESTAMP, timestamp)
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/lateststamps.py", line 71, in _set_timestamp
    self._save()
  File "/home/stasiek/.local/lib/python3.8/site-packages/instaloader/lateststamps.py", line 30, in _save
    makedirs(dirname(self.file), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**To Reproduce**
```bash
python3.8 -m pip instaloader \
                --login ***
                --latest-stamps latest-stamps.ini \
                --no-compress-json --fast-update \
                --tagged --stories --highlights \
                example_profile
```

**Expected behavior**
No crash.

**Instaloader version**
```bash
$ python3.8 -m instaloader --version
4.10
```

PR is coming in a sec.

**Comment by viperey** [comment]
I've also seen this behavior happening in python 3.11
