### ISSUE TITLE
problem in login

### ISSUE THREAD

**Issue by Mohammadahmadi04** [instaloader/instaloader#2059]
Dear to whom this may concern , 

Recently I’ve been trying to login into my Instagram page to bring out a list of my followers by using Instaloader and following necessary syntaxes. Yet I have been receiving an error that is shown as followed:

import instaloader
from userpw import username,password

loader = instaloader.Instaloader()

loader.login(username, password)

profile = instaloader.Profile.from_username(loader.context, username)

for follower in profile.get_followers():
    print(follower.username)

---------------------------------------------------------

JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\python class\project\a.py", line 8, in <module>
    loader.login(username, password)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloader.py", line 651, in login
    self.context.login(user, passwd)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 259, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 448, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 448, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 436, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Comment by NociveDoggo** [comment]
I'm having the same issue in terminal using the `instaloader instagram -l user` command.

This is what I get:

```
Loaded session from /Users/user/.config/instaloader/session-user.
Enter Instagram password for user:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
```

**Comment by kmastra** [comment]
any news?? i am facing the same today!

**Comment by eduardosadi** [comment]
estou com o mesmo problema aqui :/

**Comment by moithepro** [comment]
Let's gooooo
