### ISSUE TITLE
"TypeError: expected string or bytes-like object" while downloading profile

### ISSUE THREAD

**Issue by marcelomazza** [instaloader/instaloader#2061]
**Describe the bug**
TypeError: expected string or bytes-like object while running `instaloader profile loqesangra`

**To Reproduce**
Run `instaloader profile loqesangra`

**Expected behavior**
Download the whole profile.

**Error messages and tracebacks**
```
[195/319] loqesangra/2021-02-24_17-48-00_UTC.jpg exists Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/Library/Python/3.8/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/Library/Python/3.8/site-packages/instaloader/instaloader.py", line 1489, in download_profiles
    self.posts_download_loop(posts_to_download, profile_name, fast_update, post_filter,
  File "/Library/Python/3.8/site-packages/instaloader/instaloader.py", line 1064, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/Library/Python/3.8/site-packages/instaloader/instaloader.py", line 773, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
  File "/Library/Python/3.8/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "/Library/Python/3.8/site-packages/instaloader/instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Instaloader version**
```
~/Downloads $ instaloader --version
/Users/marcelo/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
4.10
```

**Comment by RedAero** [comment]
I'm also getting the same (well, nearly) error on the .exe version on multiple accounts.

**Comment by aandergr** [comment]
> **Instaloader version**
> 
> ```
> ~/Downloads $ instaloader --version
> /Users/marcelo/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
>   warnings.warn(
> 4.10
> ```

Does this also happen with a recent Instaloader version?

**Comment by marcelomazza** [comment]
Hi @aandergr , I uploaded the version:

```
 ~/psl/instaloader $ instaloader --version
4.13.1
```

and now I'm getting:

```
[195/320] loqesangra/2021-02-24_20-42-32_UTC.jpg [Si chequeaste las stories y n…] json
[196/320] loqesangra/2021-02-24_17-48-00_UTC.jpg Traceback (most recent call last):
  File "/opt/anaconda3/bin/instaloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/__main__.py", line 563, in main
    exit_code = _main(loader,
                ^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/__main__.py", line 300, in _main
    instaloader.download_profiles(profiles,
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/instaloader.py", line 1506, in download_profiles
    self.posts_download_loop(posts_to_download, profile_name, fast_update, post_filter,
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/instaloader.py", line 1076, in posts_download_loop
    downloaded = self.download_post(post, target=target)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/instaloader.py", line 778, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/instaloader/instaloader.py", line 340, in download_pic
    urlmatch = re.search('\\.[a-z0-9]*\\?', url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Comment by RedAero** [comment]
> Does this also happen with a recent Instaloader version?

Just updated to 4.13, yes, same as it always has.

`Traceback (most recent call last):
  File "__main__.py", line 609, in <module>
  File "__main__.py", line 606, in __main
  File "__main__.py", line 563, in main
  File "__main__.py", line 300, in _main
  File "instaloader\instaloader.py", line 1483, in download_profiles
  File "instaloader\instaloader.py", line 1276, in download_tagged
  File "instaloader\instaloader.py", line 1076, in posts_download_loop
  File "instaloader\instaloader.py", line 778, in download_post
  File "instaloader\instaloader.py", line 97, in call
  File "instaloader\instaloader.py", line 340, in download_pic
  File "re\__init__.py", line 177, in search
TypeError: expected string or bytes-like object, got 'NoneType'
[10836] Failed to execute script '__main__' due to unhandled exception!`

**Comment by aandergr** [comment]
> Hi @aandergr , I uploaded the version:
> 
> ```
>  ~/psl/instaloader $ instaloader --version
> 4.13.1
> ```

Thanks for trying with the latest version. Indeed, it is reproducible that for this post (shortcode `CLrxLZglPIC`), the video_url field is None and the download aborts with the mentioned error message.

> **Expected behavior**
> Download the whole profile.

The video of that particular post cannot be accessed even when accessing Instagram with the browser, making it unlikely that Instaloader can access it. However, Instaloader should not fail with an error and abort the whole download process, rather it should skip downloading this video, show a warning message, and continue.
