### ISSUE TITLE
if highlights with "id" name exists, fails to download them cause "id" (as file) exists

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#2070]
if highlights with "id" name exists, fails to download them cause "id" (as file) exists #2070 

```instaloader --login=user --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0b5" --abort-on=302,400,401,429,403  --fast-update  --highlights --stories --tagged nikipt/```

instaloader 4.10, linux
```
Retrieving highlights "id" from profile nikipt
Traceback (most recent call last):
  File "/home/elias/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 1478, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 971, in download_highlights
    self.download_highlight_cover(user_highlight, highlight_target)
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 580, in download_highlight_cover
    self.download_title_pic(highlight.cover_url, target, 'cover', highlight.owner_profile)
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 540, in download_title_pic
    filename = self.__prepare_filename(filename_template, lambda: url) + ".jpg"
  File "/home/elias/.local/lib/python3.10/site-packages/instaloader/instaloader.py", line 673, in __prepare_filename
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/home/elias/miniconda3/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'nikipt/id'
```

**Comment by estatistics** [comment]
in linux, you cant have a filename "id" and a folder named "id", so, maybe, "id" file may be renamed in something else if such conflicts are found?  (but how many people will have named highlights as "id"?

You may through a more specific warning on that maybe?
