### ISSUE TITLE
Looking help with error - [WinError 3] The system cannot find the path specified: ''

### ISSUE THREAD

**Issue by i-was-lost** [instaloader/instaloader#2082]
So I've been running instaloader using a simple batch file:

`@echo off
set /p user="Enter username: "
instaloader +insta_args.txt %user% > output.txt 2> output.err`

With insta_args.txt as such:

```
--login=i_was_lost
--password=password123
--latest-stamps=record.txt
--no-videos
--no-captions
--no-metadata-json
```

All was working fine on a previous machine using Windows 10. I have since moved this batch file, along with accompanying files, to a new machine (also Windows 10). Installed latest python 3 and then instaloader module through pip3.

I then had the 'Could not find "window._sharedData"' issue with the login but used the 'session token from Firefox' workaround in the troubleshooting documentation. This then leads to the current error, which has me a little confused.

From the output file, it looks like login is successful:

`Using latest stamps from record.txt.
Loaded session from C:\Users\lost\AppData\Local\Instaloader\session-i_was_lost.
Logged in as i_was_lost.
`

But then an output.err file is produced, which reads as follows:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lost\AppData\Local\Programs\Python\Python311\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\lost\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\__main__.py", line 470, in main
    _main(loader,
  File "C:\Users\lost\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\__main__.py", line 181, in _main
    profile = instaloader.check_profile_id(target, latest_stamps)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lost\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloader.py", line 1385, in check_profile_id
    latest_stamps.save_profile_id(profile.username, profile.userid)
  File "C:\Users\lost\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\lateststamps.py", line 49, in save_profile_id
    self._save()
  File "C:\Users\lost\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\lateststamps.py", line 30, in _save
    makedirs(dirname(self.file), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

I wonder why instaloader is trying to use this empty path? Where in my setup could the issue be arising?

My apologies for not being good with this sort of thing!

**Comment by i-was-lost** [comment]
Tried uninstalling and re-installing instaloader and also trying it from a different directory/disk.

Still the same empty path error. Really at a loss.

Could this be a bug?

**Comment by Fabio-Velasquez** [comment]
Hey man, i had encountered this error when porting my script to different machines. It was because my script did not have admin access. It worked after enablling that
