### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by skrako** [instaloader/instaloader#2116]
Not able to login

import instaloader
# Get instance
L = instaloader.Instaloader()
# Login or load session
L.interactive_login('skrako_')
# Obtain profile metadata
profile = instaloader.Profile.from_username(L.context, "skrako_")

**Expected behavior**
Be able to access profile data

**Error messages and tracebacks**
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 356, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "instabot_3.py", line 674, in <module>
    main()
  File "instabot_3.py", line 649, in main
    data_analyzer = DataAnalyzer()
  File "instabot_3.py", line 582, in __init__
    self.__update_df()
  File "instabot_3.py", line 590, in __update_df
    L.interactive_login('skrako_')        # (login)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloader.py", line 1572, in interactive_login
    self.login(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 214, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 382, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Instaloader version**
`instaloader --version` output. 4.9.5

**Comment by aandergr** [comment]
Outdated version. Please update to 4.10.2.
