### ISSUE TITLE
KeyError when getting the 'igtvcount' attribute of Profile object

### ISSUE THREAD

**Issue by gordon0907** [instaloader/instaloader#2121]
**Describe the bug**
I have a script that uses instaloader. The script has been running smoothly for the past year until yesterday when I got an error. After some debugging, I found that it is a `KeyError: 'edge_felix_video_timeline'`, raised in line 829 of `instaloader\structures.py`. I have tried a few more times, I found that this error is likely to occur only if I log in. I have double-checked that my account is not banned (I can log in and browse posts normally in Firefox). And I also tried to use [615_import_firefox_session.py](https://github.com/instaloader/instaloader/blob/master/docs/codesnippets/615_import_firefox_session.py), to regenerate the session from Firefox. But the problem is still here.

**To Reproduce**
Here is the simplest code to reproduce the behavior:
```
import instaloader
il = instaloader.Instaloader()
il.load_session_from_file(username='username', filename='filename')  # use an existing session file
assert il.test_login()  # make sure that login successed
profile = instaloader.Profile.from_username(il.context, '__megbaby_')
profile.igtvcount
```

**Expected behavior**
Expect the return of `igtvcount` with no error.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "X:\Instagram Downloader\venv\Lib\site-packages\instaloader\structures.py", line 829, in _metadata
    d = d[key]
        ~^^^^^
KeyError: 'edge_felix_video_timeline'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "X:\Instagram Downloader\venv\Lib\site-packages\instaloader\structures.py", line 884, in igtvcount
    return self._metadata('edge_felix_video_timeline', 'count')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Instagram Downloader\venv\Lib\site-packages\instaloader\structures.py", line 835, in _metadata
    d = d[key]
        ~^^^^^
KeyError: 'edge_felix_video_timeline'
```

**Instaloader version**
4.10.1

**Additional context**
Since I only have one IG account, I only tested on one account. But recently I just used this account as usual, and have never done any strange things on it (e.g., VPN or something else).

**Comment by gordon0907** [comment]
I tried again today, with the same script and environmental setting. But I can no longer reproduce the case. Perhaps it was a problem on Instagram's server.

So I'm going to close this issue here.

**Comment by duerecompense** [comment]
I am also now getting this same error consistently since yesterday.

**Comment by Jarsky** [comment]
Just upgraded, also receiving this error

```
KeyError: 'edge_felix_video_timeline'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/usr/local/lib/python3.12/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/usr/local/lib/python3.12/site-packages/instaloader/instaloader.py", line 1472, in download_profiles
    self.download_igtv(profile, fast_update=fast_update, post_filter=post_filter,
  File "/usr/local/lib/python3.12/site-packages/instaloader/instaloader.py", line 1286, in download_igtv
    igtv_posts = profile.get_igtv_posts()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instaloader/structures.py", line 1092, in get_igtv_posts
    self._metadata('edge_felix_video_timeline'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instaloader/structures.py", line 835, in _metadata
    d = d[key]
        ~^^^^^
```

**Comment by gordon0907** [comment]
Oh, yes. I ran my script again today, and I got this error again.

So, let me reopen this issue here.

**Comment by duerecompense** [comment]
Checked and `self._metadata` no longer contains `"edge_felix_video_timeline"`, and I haven't been able to find another variable or endpoint that contains the expected video information either.

Seems like Instagram recently changed how it returns information and similar issues are being reported. #2142

The API changelog shows that some other changes went into effect on [2023-12-11.](https://developers.facebook.com/docs/instagram-api/changelog/#:~:text=September%2012%2C%202023,December%2011%2C%202023.). I haven't been able to figure out where the appropriate change is needed.

**Comment by Xosmond** [comment]
I'm getting this error as well. Is there a workaround?

**Comment by gordon0907** [comment]
It seems that without the `igtvcount` attribute, there is no way for us to download REELS. (Originally we can call `get_igtv_posts` method of `Profile` objects.)

I have also tried hardcoding `{'count': 0, 'page_info': {'has_next_page': True, 'end_cursor': ''}, 'edges': []}` into `Profile._node`. With this hardcode, I'm able to retrieve some old REELS only. In my case, those REELS are all earlier than 2023 (the lastest one around 2022 Sep).

Here is a simple example code:
```
import instaloader
il = instaloader.Instaloader()
il.load_session_from_file(username='username', filename='filename')  # use an existing session file
assert il.test_login()  # make sure that login successed
profile = instaloader.Profile.from_username(il.context, 'instagram')
profile._node['edge_felix_video_timeline'] = {'count': 0, 'page_info': {'has_next_page': True, 'end_cursor': ''}, 'edges': []} # seems that the value of 'count' doesn't matter
igtv_iter = profile.get_igtv_posts()
[next(igtv_iter) for n in range(10)]
```
The result I got from the above code is as follows:
```
[<Post Ch74NvrD2UV>, <Post ChNXTUuJQiQ>, <Post CfsDirnD3Fd>, <Post Cd9BGJ4DOlu>, <Post Cd6je_RjumK>, <Post Cb5WT-Uhj6Z>, <Post Cbx0lS3peQC>, <Post CbiFqgQDcVe>, <Post Ca-J5ghBNUs>, <Post CasIEvwpDJ6>]
```
The latest REELS is the first one, with shortcode `Ch74NvrD2UV`.

According to the above observation, maybe the current `querty_hash` for `igtv_posts` is outdated. The current one in `structures.py` is `bc78b344a68ed16dd5d7f264681c4c76`.

But I have no idea about Instagram's API. May someone give a help on this.

**Comment by nokia8801** [comment]
I'm having the same or a similar issue.

```
Retrieving IGTV videos for profile exampleusername.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/instaloader/structures.py", line 902, in _metadata
    d = d[key]
        ~^^^^^
KeyError: 'edge_felix_video_timeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/instaloader", line 33, in <module>
    sys.exit(load_entry_point('instaloader==4.10.3', 'console_scripts', 'instaloader')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/instaloader/__main__.py", line 470, in main
    _main(loader,
  File "/usr/lib/python3.11/site-packages/instaloader/__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 1478, in download_profiles
    self.download_igtv(profile, fast_update=fast_update, post_filter=post_filter,
  File "/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 1292, in download_igtv
    igtv_posts = profile.get_igtv_posts()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/instaloader/structures.py", line 1165, in get_igtv_posts
    self._metadata('edge_felix_video_timeline'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/instaloader/structures.py", line 908, in _metadata
    d = d[key]
        ~^^^^^
KeyError: 'edge_felix_video_timeline'
```

**Comment by arthur-lim** [comment]
I'm having the same issue here

```
Traceback (most recent call last):
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\structures.py", line 969, in _metadata
    d = d[key]
KeyError: 'edge_felix_video_timeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\__main__.py", line 541, in main
    _main(loader,
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\__main__.py", line 283, in _main
    instaloader.download_profiles(profiles,
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\instaloader.py", line 1478, in download_profiles
    self.download_igtv(profile, fast_update=fast_update, post_filter=post_filter,
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\instaloader.py", line 1292, in download_igtv
    igtv_posts = profile.get_igtv_posts()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\structures.py", line 1232, in get_igtv_posts
    self._metadata('edge_felix_video_timeline'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\structures.py", line 975, in _metadata
    d = d[key]
        ~^^^^^
KeyError: 'edge_felix_video_timeline'
```
