### ISSUE TITLE
Get error while authentication via terminal

### ISSUE THREAD

**Issue by saurabhvns01** [instaloader/instaloader#2173]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instaloader\__main__.py", line 470, in main
    _main(loader,
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instaloader\__main__.py", line 120, in _main
    instaloader.interactive_login(username)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instaloader\instaloader.py", line 1589, in interactive_login
    self.login(username, password)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instaloader\instaloader.py", line 651, in login
    self.context.login(user, passwd)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\instaloader\instaloadercontext.py", line 260, in login
    csrf_token = csrf_json['config']['csrf_token']
                 ~~~~~~~~~^^^^^^^^^^
KeyError: 'config'

**Comment by saurabhvns01** [comment]
It's working.

**Comment by rgrjnr** [comment]
Getting the same error here

**Comment by EllisCallaghan** [comment]
any update? This error didn't exist 2 months ago

**Comment by sunyshore** [comment]
same error

**Comment by EllisCallaghan** [comment]
logging into instaloader with the firefox session solved it for me.
