### ISSUE TITLE
Error downloading IGTV files

### ISSUE THREAD

**Issue by OGF7322** [instaloader/instaloader#2224]
**Describe the bug**
Using the following command in the command line interface:
.\instaloader --login=[account name] [profile name] --stories --highlights --igtv
and a successfull login an error appeared right after completing the download of the profile and starting on the IGTV files.

removing the "--igtv" fixes the issue and downloads everything else as expected

**To Reproduce**
In the command line the usage of the "--igtv" modifier cuases this error. It is not limited to one account, the error appeared on all accounts I tried this command on.
The issue does not happen, when you don't log in.

**Expected behavior**
I expected a download without an error

**Error messages and tracebacks**
Retrieving IGTV videos for profile [profile name].
Traceback (most recent call last):
  File "instaloader\structures.py", line 969, in _metadata
KeyError: 'edge_felix_video_timeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 577, in <module>
  File "__main__.py", line 574, in __main
  File "__main__.py", line 541, in main
  File "__main__.py", line 283, in _main
  File "instaloader\instaloader.py", line 1478, in download_profiles
  File "instaloader\instaloader.py", line 1292, in download_igtv
  File "instaloader\structures.py", line 1232, in get_igtv_posts
  File "instaloader\structures.py", line 975, in _metadata
KeyError: 'edge_felix_video_timeline'
[540] Failed to execute script '__main__' due to unhandled exception!

**Instaloader version**
4.11

**Additional context**
The instagram account I'm using is a newly created one, this might cause the issue.

**Comment by UnlimitedCookies** [comment]
> There has been no activity on this issue for an extended period of time. This issue will be closed after further 14 days of inactivity.

Please get rid of the stale bot. The mere assumption that issues resolve themselves over time without action is fundamentally naive.
