### ISSUE TITLE
Login throws at _find_no_duplicates

### ISSUE THREAD

**Issue by tulssinep** [instaloader/instaloader#2242]
**Describe the bug**
Regardless of whether I try to use instaloader via command line or via python package in code, I can't log in.

Doing it via command line, I get "Login error: Wrong password." (and one time I saw a longer error message about the same thing that looks like it comes from IG). Doing it via code, it throws immediately as shown in the stack trace below

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
```
python3 main.py 
Traceback (most recent call last):
  File "/Users/pp/instacopy/main.py", line 7, in <module>
    L.login("abc", "12")        # (login)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/instaloader.py", line 651, in login
    self.context.login(user, passwd)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 318, in login
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
                                           ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"
```

**Instaloader version**
4.11

I tried with 2 different accounts.

**Comment by tulssinep** [comment]
I may add that `resp_json` looks like everything should be ok: `{'user': True, 'userId': '123', 'authenticated': True, 'oneTapPrompt': True, 'reactivated': True, 'status': 'ok'}` 

Here is the log output from running it directly in the git repository:
```
$ python3 instaloader.py --login=ab profile abc
Session file does not exist yet - Logging in.
Enter Instagram password for ab: 
{'user': True, 'userId': '123', 'authenticated': True, 'oneTapPrompt': True, 'reactivated': True, 'status': 'ok'}
Traceback (most recent call last):
  File "/Users/pp/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/Users/pp/instaloader/instaloader/__main__.py", line 541, in main
    _main(loader,
  File "/Users/pp/instaloader/instaloader/__main__.py", line 184, in _main
    instaloader.interactive_login(username)
  File "/Users/pp/instaloader/instaloader/instaloader.py", line 1595, in interactive_login
    self.login(username, password)
  File "/Users/pp/instaloader/instaloader/instaloader.py", line 651, in login
    self.context.login(user, passwd)
  File "/Users/pp/instaloader/instaloader/instaloadercontext.py", line 320, in login
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
                                           ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"
```
