### ISSUE TITLE
HTTP redirect ends with a KeyError: 'video_url'

### ISSUE THREAD

**Issue by hgkmaxymus** [instaloader/instaloader#225]
Hello,

While downloading the photo 49 of 264 of this certain profile, this error appears and stops the crawling.
Here is the log:

```
HTTP redirect from https://www.instagram.com/p/BfQb4cSAq-j/ to https://www.instagram.com/p/BfQcCIWgVdq
Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 147, in _field
    d = d[key]
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\Scripts\instaloader-script.py", line 10, in <module>
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 184, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 941, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 424, in download_post
    downloaded &= self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 265, in video_url
    return self._field('video_url')
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 152, in _field
    d = d[key]
KeyError: 'video_url'
```

**Instaloader version**
```
$ instaloader --version

4.2
```
**Additional context**
Ah, I had trouble running the instaloader in my Bash (I use Win10, so I used the windows version til you guys updated the linux version and didn't release a Windows update :P ), so I fixed it by adding a encoding and quotes to the file path in the instaloader-script.py since my windows username has a space. (I don't know if it is considered a "bug" fix, but it did the trick for me)

```
$ cat "/c/Users/hgk maxymus/AppData/Local/Programs/Python/Python35-32/Scripts/instaloader-script.py"

# This Python file uses the following encoding: utf-8
#!"c:\users\hgk maxymus\appdata\local\programs\python\python35-32\python.exe"
# EASY-INSTALL-ENTRY-SCRIPT: 'instaloader==4.2','console_scripts','instaloader'
__requires__ = 'instaloader==4.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('instaloader==4.2', 'console_scripts', 'instaloader')()
    )

```

Thanks! Keep the nice work! :)

**Comment by Thammus** [comment]
Hello,

I tried downloading the post on which your error occured and it did not reproduce the `KeyError`. The redirect worked as expected and the video is being downloaded fine. 
```
$ instaloader -- -BfQb4cSAq-j

HTTP redirect from https://www.instagram.com/p/BfQb4cSAq-j/ to https://www.instagram.com/p/BfQcCIWgVdq
-BfQb4cSAq-j/2018-02-16_12-02-16_UTC_1.jpg -BfQb4cSAq-j/2018-02-16_12-02-16_UTC_2.jpg -BfQb4cSAq-j/2018-02-16_12-02-16_UTC_2.mp4 [#cartagena por do sol em #caf…] json
```
Maybe this was a temporary error on Instagram's side or with the internet connection. Have you simply tried to re-download the posts?

Concerning your second problem, it seems like the responsibility lies on the side of pip or setuptools which do not support spaces in the path to the python executable. So this is not directly related to Instaloader and your "adding quotes"-fix should be sufficient.

Greetings

**Comment by hgkmaxymus** [comment]
Hello,

I tried to re-download the full profile, no go. So, I checked your command and thought "maybe the issue is the redirect interfering with my filename pattern". Tried that and same error.  Finally, I decided to download the single post, no issues (it even said I had it already!). Then I thought it could be the next post having issues (not the 49th, could be the 50th with error), but no, I could download it. So, at this moment, I am downloading post by post, without issues. For some reason, the automatic list isn't able to download something between the 49th (the 49th has the same video of the 48th post - which has a photo and the video) and the 50th post.

Below are my logs:

My default command:
```
$ instaloader --dirname-pattern={profile} --filename-pattern="{profile} - {shortcode}" --max-connection-attempts=0 --no-captions --no-metadata-json cleidir.fit_
cleidir.fit_/2018-10-23_18-52-25_UTC_profile_pic.jpg already exists
Retrieving posts from profile cleidir.fit_.
[  1/265] cleidir.fit_/cleidir.fit_ - BsioxA8BL-A.jpg exists
[  2/265] cleidir.fit_/cleidir.fit_ - BsPNE9oBkkA.jpg exists
[  3/265] cleidir.fit_/cleidir.fit_ - BsMQ7-rBXQ0_1.jpg exists cleidir.fit_/cleidir.fit_ - BsMQ7-rBXQ0_2.jpg exists cleidir.fit_/cleidir.fit_ - BsMQ7-rBXQ0_3.jpg exists
[  4/265] cleidir.fit_/cleidir.fit_ - BsGwQHOBNcp.jpg exists
[  5/265] cleidir.fit_/cleidir.fit_ - BsEicpJhDOl.jpg exists
[  6/265] cleidir.fit_/cleidir.fit_ - BsB0m4aB375.jpg exists
[  7/265] cleidir.fit_/cleidir.fit_ - BsBUnkuBhbI_1.jpg exists cleidir.fit_/cleidir.fit_ - BsBUnkuBhbI_2.jpg exists cleidir.fit_/cleidir.fit_ - BsBUnkuBhbI_3.jpg exists cleidir.fit_/cleidir.fit_ - BsBUnkuBhbI_4.jpg exists cleidir.fit_/cleidir.fit_ - BsBUnkuBhbI_5.jpg exists
[  8/265] cleidir.fit_/cleidir.fit_ - Br_HgS6hntE_1.jpg exists cleidir.fit_/cleidir.fit_ - Br_HgS6hntE_2.jpg exists cleidir.fit_/cleidir.fit_ - Br_HgS6hntE_2.mp4 exists
[  9/265] cleidir.fit_/cleidir.fit_ - Br5eGI9Bu7k.jpg exists
[ 10/265] cleidir.fit_/cleidir.fit_ - BryqzqKhz4I_1.jpg exists cleidir.fit_/cleidir.fit_ - BryqzqKhz4I_2.jpg exists cleidir.fit_/cleidir.fit_ - BryqzqKhz4I_3.jpg exists
[ 11/265] cleidir.fit_/cleidir.fit_ - BrvQkcchQzG.jpg exists
[ 12/265] cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_1.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_2.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_3.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_4.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_5.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_6.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_7.jpg exists cleidir.fit_/cleidir.fit_ - BrsoH0phB_z_8.jpg exists
[ 13/265] cleidir.fit_/cleidir.fit_ - Brp7yF2BOiM_1.jpg exists cleidir.fit_/cleidir.fit_ - Brp7yF2BOiM_2.jpg exists cleidir.fit_/cleidir.fit_ - Brp7yF2BOiM_3.jpg exists
[ 14/265] cleidir.fit_/cleidir.fit_ - BrnrLzbBoNu_1.jpg exists cleidir.fit_/cleidir.fit_ - BrnrLzbBoNu_2.jpg exists cleidir.fit_/cleidir.fit_ - BrnrLzbBoNu_3.jpg exists
[ 15/265] cleidir.fit_/cleidir.fit_ - BrLQbHzBIGp.jpg exists
[ 16/265] cleidir.fit_/cleidir.fit_ - BrIj8v_hJp8.jpg exists
[ 17/265] cleidir.fit_/cleidir.fit_ - BrGsl45nPAp.jpg exists
[ 18/265] cleidir.fit_/cleidir.fit_ - Bq0sOt1hE-R.jpg exists
[ 19/265] cleidir.fit_/cleidir.fit_ - BqnGsKyFtrM_1.jpg exists cleidir.fit_/cleidir.fit_ - BqnGsKyFtrM_2.jpg exists cleidir.fit_/cleidir.fit_ - BqnGsKyFtrM_2.mp4 exists
[ 20/265] cleidir.fit_/cleidir.fit_ - BqAgM8jh_50.jpg exists
[ 21/265] cleidir.fit_/cleidir.fit_ - Bp-oRSoh6yH.jpg exists
[ 22/265] cleidir.fit_/cleidir.fit_ - Bpsl9OghX9u.jpg exists
[ 23/265] cleidir.fit_/cleidir.fit_ - BpYDpjlh0hU_1.jpg exists cleidir.fit_/cleidir.fit_ - BpYDpjlh0hU_2.jpg exists cleidir.fit_/cleidir.fit_ - BpYDpjlh0hU_3.jpg exists cleidir.fit_/cleidir.fit_ - BpYDpjlh0hU_4.jpg exists
[ 24/265] cleidir.fit_/cleidir.fit_ - Bo4kT_dnPqX_1.jpg exists cleidir.fit_/cleidir.fit_ - Bo4kT_dnPqX_2.jpg exists cleidir.fit_/cleidir.fit_ - Bo4kT_dnPqX_3.jpg exists cleidir.fit_/cleidir.fit_ - Bo4kT_dnPqX_4.jpg exists
[ 25/265] cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_1.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_2.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_3.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_4.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_5.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_6.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_7.jpg exists cleidir.fit_/cleidir.fit_ - Bo2DHoQHJZg_8.jpg exists
[ 26/265] cleidir.fit_/cleidir.fit_ - BoCHfPiHFO3.jpg exists
[ 27/265] cleidir.fit_/cleidir.fit_ - BnwxpGPnz7a_1.jpg exists cleidir.fit_/cleidir.fit_ - BnwxpGPnz7a_2.jpg exists
[ 28/265] cleidir.fit_/cleidir.fit_ - Bnr8nNSnezS.jpg exists
[ 29/265] cleidir.fit_/cleidir.fit_ - Bngj8d9nhw7.jpg exists
[ 30/265] cleidir.fit_/cleidir.fit_ - BnNE2xjH4rb_1.jpg exists cleidir.fit_/cleidir.fit_ - BnNE2xjH4rb_2.jpg exists
[ 31/265] cleidir.fit_/cleidir.fit_ - BmzZk8kHL2l.jpg exists cleidir.fit_/cleidir.fit_ - BmzZk8kHL2l.mp4 exists
[ 32/265] cleidir.fit_/cleidir.fit_ - Bmo5AKjArs-_1.jpg exists cleidir.fit_/cleidir.fit_ - Bmo5AKjArs-_2.jpg exists
[ 33/265] cleidir.fit_/cleidir.fit_ - BmV74OAn0Pf.jpg exists
[ 34/265] cleidir.fit_/cleidir.fit_ - BlgLqxSniBO.jpg exists
[ 35/265] cleidir.fit_/cleidir.fit_ - Bk-Y1u0HR9n.jpg exists
[ 36/265] cleidir.fit_/cleidir.fit_ - BkIhEaNn8su.jpg exists
[ 37/265] cleidir.fit_/cleidir.fit_ - Biuf1Z0nh-7.jpg exists
[ 38/265] cleidir.fit_/cleidir.fit_ - BisPZRDns9x.jpg exists
[ 39/265] cleidir.fit_/cleidir.fit_ - BiaBqmpnRl4.jpg exists
[ 40/265] cleidir.fit_/cleidir.fit_ - BiQQSXzHbyH.jpg exists cleidir.fit_/cleidir.fit_ - BiQQSXzHbyH.mp4 exists
[ 41/265] cleidir.fit_/cleidir.fit_ - BhSLVGFFYjL.jpg exists
[ 42/265] cleidir.fit_/cleidir.fit_ - Bg6d1msHP6k.jpg exists
[ 43/265] cleidir.fit_/cleidir.fit_ - Bf33vWbgYzw_1.jpg exists cleidir.fit_/cleidir.fit_ - Bf33vWbgYzw_2.jpg exists cleidir.fit_/cleidir.fit_ - Bf33vWbgYzw_2.mp4 exists
[ 44/265] cleidir.fit_/cleidir.fit_ - BfZk1gtAUGD_1.jpg exists cleidir.fit_/cleidir.fit_ - BfZk1gtAUGD_1.mp4 exists cleidir.fit_/cleidir.fit_ - BfZk1gtAUGD_2.jpg exists cleidir.fit_/cleidir.fit_ - BfZk1gtAUGD_2.mp4 exists
[ 45/265] cleidir.fit_/cleidir.fit_ - BfZjholAP0a_1.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_2.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_3.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_4.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_5.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_6.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_7.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_8.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_9.jpg exists cleidir.fit_/cleidir.fit_ - BfZjholAP0a_10.jpg exists
[ 46/265] cleidir.fit_/cleidir.fit_ - BfTscv-AQOh_1.jpg exists cleidir.fit_/cleidir.fit_ - BfTscv-AQOh_2.jpg exists cleidir.fit_/cleidir.fit_ - BfTscv-AQOh_3.jpg exists cleidir.fit_/cleidir.fit_ - BfTscv-AQOh_4.jpg exists cleidir.fit_/cleidir.fit_ - BfTscv-AQOh_5.jpg exists cleidir.fit_/cleidir.fit_ - BfTscv-AQOh_6.jpg exists
[ 47/265] cleidir.fit_/cleidir.fit_ - BfR9B3eg9vJ_1.jpg exists cleidir.fit_/cleidir.fit_ - BfR9B3eg9vJ_2.jpg exists cleidir.fit_/cleidir.fit_ - BfR9B3eg9vJ_3.jpg exists cleidir.fit_/cleidir.fit_ - BfR9B3eg9vJ_4.jpg exists cleidir.fit_/cleidir.fit_ - BfR9B3eg9vJ_5.jpg exists cleidir.fit_/cleidir.fit_ - BfR9B3eg9vJ_6.jpg exists
[ 48/265] cleidir.fit_/cleidir.fit_ - BfQcCIWgVdq_1.jpg exists cleidir.fit_/cleidir.fit_ - BfQcCIWgVdq_2.jpg exists cleidir.fit_/cleidir.fit_ - BfQcCIWgVdq_2.mp4 exists
[ 49/265] cleidir.fit_/cleidir.fit_ - BfQb4cSAq-j.jpg exists
HTTP redirect from https://www.instagram.com/p/BfQb4cSAq-j/ to https://www.instagram.com/p/BfQcCIWgVdq
Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 147, in _field
    d = d[key]
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\Scripts\instaloader-script.py", line 10, in <module>
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 184, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 940, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 423, in download_post
    downloaded &= self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 265, in video_url
    return self._field('video_url')
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 152, in _field
    d = d[key]
KeyError: 'video_url'
```

Changing the filename pattern to date:
```
$ instaloader --dirname-pattern={profile} --filename-pattern="{profile} - {date_utc}" --max-connection-attempts=0 --no-captions --no-metadata-json cleidir.fit_
cleidir.fit_/2018-10-23_18-52-25_UTC_profile_pic.jpg already exists
Retrieving posts from profile cleidir.fit_.
[  1/265] cleidir.fit_/cleidir.fit_ - 2019-01-12_16-27-59.jpg
[  2/265] cleidir.fit_/cleidir.fit_ - 2019-01-05_03-20-28.jpg
[  3/265] cleidir.fit_/cleidir.fit_ - 2019-01-03_23-56-28_1.jpg cleidir.fit_/cleidir.fit_ - 2019-01-03_23-56-28_2.jpg cleidir.fit_/cleidir.fit_ - 2019-01-03_23-56-28_3.jpg
[  4/265] cleidir.fit_/cleidir.fit_ - 2019-01-01_20-34-40.jpg
[  5/265] cleidir.fit_/cleidir.fit_ - 2018-12-31_23-55-33.jpg
[  6/265] cleidir.fit_/cleidir.fit_ - 2018-12-30_22-36-31.jpg
[  7/265] cleidir.fit_/cleidir.fit_ - 2018-12-30_17-57-00_1.jpg cleidir.fit_/cleidir.fit_ - 2018-12-30_17-57-00_2.jpg cleidir.fit_/cleidir.fit_ - 2018-12-30_17-57-00_3.jpg cleidir.fit_/cleidir.fit_ - 2018-12-30_17-57-00_4.jpg cleidir.fit_/cleidir.fit_ - 2018-12-30_17-57-00_5.jpg
[  8/265] cleidir.fit_/cleidir.fit_ - 2018-12-29_21-23-55_1.jpg cleidir.fit_/cleidir.fit_ - 2018-12-29_21-23-55_2.jpg cleidir.fit_/cleidir.fit_ - 2018-12-29_21-23-55_2.mp4
[  9/265] cleidir.fit_/cleidir.fit_ - 2018-12-27_16-45-53.jpg
[ 10/265] cleidir.fit_/cleidir.fit_ - 2018-12-25_01-22-16_1.jpg cleidir.fit_/cleidir.fit_ - 2018-12-25_01-22-16_2.jpg cleidir.fit_/cleidir.fit_ - 2018-12-25_01-22-16_3.jpg
[ 11/265] cleidir.fit_/cleidir.fit_ - 2018-12-23_17-35-17.jpg
[ 12/265] cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_1.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_2.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_3.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_4.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_5.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_6.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_7.jpg cleidir.fit_/cleidir.fit_ - 2018-12-22_17-03-22_8.jpg
[ 13/265] cleidir.fit_/cleidir.fit_ - 2018-12-21_15-57-27_1.jpg cleidir.fit_/cleidir.fit_ - 2018-12-21_15-57-27_2.jpg cleidir.fit_/cleidir.fit_ - 2018-12-21_15-57-27_3.jpg
[ 14/265] cleidir.fit_/cleidir.fit_ - 2018-12-20_18-53-55_1.jpg cleidir.fit_/cleidir.fit_ - 2018-12-20_18-53-55_2.jpg cleidir.fit_/cleidir.fit_ - 2018-12-20_18-53-55_3.jpg
[ 15/265] cleidir.fit_/cleidir.fit_ - 2018-12-09_18-01-21.jpg
[ 16/265] cleidir.fit_/cleidir.fit_ - 2018-12-08_16-54-15.jpg
[ 17/265] cleidir.fit_/cleidir.fit_ - 2018-12-07_23-31-17.jpg
[ 18/265] cleidir.fit_/cleidir.fit_ - 2018-11-30_23-41-48.jpg
[ 19/265] cleidir.fit_/cleidir.fit_ - 2018-11-25_17-03-38_1.jpg cleidir.fit_/cleidir.fit_ - 2018-11-25_17-03-38_2.jpg cleidir.fit_/cleidir.fit_ - 2018-11-25_17-03-38_2.mp4
[ 20/265] cleidir.fit_/cleidir.fit_ - 2018-11-10_17-16-11.jpg
[ 21/265] cleidir.fit_/cleidir.fit_ - 2018-11-09_23-48-12.jpg
[ 22/265] cleidir.fit_/cleidir.fit_ - 2018-11-02_23-41-39.jpg
[ 23/265] cleidir.fit_/cleidir.fit_ - 2018-10-26_00-17-04_1.jpg cleidir.fit_/cleidir.fit_ - 2018-10-26_00-17-04_2.jpg cleidir.fit_/cleidir.fit_ - 2018-10-26_00-17-04_3.jpg cleidir.fit_/cleidir.fit_ - 2018-10-26_00-17-04_4.jpg
[ 24/265] cleidir.fit_/cleidir.fit_ - 2018-10-13_18-46-47_1.jpg cleidir.fit_/cleidir.fit_ - 2018-10-13_18-46-47_2.jpg cleidir.fit_/cleidir.fit_ - 2018-10-13_18-46-47_3.jpg cleidir.fit_/cleidir.fit_ - 2018-10-13_18-46-47_4.jpg
[ 25/265] cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_1.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_2.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_3.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_4.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_5.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_6.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_7.jpg cleidir.fit_/cleidir.fit_ - 2018-10-12_19-18-15_8.jpg
[ 26/265] cleidir.fit_/cleidir.fit_ - 2018-09-22_15-15-55.jpg
[ 27/265] cleidir.fit_/cleidir.fit_ - 2018-09-15_21-37-56_1.jpg cleidir.fit_/cleidir.fit_ - 2018-09-15_21-37-56_2.jpg
[ 28/265] cleidir.fit_/cleidir.fit_ - 2018-09-14_00-37-36.jpg
[ 29/265] cleidir.fit_/cleidir.fit_ - 2018-09-09_14-30-24.jpg
[ 30/265] cleidir.fit_/cleidir.fit_ - 2018-09-02_00-53-10_1.jpg cleidir.fit_/cleidir.fit_ - 2018-09-02_00-53-10_2.jpg
[ 31/265] cleidir.fit_/cleidir.fit_ - 2018-08-23_02-05-26.jpg cleidir.fit_/cleidir.fit_ - 2018-08-23_02-05-26.mp4
[ 32/265] cleidir.fit_/cleidir.fit_ - 2018-08-18_23-36-56_1.jpg cleidir.fit_/cleidir.fit_ - 2018-08-18_23-36-56_2.jpg
[ 33/265] cleidir.fit_/cleidir.fit_ - 2018-08-11_14-56-30.jpg
[ 34/265] cleidir.fit_/cleidir.fit_ - 2018-07-21_17-55-29.jpg
[ 35/265] cleidir.fit_/cleidir.fit_ - 2018-07-08_14-56-24.jpg
[ 36/265] cleidir.fit_/cleidir.fit_ - 2018-06-17_16-49-19.jpg
[ 37/265] cleidir.fit_/cleidir.fit_ - 2018-05-13_17-46-53.jpg
[ 38/265] cleidir.fit_/cleidir.fit_ - 2018-05-12_20-44-45.jpg
[ 39/265] cleidir.fit_/cleidir.fit_ - 2018-05-05_18-58-27.jpg
[ 40/265] cleidir.fit_/cleidir.fit_ - 2018-05-02_00-05-30.jpg cleidir.fit_/cleidir.fit_ - 2018-05-02_00-05-30.mp4
[ 41/265] cleidir.fit_/cleidir.fit_ - 2018-04-07_21-17-35.jpg
[ 42/265] cleidir.fit_/cleidir.fit_ - 2018-03-29_16-17-32.jpg
[ 43/265] cleidir.fit_/cleidir.fit_ - 2018-03-03_19-34-45_1.jpg cleidir.fit_/cleidir.fit_ - 2018-03-03_19-34-45_2.jpg cleidir.fit_/cleidir.fit_ - 2018-03-03_19-34-45_2.mp4
[ 44/265] cleidir.fit_/cleidir.fit_ - 2018-02-20_01-12-21_1.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-12-21_1.mp4 cleidir.fit_/cleidir.fit_ - 2018-02-20_01-12-21_2.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-12-21_2.mp4
[ 45/265] cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_1.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_2.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_3.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_4.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_5.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_6.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_7.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_8.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_9.jpg cleidir.fit_/cleidir.fit_ - 2018-02-20_01-00-54_10.jpg
[ 46/265] cleidir.fit_/cleidir.fit_ - 2018-02-17_18-23-26_1.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_18-23-26_2.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_18-23-26_3.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_18-23-26_4.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_18-23-26_5.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_18-23-26_6.jpg
[ 47/265] cleidir.fit_/cleidir.fit_ - 2018-02-17_02-09-50_1.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_02-09-50_2.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_02-09-50_3.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_02-09-50_4.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_02-09-50_5.jpg cleidir.fit_/cleidir.fit_ - 2018-02-17_02-09-50_6.jpg
[ 48/265] cleidir.fit_/cleidir.fit_ - 2018-02-16_12-02-16_1.jpg cleidir.fit_/cleidir.fit_ - 2018-02-16_12-02-16_2.jpg cleidir.fit_/cleidir.fit_ - 2018-02-16_12-02-16_2.mp4
[ 49/265] cleidir.fit_/cleidir.fit_ - 2018-02-16_12-00-57.jpg
HTTP redirect from https://www.instagram.com/p/BfQb4cSAq-j/ to https://www.instagram.com/p/BfQcCIWgVdq
Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 147, in _field
    d = d[key]
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\Scripts\instaloader-script.py", line 10, in <module>
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\__main__.py", line 184, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 940, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\instaloader.py", line 423, in download_post
    downloaded &= self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local)
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 265, in video_url
    return self._field('video_url')
  File "C:\Users\hgk maxymus\AppData\Local\Programs\Python\Python35-32\lib\site-packages\instaloader\structures.py", line 152, in _field
    d = d[key]
KeyError: 'video_url'
```

Forcing the download of the single post (49th):
```
$ instaloader --dirname-pattern={profile} --filename-pattern="{profile} - {shortcode}" --max-connection-attempts=0 --no-captions --no-metadata-json -- -BfQb4cSAq-j

HTTP redirect from https://www.instagram.com/p/BfQb4cSAq-j/ to https://www.instagram.com/p/BfQcCIWgVdq
cleidir.fit_/cleidir.fit_ - BfQcCIWgVdq_1.jpg exists cleidir.fit_/cleidir.fit_ - BfQcCIWgVdq_2.jpg exists cleidir.fit_/cleidir.fit_ - BfQcCIWgVdq_2.mp4 exists
```

Forcing the download of the single post right after (50th):
```
$ instaloader --dirname-pattern={profile} --filename-pattern="{profile} - {shortcode}" --max-connection-attempts=0 --no-captions --no-metadata-json -- -BfMWNevAI4q
cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_1.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_2.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_3.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_4.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_5.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_6.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_7.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_8.jpg cleidir.fit_/cleidir.fit_ - BfMWNevAI4q_9.jpg
```

---

About the python and spaces, I thought you could add the quotes even though I know the issue is with pip/python 😜.

Either way, thanks! :)
