### ISSUE TITLE
Unable download Highlights and IGTV with the KeyError "edge_felix_video_timeline"

### ISSUE THREAD

**Issue by arthur-lim** [instaloader/instaloader#2285]
**Describe the bug**
Unable to download highlights and IGTV with the error

**To Reproduce**
Running the command `instaloader username --highlights --igtv --load-cookies=firefox`

**Expected behavior**
Able to download Highlights and IGTV of that profile

**Error messages and tracebacks**

```
Retrieving IGTV videos for profile wanna._b.
Traceback (most recent call last):
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\structures.py", line 969, in _metadata
    d = d[key]
KeyError: 'edge_felix_video_timeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\__main__.py", line 541, in main
    _main(loader,
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\__main__.py", line 283, in _main
    instaloader.download_profiles(profiles,
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\instaloader.py", line 1478, in download_profiles
    self.download_igtv(profile, fast_update=fast_update, post_filter=post_filter,
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\instaloader.py", line 1292, in download_igtv
    igtv_posts = profile.get_igtv_posts()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\structures.py", line 1232, in get_igtv_posts
    self._metadata('edge_felix_video_timeline'),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARTHUR\AppData\Roaming\Python\Python312\site-packages\instaloader\structures.py", line 975, in _metadata
    d = d[key]
        ~^^^^^
KeyError: 'edge_felix_video_timeline'
```

**Instaloader version**
4.11

**Comment by ekalin** [comment]
Does IGTV even exist yet? I do not see that tab anymore in that profile (or in any other).

There are reels, which sometimes appear in the profile and sometimes not. Is that what you mean?

For the record, downloading of reels has been requested, but is not implemented yet: #812

**Comment by arthur-lim** [comment]
Roger that
But I got the same error message while trying to download highlights

**Comment by jpfleischer** [comment]
how do i know which metadata pertains to igtv? i cannot put print statements for debugging because i dont know which variable stores the response from IG
