### ISSUE TITLE
Can only scrape 12 or so posts (first page?) before JSON Query to graphql/query 401 error

### ISSUE THREAD

**Issue by billbeans** [instaloader/instaloader#2307]
**Describe the bug**
This tool stopped working completely for me a couple weeks ago, but since the last update it kind of works again, only it fails consistently around 12 or so posts. I even signed in and it still failed with the api check error.

**To Reproduce**
instaloader [any profile]

**Expected behavior**
To be able to scrape profiles.

**Error messages and tracebacks**
`JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing`

*When waiting a few minutes and trying again, it always fails*

**Instaloader version**
4.12

**Additional context**
I use a VPN which I know can mess things up, but before I was eventually able to scrape public profiles if I switched IPs enough. gallery-dl isn't working for me either, so I think there may have been another api change. I don't have "residential" proxies to test on, only "datacenter", so they may only block those now, but probably not if it lets me get 12 posts in? I'm also using Linux which judging from previous bug reports seemed to have less functionality

**Comment by spindelbotten** [comment]
I've had the same issue since two days ago. About four days ago I could scrape over 1k posts successfully and now it's just 12 no matter if I change locations with my VPN or use my regular IP address. I've waited over 6, 12 and 24 hours between attempts and results are still the same error as above.

**Comment by LoicBERGER** [comment]
same here, i scrapped a lot ... and can't find a solution

**Comment by J3-strip** [comment]
same here! even went down a dedicated Ip route. same problem.

**Comment by Tg00174** [comment]
same problem

**Comment by markshi9008** [comment]
same problem

**Comment by edisx** [comment]
same problem

**Comment by AyoDev** [comment]
same problem

**Comment by gueruex** [comment]
I am also running into the same problem. Seems like Instagram is going crazy with their rate limiting if they detect any automated behavior.

**Comment by LoicBERGER** [comment]
on my side pictures are downloading, but at some points it stopped with this :  

 "File "C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py", line 459, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=......"

**Comment by androslee** [comment]
i'm not sure the best way to get it added to the CLI, but i was able to get the code working again.  i just manually added a HUGE sleep to the download.  it appears instagram has a huge, huge rate limiter built in.  when i just set my waittime to be a random number, around 20 minutes, i was able to get all posts.  even from accounts with 2600 posts.  yes it took a few days.

instaloader/instaloadercontext.py
    class RateController
        def wait_before_query
            waittime =   random.randint(1050, 1150)

put a little random in there, just so each call varies a little bit.

i don't think the CLI for --rate-limit works.  so i just hard coded this into my RateController directly.

though i'm running into another issue, which i think is unrelated.  on some accounts, instaloader stops early and does not get the last 60 posts.  i think it's a different issue.

**Comment by iamdanielwejs** [comment]
Same here.

**Comment by iamdanielwejs** [comment]
same problem here.

**Comment by DonBaronFactory** [comment]
Same here, 12 is the limit

**Comment by IamEdHardy** [comment]
same problem

**Comment by androslee** [comment]
i think something must have changed with instagram's api/response.  i was getting full accounts last week.  but yes, now mine is stopping after 12.  

i'm not getting any errors, but mine just stops.

i wasnt saving any logs/json responses before, but i did just now.  i found out a few things:

- it looks like the only API that was working/responding without a login, was the "iphone_json" response
- graphql just comes up empty.  or at least this tool forms a nonworking url
- in the iphone json response, i don't think it gets all of the posts of a user, and at the bottom it says "next page: false".  so it just ends.

**Comment by Koenvanvlijmen** [comment]
> i'm not sure the best way to get it added to the CLI, but i was able to get the code working again. i just manually added a HUGE sleep to the download. it appears instagram has a huge, huge rate limiter built in. when i just set my waittime to be a random number, around 20 minutes, i was able to get all posts. even from accounts with 2600 posts. yes it took a few days.
> 
> instaloader/instaloadercontext.py class RateController def wait_before_query waittime = random.randint(1050, 1150)
> 
> put a little random in there, just so each call varies a little bit.
> 
> i don't think the CLI for --rate-limit works. so i just hard coded this into my RateController directly.


@androslee  This does not seem to work for me.  Is that the only thing that you changed? And does it still work for you?

**Comment by phuongcanopylab** [comment]
same here, I can only iterate and write out 12 posts from get_posts(). no error thrown out tho, it just stopped writing and exit the loop.

**Comment by drumstick90** [comment]
same here - 12 posts the i get the error

**Comment by eminaatnexro** [comment]
Hello,
Experiencing the same issue here. Was able to scrape all posts for one user a couple of weeks ago.
Instaloader CLI now just downloads the 12 latest posts and quit (no errors). Logging in does not help.

**Comment by achyu-dev** [comment]
having same issue

**Comment by estatistics** [comment]
same here just 10 stories or no stories at all.

**Comment by sgtpepperaut** [comment]
same issue

**Comment by estatistics** [comment]
It appears that 2.13 latest build fixed that problem.

**Comment by yonas** [comment]
@estatistics 4.13?

**Comment by estatistics** [comment]
> @estatistics 4.13?

yes, sorry

**Comment by yonas** [comment]
Works for me as well :partying_face:

**Comment by drumstick90** [comment]
I still get the same error in google colab 

My code:

```

import instaloader
L = instaloader.Instaloader()
posts = instaloader.Profile.from_username(L.context, "_target_").get_posts()
for post in posts:
    L.download_post(post, "_target_")
```
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]

**Comment by achyu-dev** [comment]
@drumstick90  I am facing the same issue

**Comment by drumstick90** [comment]
Works when launched from ipynb in visual studio code !

**Comment by Licomix** [comment]
It's works on local machine fine. But not at hosting 
`JSON Query to graphql/query: 401 Unauthorized - "fail" status, message `

**Comment by PastaAdventures** [comment]
seems its still happening wit 4.13

**Comment by ekalin** [comment]
If you're talking about the 401 error (like in the first post), especially when not logged in, that's caused by Instagram. They strongly limit anonymous scraping, and you'll probably see that even with a browser you cannot see more than the first 12 posts - and sometimes nothing at all.

If that's not the case (you're logged in, or it downloads 12 and stops with no error, etc) then please describe the problem clearly.

**Comment by PastaAdventures** [comment]
even while logged in i get only 12
`import instaloader
L = instaloader.Instaloader()
L.load_session_from_file("Username", "Path to file")
posts = instaloader.Profile.from_username(L.context, "target").get_posts()
for post in posts:
    L.download_post(post, "target")`

**Comment by ekalin** [comment]
And what happens after the 12 posts? A 401 error?

**Comment by PastaAdventures** [comment]
no error, script just exits after 12 posts

**Comment by PastaAdventures** [comment]
yeah exact same behaviour on cli, which is why I attempted module

**Comment by florian5392** [comment]
> Same problem here.
> 
> After a lot of reading and trying different solutions with no success, I temporarily solved my problem by deleting the Instaloader login cookie, downloading posts without the --login CLI parameter, and using a VPN. Every 2,000 to 3,000 requests, I rotate my IP address and location. I feel like a hacker!
> 
> In other words, I'm trying to hide my identity as much as possible and change my location frequently. It seems to me that it's not an API limit issue, but rather a limit on requests per IP.
> 
> I also modified the [Instaloader.do_sleep() function](https://instaloader.github.io/module/instaloadercontext.html#instaloader.InstaloaderContext.do_sleep):
> 
> in file instaloadercontext.py line 364 (v4.13.1):
> 
> From:
> 
> ```python
> def do_sleep(self):
>   """Sleep a short time if self.sleep is set. Called before each request to instagram.com."""
>   if self.sleep:
>       time.sleep(min(random.expovariate(0.6), 15.0))
> ```
> 
> To:
> 
> ```python
> def do_sleep(self):
>   """Sleep a short time if self.sleep is set. Called before each request to instagram.com."""
>   if self.sleep:
>       time.sleep(min(random.expovariate(0.2), 15.0))
> ```
> 
> This change slightly increases the random sleep time between each request. I'm considering increasing the waiting time between requests even more to avoid issues.
> 
> For me, and by now, this seems to work.

Unfortunately, the vpn and the updated do_sleep function didn't help in my case.

**Comment by Allen-Kwan** [comment]
> Same problem here.
> 
> After a lot of reading and trying different solutions with no success, I temporarily solved my problem by deleting the Instaloader login cookie, downloading posts without the --login CLI parameter, and using a VPN. Every 2,000 to 3,000 requests, I rotate my IP address and location. I feel like a hacker!
> 
> In other words, I'm trying to hide my identity as much as possible and change my location frequently. It seems to me that it's not an API limit issue, but rather a limit on requests per IP.
> 
> I also modified the [Instaloader.do_sleep() function](https://instaloader.github.io/module/instaloadercontext.html#instaloader.InstaloaderContext.do_sleep):
> 
> in file instaloadercontext.py line 364 (v4.13.1):
> 
> From:
> 
> ```python
> def do_sleep(self):
>   """Sleep a short time if self.sleep is set. Called before each request to instagram.com."""
>   if self.sleep:
>       time.sleep(min(random.expovariate(0.6), 15.0))
> ```
> 
> To:
> 
> ```python
> def do_sleep(self):
>   """Sleep a short time if self.sleep is set. Called before each request to instagram.com."""
>   if self.sleep:
>       time.sleep(min(random.expovariate(0.2), 15.0))
> ```
> 
> This change slightly increases the random sleep time between each request. I'm considering increasing the waiting time between requests even more to avoid issues.
> 
> For me, and by now, this seems to work.

Total newb here, but can you activate the sleep timer/function via the command line arguments?

**Comment by Allen-Kwan** [comment]
> There's not command line argument to modify sleep time between requests.

Ah I see, I have to edit the code and compile my own version to add sleep functionality?

**Comment by AdriaPadilla** [comment]
> > There's not command line argument to modify sleep time between requests.
> 
> Ah I see, I have to edit the code and compile my own version to add sleep functionality?

To increase the sleep time between each request, you need to modify the do_sleep(self) function found on line 364 of the instaloadercontext.py file, which is located in the folder where the Python packages are installed on your computer, or in the corresponding location in your virtual environment (if you are using one). There's no need to compile.

**Comment by mr-akashjain** [comment]
Same error, i deleted old cookies and logged in again and was able to download 12 more. This method is also not working again
any fix??

**Comment by AdriaPadilla** [comment]
I’ve been testing possible solutions, and for now, all I have are temporary patches that allow me to keep downloading data. However, if I’m not careful, sooner or later the 401 error reappears, even without necessarily reaching the API request limit (error 429).

Here’s some information I’ve gathered:

- This is an Instagram issue: it seems to be able to detect automated activity. I assume several factors are taken into account for this detection. 
- Using a VPN doesn’t solve the issue. It seems IG has blocked the IPs of the main nodes of the most popular VPNs. The 401 error appears sooner when using a VPN compared to my home connection, where I seem to be able to make more requests without hitting the error.
- The error appears, sooner or later, both when using the `--login` option in the CLI and during anonymous data extractions. I can confirm that using `--login` delays the error. However, there’s a risk of blocking the account from which the extraction is being made, as mentioned in previous comments. In fact, when accessing IG via browser, a "suspicious activity" alert pops up, warning that something is going on.
- It seems IG identifies the public IP from which the request is made and eventually blocks access from any device connected to that public IP. I’ve experienced this temporary block to any device connected to my home Wi-Fi.

As I mentioned at the beginning, the error keeps appearing from time to time, and I haven’t managed to find a solution. I’m a complete novice at coding, and some parts of Instaloader’s core I don’t fully understand, nor are they documented. However, I’ve made a few tweaks that allow me to manage the issue.

I’ve increased the wait time between requests, setting a minimum wait time of 5 seconds between requests:

```python
def do_sleep(self):
    """Sleep a short time if self.sleep is set. Called before each request to instagram.com."""
    if self.sleep:
        sleep_time = min(random.expovariate(0.10), 25.0)
        if sleep_time < 5:  # minimum time to sleep
            pass
        else:
            print(f"Sleeping for: {sleep_time}")
            time.sleep(sleep_time)
```
I’ve created a list of different user agents to rotate between them across requests. The goal is to make the requests a bit more random:

```python

def default_user_agent() -> str:
    user_agents = ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.3',
                   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.',
                   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.3']
    agent = random.choice(user_agents)
    print(f"User agent for query: {agent}")
    return agent
```
These are just some ideas, and I’m not sure if they’re having a real effect on the issue, but they’re allowing me to make requests, even if it means waiting longer.

Do you have any other ideas?

**Comment by yarodevuci** [comment]
have anyone tried to throttle download speed to see if that helps to keep the session active?

**Comment by achyu-dev** [comment]
@yarodevuci  I have tried but still it does not work sadly

**Comment by AdriaPadilla** [comment]
> have anyone tried to throttle download speed to see if that helps to keep the session active?

> @yarodevuci I have tried but still it does not work sadly

After two months, I can say that, in my case, the situation hasn’t changed, and I still don’t have a solution to this problem. I download a large amount of data using Instaloader for academic purposes, and it’s been a nightmare to extract all the information.

I’ve tried everything—going faster, slower, more random—but nothing works. Sooner or later, the 401 error pops up. If you keep trying, your account eventually gets blocked. It’s pretty clear that Instagram/Meta has gotten better at detecting scraping.

Since I haven’t found a solution, Instaloader has become useless for me, and I’ve stopped using it. I’m not really sure how others are managing, but I don’t think my problem is unique. I imagine that if you download a certain amount of data, you’ll run into the same issue eventually.

If anyone has more info, it would be great to share. Cheers.

**Comment by achyu-dev** [comment]
yes, I agree, I think we just need to realize the fact that Instagram / Meta has gotten strict with their policies. 

I think its safe to close this issue and its just been stale and no solution has been found till now

**Comment by yarodevuci** [comment]
yep same exact here, i tried also posting random comments. follow / unfollow people, basically acting as human but still getting 401 error eventually

**Comment by JanGeorge06** [comment]
Hey guys, any solution found?

I'm iterating over 7 pages to get the latest post for the day, it was working last week perfectly, but now from the first page the error appears

 'JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]'

Any solution?

**Comment by yarodevuci** [comment]
> Hey guys, any solution found?
> 
> I'm iterating over 7 pages to get the latest post for the day, it was working last week perfectly, but now from the first page the error appears
> 
> 'JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]'
> 
> Any solution?

nope

**Comment by JanGeorge06** [comment]
Hey guys,
I tried running the same script in a new Python file and it worked, so try refreshing everything and creating a new Py file and run the script again.

**Comment by JanGeorge06** [comment]
> Hey guys, I tried running the same script in a new Python file and it worked, so try refreshing everything and creating a new Py file and run the script again.

Error appeared again and Instagram flagged the account, are there any scraping techniques to prevent this issue? (Other than Instaloader or normal scraping)

**Comment by JanGeorge06** [comment]
> > Hey guys, I tried running the same script in a new Python file and it worked, so try refreshing everything and creating a new Py file and run the script again.
> 
> When I read your post, I thought, "It won't last long."
> 
> Immediately after:
> 
> > Error appeared again and Instagram flagged the account, are there any scraping techniques to prevent this issue? (Other than Instaloader or normal scraping)
> 
> Ahahaha.
> 
> For anyone stumbling upon this post looking for a solution or thinking they've found a way to fix the issue, let me save you the trouble: it’s not possible. Sooner or later, Instagram will block your account again. Instagram and Meta have deployed advanced systems to detect suspicious activity, and as of now, there’s no way to get around this.

Hahaha, I know these solutions won’t be reliable and I’m sure Instagram will block everything, but for now the script is inconsistent (sometimes works, sometimes not) even raw scraping is automation and suspicious activity, so if someone has ideas for scraping IG in a safe way paste it down here and what would be the solution if a certain application gets its data from IG posts?

**Comment by yarodevuci** [comment]
i tried download speed < 500kb/s, i tried leaving follow/unfollow footprint, leaving comments and stuff like that, still getting flagged, now my browser Firefox not even loading insta, i have to do it from device, basically they blocked browser login now...

**Comment by JanGeorge06** [comment]
Same chrome is not loading IG…script sometimes works sometimes not. 

> i tried download speed < 500kb/s, i tried leaving follow/unfollow footprint, leaving comments and stuff like that, still getting flagged, now my browser Firefox not even loading insta, i have to do it from device, basically they blocked browser login now...

**Comment by AdriaPadilla** [comment]
> Same chrome is not loading IG…script sometimes works sometimes not.
> 
> > i tried download speed < 500kb/s, i tried leaving follow/unfollow footprint, leaving comments and stuff like that, still getting flagged, now my browser Firefox not even loading insta, i have to do it from device, basically they blocked browser login now...

Check if you can access Instagram on your phone while connected to your PC's network/wifi. If you can't, it’s likely a public IP ban. If you can, the issue might be related to your browser, fingerprinting, cookies, or MAC address.

**Comment by JanGeorge06** [comment]
> i tried download speed < 500kb/s, i tried leaving follow/unfollow footprint, leaving comments and stuff like that, still getting flagged, now my browser Firefox not even loading insta, i have to do it from device, basically they blocked browser login now...

I don’t care about browsing tbh, just need the script to work normally. So if anyone finds a workaround or a solution to IG scraping just post it here guys and keep it updated.

**Comment by AdriaPadilla** [comment]
> I don’t care about browsing tbh, just need the script to work normally. So if anyone finds a workaround or a solution to IG scraping just post it here guys and keep it updated.

I can understand this is frustrating, but there's no solution. 

The only alternative tool I know, by now: https://github.com/digitalmethodsinitiative/zeeschuimer

**Comment by quietsecret123** [comment]
@yarodevuci and @JanGeorge06 If you can't load IG on your browser, you'll need to type instagram.com/challenge/ and you'll be able to acknowledge the scraping warning.

**Comment by quietsecret123** [comment]
> I found an alternative for scraping Instagram which is **Apify**. Go to this [link](https://console.apify.com/actors/nH2AHrwxeTRJoN5hX/input) and play with the tool for a bit until you understand it. If it fit your needs go to the integrations part and choose API client.

> And go on to Python and scrape Instagram, I only need post captions from several posts to do some AI on it, so this tool works for me!

Thanks for sharing this. Unfortunately, I need something that saves IG stories, which Apify can't do. I'm also still learning how to use Python, so it will be a while for me to use Instaloader.

**Comment by stefanel96** [comment]
Hello everyone,
I'd like to ask the team if they are working on a fix for this issue (advanced scraping detection from Meta) and is there a chance to avoid this or it is what it is?

Regards

**Comment by AdriaPadilla** [comment]
> Hello everyone, I'd like to ask the team if they are working on a fix for this issue (advanced scraping detection from Meta) and is there a chance to avoid this or it is what it is?
> 
> Regards

I'm not going to solve the problem with my answer, but I want to think about the question you've raised and the challenge we're facing. If Meta has implemented this system, it's clear they don't want us to access data from their platform through methods other than those provided via their Developer page. Creating a workaround for this issue seems highly unlikely, and I foresee that accessing such information will only become more difficult in the future. Platforms are becoming increasingly restrictive.

Right now, the most constructive approach is to advocate for a more open API. Within the European Union, the Digital Services Act is being implemented, which could enforce greater data openness for purposes of scientific and social research—something that directly aligns with my work. 

Attempting to bypass Meta's restrictions or asking the Instaloader developers to invest time in overcoming these blocks feels like engaging in an endless game of cat and mouse, one where we are unlikely to come out ahead.

**Comment by stefanel96** [comment]
> > Hello everyone, I'd like to ask the team if they are working on a fix for this issue (advanced scraping detection from Meta) and is there a chance to avoid this or it is what it is?
> > Regards
> 
> I'm not going to solve the problem with my answer, but I want to think about the question you've raised and the challenge we're facing. If Meta has implemented this system, it's clear they don't want us to access data from their platform through methods other than those provided via their Developer page. Creating a workaround for this issue seems highly unlikely, and I foresee that accessing such information will only become more difficult in the future. Platforms are becoming increasingly restrictive.
> 
> Right now, the most constructive approach is to advocate for a more open API. Within the European Union, the Digital Services Act is being implemented, which could enforce greater data openness for purposes of scientific and social research—something that directly aligns with my work.
> 
> Attempting to bypass Meta's restrictions or asking the Instaloader developers to invest time in overcoming these blocks feels like engaging in an endless game of cat and mouse, one where we are unlikely to win.

@AdriaPadilla, I don’t want you to misunderstand me—I’m deeply grateful for everything you do, and I truly admire your work.
I asked this question simply to understand what my next steps should be: whether I should look into other solutions and options or wait for a possible solution from your side, if there is one or if you're working on it.

I’ve noticed that services like Apify and a few others still manage to scrape everything needed (up to 30 posts per minute). However, they likely use a distributed network of computers and other advanced methods, and as far as I know, they can only scrape public profiles, not logged-in accounts (I’m not entirely sure about this since I haven’t explored them in depth). That’s why I thought there might still be hope here.

Once again, I want to say how much I appreciate everything you do. Neither I nor anyone else can say anything against your work, especially considering it’s open-source.

**Comment by david04** [comment]
Just to add that I'm having this issue:
```JSON Query to api/v1/users/web_profile_info/?username=[.......]: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=[.......]```

but only on one computer, with another on the same network (same IP address) I have no issues

It must be something related to the computer info...

**Comment by billbeans** [comment]
The Instagram API is extremely restrictive, and constantly changing. Even with different proxies and signing in, I haven't been able to scrape a profile in ages.

Reading the creator of [Bibliogram's](https://github.com/zydou/bibliogram) blog post about their frustration with the API is very enlightening: https://cadence.moe/blog/2022-09-01-discontinuing-bibliogram

**Comment by hoshython** [comment]
Do you see such message after using instaloader?
https://ibb.co/FRPsfmm

**Comment by atchoo78** [comment]
Hi,

The last couple of days I've received the 401 error that many here are experiencing. 

```python
Retrieving posts from profile EXAMPLEGUY
JSON Query to graphql/query: 
401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22count%22%3A12%2C%22include_relationship_info%22%3Atrue%2C%22latest_besties_reel_media%22%3Atrue%2C%22latest_reel_media%22%3Atrue%7D%2C%22username%22%3A%22EXAMPLEGUY%22%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=123456789&server_timestamps=true
```

Earlier today, I was able to copy that URL and paste it in my browser, and it would load fine. However, when I scraped image and video URLs from the Graphql result page, I had to first convert all the unicode codepoints to UTF-8/HTML entitites chars and URL encode the result. After I replaced every occurence of "\u0026" with "&" and some other similar unicode escapes ("\u0022" = quotation mark, and so on...) I was able to load all the images and video files. 🎆 

However, something did change during this evening, and I suspect Meta has tightened up API security/access restrictions. 

Just to be clear: the error message from Python/Instaloader is still the same as earlier. But if I try to open that URL from the Instaloader error message ("https://www.instagram.com/graphql/query?variables=….") in the browser, it now returns this error message:

```json

{"message":"Please wait a few minutes before you try again.","require_login":true,"igweb_rollout":true,"status":"fail"}
{"errors":[{"message":"execution error","severity":"CRITICAL"}],"status":"ok"}

```

I have absolutely no idea whether those are Instaloader specific error codes or Instagram API/GraphQL. Too much backtracking and I lost count…I'm not in debug mode, and i don't know Instaloader that well yet either. All I know is that it seems kinda stuck right now, and that big red "CRITICAL" wasn't exactly reassuring 😆 

Another thing I noticed is that the initial 401 error from Instaloader is somehow encoded differently than just 4-5 hours ago. As I mentioned, there was LOTS of unicode conversion and URL encoding. Now the URLs are readable in UTF-8 with no unicode or conversion needed. That _might_ be an important clue, but I don't really know for sure.

Allright, good luck. Hope it get sorted out. I like Instaloader so far, despite all this 👍🏼 🎰 

Andreas

**Comment by atchoo78** [comment]
Hi again,


Now I get this error message in the browser if I try to load the URL returned from the 401 Instaloader error:

```json

{"errors":[{"message":"execution error","path":["xdt_api__v1__feed__user_timeline_graphql_connection"],"severity":"CRITICAL"}],"data":null,"extensions":{"is_final":true},"status":"ok"}

```

Andreas

**Comment by bagusa4** [comment]
I have same problem here.

`
(.venv) bagusa4@LAPTOP-A8LJRQQ7:/mnt/l/Workspaces/python/igemotionanalyzer$ /mnt/l/Workspaces/python/igemotionanalyzer/.venv/bin/python /mnt/l/Workspaces/python/igemotionanalyzer/main.py
JSON Query to api/v1/users/web_profile_info/?username=google: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=google [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=google: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=google [retrying; skip with ^C]
Traceback (most recent call last):
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=google

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=google

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=google

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/l/Workspaces/python/igemotionanalyzer/main.py", line 5, in <module>
    profile = instaloader.Profile.from_username(loader.context, user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/structures.py", line 905, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/structures.py", line 973, in _obtain_metadata
    metadata = self._context.get_iphone_json(f'api/v1/users/web_profile_info/?username={self.username}',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 642, in get_iphone_json
    response = self.get_json(path, params, 'i.instagram.com', tempsession, response_headers=response_headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/l/Workspaces/python/igemotionanalyzer/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to api/v1/users/web_profile_info/?username=google: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=google
(.venv) bagusa4@LAPTOP-A8LJRQQ7:/mnt/l/Workspaces/python/igemotionanalyzer$ 

`

**Comment by Rahul-Tawar** [comment]
I don't if Instagram's scraping policies has changed, 
Because I'm getting 401 and 403 error.
