### ISSUE TITLE
Crashed on highlights creating folder of characters not valid to use in name of file/folder

### ISSUE THREAD

**Issue by um-4ir** [instaloader/instaloader#2341]
**Describe the bug**
I try to download highlights then I found a bug their if a highlight's title have characters that are not valid to use in name of file or folder. On that moment it crashed in my case character was question mark *?* 

**To Reproduce**
(e.g. Instaloader --highlights profile)

**Expected behavior**
It create folder of the titles of highlights is good thing but here a thing missing that it should replace that characters with underscore or any other valid character so we will not face process crash 🙏

**Error messages and tracebacks**

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instaloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/__main__.py", line 563, in main
    exit_code = _main(loader,
                ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/__main__.py", line 300, in _main
    instaloader.download_profiles(profiles,
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 1495, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 977, in download_highlights
    self.download_highlight_cover(user_highlight, highlight_target)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 580, in download_highlight_cover
    self.download_title_pic(highlight.cover_url, target, 'cover', highlight.owner_profile)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloader.py", line 548, in download_title_pic
    self.context.write_raw(pic_bytes if pic_bytes else http_response, filename)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/instaloader/instaloadercontext.py", line 664, in write_raw
    with open(filename + '.temp', 'wb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: 'ig_pf/errr?????????/2024-07-03_19-49-20_UTC_cover.jpg.temp'

**Instaloader version**
4.13

**Comment by aandergr** [comment]
PermissionError, not related to Instaloader. Check your file permissions.
