### ISSUE TITLE
High resolution profile pictures sometimes only partially downloaded

### ISSUE THREAD

**Issue by bugfinder5000** [instaloader/instaloader#235]
**Describe the bug**
High resolution profile pictures downloaded by Instaloader 4.2.1 are often only partially downloaded, and sometimes empty files.
I am downloading to a new directory with no previous images or metadata.
I cleared my login session to rule that out too.

**To Reproduce**
Here's the command I use to get just the profile picture of a random account:

    /usr/local/bin/instaloader --login=REDACTED --password=REDACTED --max-connection-attempts 1 --fast-update --profile-pic-only --dirname-pattern="instagram-stories/{target}" REDACTED

Sometimes it works just fine, but one in a while it will only download a partial image.

**Expected behavior**
The profile images should be fully downloaded.

**Error messages and tracebacks**
Full terminal output in event of failed download:

    $ /usr/local/bin/instaloader --login=REDACTED --password=REDACTED --max-connection-attempts 1 --fast-update --profile-pic-only --dirname-pattern="instagram-stories/{target}" REDACTED
    Loaded session from /tmp/.instaloader-REDACTED/session-REDACTED.
    Logged in as REDACTED.
    instagram-stories/REDACTED/2019-01-13_16-08-42_UTC_profile_pic.jpg Traceback (most recent call last):
      File "/usr/lib/python3.6/http/client.py", line 546, in _get_chunk_left
        chunk_left = self._read_next_chunk_size()
      File "/usr/lib/python3.6/http/client.py", line 513, in _read_next_chunk_size
        return int(line, 16)
    ValueError: invalid literal for int() with base 16: b''
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.6/http/client.py", line 578, in _readinto_chunked
        chunk_left = self._get_chunk_left()
      File "/usr/lib/python3.6/http/client.py", line 548, in _get_chunk_left
        raise IncompleteRead(b'')
    http.client.IncompleteRead: IncompleteRead(0 bytes read)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 360, in _error_catcher
        yield
      File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 442, in read
        data = self._fp.read(amt)
      File "/usr/lib/python3.6/http/client.py", line 449, in read
        n = self.readinto(b)
      File "/usr/lib/python3.6/http/client.py", line 483, in readinto
        return self._readinto_chunked(b)
      File "/usr/lib/python3.6/http/client.py", line 594, in _readinto_chunked
        raise IncompleteRead(bytes(b[0:total_bytes]))
    http.client.IncompleteRead: IncompleteRead(9371 bytes read)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/bin/instaloader", line 11, in <module>
        load_entry_point('instaloader==4.2.1', 'console_scripts', 'instaloader')()
      File "/usr/local/lib/python3.6/dist-packages/instaloader/__main__.py", line 412, in main
        storyitem_filter_str=args.storyitem_filter)
      File "/usr/local/lib/python3.6/dist-packages/instaloader/__main__.py", line 186, in _main
        download_stories, fast_update, post_filter, storyitem_filter)
      File "/usr/local/lib/python3.6/dist-packages/instaloader/instaloader.py", line 911, in download_profiles
        self.download_profilepic(profile)
      File "/usr/local/lib/python3.6/dist-packages/instaloader/instaloader.py", line 317, in download_profilepic
        self.context.write_raw(profile_pic_bytes if profile_pic_bytes else profile_pic_response, filename)
      File "/usr/local/lib/python3.6/dist-packages/instaloader/instaloadercontext.py", line 455, in write_raw
        shutil.copyfileobj(resp.raw, file)
      File "/usr/lib/python3.6/shutil.py", line 79, in copyfileobj
        buf = fsrc.read(length)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 459, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 378, in _error_catcher
        raise ProtocolError('Connection broken: %r' % e, e)
    urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(9371 bytes read)', IncompleteRead(9371 bytes read))

**Instaloader version**

    $ /usr/local/bin/instaloader --version
    4.2.1

**Additional context**
It seems very random when it happens. It does not seem to be a problem with my internet connection either.

**Comment by bugfinder5000** [comment]
After getting profile images from 444 profiles, most of them were unfinished (maybe 80-90%).

Running the commands a second time right after, it seems to download them correctly without error. The broken images are overwritten with the new good image.

**Comment by aandergr** [comment]
This is fixed with one of my latest commits, included in 4.2.2; of course unless `--max-connection-attempts=1` is set, which stops Instaloader from retrying after a connection error occurs.

**Comment by bugfinder5000** [comment]
Great work, thanks!
