### ISSUE TITLE
"load--cookies edge" doesn't work on Windows 10

### ISSUE THREAD

**Issue by reln549** [instaloader/instaloader#2351]
The `--load-cookies` function works with Firefox and doesn't work with Edge on Windows 10. I loaded cookies on Edge a few months ago, but it gave me a similar error, then it went away. The same with Opera browser. 
I use the .exe application, latest version 4.13.

The error is the following:

PS C:\Users\Alessandro\Videos\instaloader-v4.13-windows-standalone> .\instaloader --load-cookies edge
Traceback (most recent call last):
  File "__main__.py", line 609, in <module>
  File "__main__.py", line 606, in __main
  File "__main__.py", line 563, in main
  File "__main__.py", line 165, in _main
  File "__main__.py", line 124, in import_session
  File "__main__.py", line 105, in get_cookies_from_instagram
  File "browser_cookie3\__init__.py", line 1195, in edge
  File "browser_cookie3\__init__.py", line 489, in load
  File "browser_cookie3\__init__.py", line 349, in __enter__
  File "browser_cookie3\__init__.py", line 383, in get_connection
  File "browser_cookie3\__init__.py", line 374, in __get_connection_legacy
  File "shutil.py", line 260, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Alessandro\\AppData\\Roaming\\..\\Local\\Microsoft\\Edge\\User Data\\Default\\Network\\Cookies'
[17640] Failed to execute script '__main__' due to unhandled exception!
PS C:\Users\Alessandro\Videos\instaloader-v4.13-windows-standalone>

**Comment by aandergr** [comment]
Looks like an issue with your file permissions.
