### ISSUE TITLE
Crash During Post and Story Download with JSONDecodeError in `simplejson` Module

### ISSUE THREAD

**Issue by sapphirepro** [instaloader/instaloader#2357]
**Describe the bug**
Crash during posts download. Happens same to stories

**To Reproduce**
instagram profile mchaley_nancy fails on post 7

**Instaloader version**
latest

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Data/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/Data/instaloader/instaloader/__main__.py", line 563, in main
    exit_code = _main(loader,
                ^^^^^^^^^^^^^
  File "/Data/instaloader/instaloader/__main__.py", line 300, in _main
    instaloader.download_profiles(profiles,
  File "/Data/instaloader/instaloader/instaloader.py", line 1506, in download_profiles
    self.posts_download_loop(posts_to_download, profile_name, fast_update, post_filter,
  File "/Data/instaloader/instaloader/instaloader.py", line 1076, in posts_download_loop
    downloaded = self.download_post(post, target=target)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Data/instaloader/instaloader/instaloader.py", line 778, in download_post
    self.download_pic(filename=filename, url=post.video_url, mtime=post.date_local))
                                             ^^^^^^^^^^^^^^
  File "/Data/instaloader/instaloader/structures.py", line 574, in video_url
    int(self._context.head(version_url, allow_redirects=True).headers.get('Content-Length', 0)),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Data/instaloader/instaloader/instaloadercontext.py", line 721, in head
    raise ConnectionException(self._response_error(resp))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Data/instaloader/instaloader/instaloadercontext.py", line 375, in _response_error
    resp_json = resp.json()
                ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aandergr** [comment]
We’re unable to reproduce this specific bug on our end. However, users have experienced similar issues with the `simplejson` Python module, which has been known to cause JSON parsing errors. Please refer to [issue #62](https://github.com/instaloader/instaloader/issues/62) for details, and we recommend trying to uninstall `simplejson` to see if that resolves the problem.

If the issue persists, could you please provide a more detailed bug report? It would be helpful if you included:
- Specific steps to reproduce the error
- The exact Instaloader version (not `latest`, as this is neither unique nor easily traceable in the future).
