### ISSUE TITLE
Reopen and Review Issue #2338 – Profile by ID Still Requires Login

### ISSUE THREAD

**Issue by AliZamaniJ** [instaloader/instaloader#2370]
Hello,

I would like to request that issue #2338 be reopened and reviewed.

The problem of obtaining profile information by user ID without logging in still persists, even after the update to remove rhx_gis. The login is still required, and the issue has not been resolved.

You can test it with the following code to verify:

```
import instaloader

L = instaloader.Instaloader()

user_id = 1234567
profile = instaloader.Profile.from_id(L.context, user_id)

print(profile.username)
```

**Comment by ekalin** [comment]
You did not say what the error is, but I'll guess it's a 401 and/or "Redirected to login".

Instagram strongly restricts anonymous access, even in a browser if you try to browse anonymously you'll eventually be limited. There isn't much that can be done.

I guess it's that because I just tried, and was able to fetch a profile anonymously successfully.

If it's a different error, then please post the message.

**Comment by AliZamaniJ** [comment]
You're correct, I'm encountering the same errors. Here is the error message I'm receiving:

```
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=7c16654f22c819fb63d1183034a5162f&variables=%7B%22user_id%22%3A%221234567%22%2C%22include_chaining%22%3Afalse%2C%22include_reel%22%3Atrue%2C%22include_suggested_users%22%3Afalse%2C%22include_logged_out_extras%22%3Afalse%2C%22include_highlight_reels%22%3Afalse%7D [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=7c16654f22c819fb63d1183034a5162f&variables=%7B%22user_id%22%3A%221234567%22%2C%22include_chaining%22%3Afalse%2C%22include_reel%22%3Atrue%2C%22include_suggested_users%22%3Afalse%2C%22include_logged_out_extras%22%3Afalse%2C%22include_highlight_reels%22%3Afalse%7D [retrying; skip with ^C]
Traceback (most recent call last):
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=7c16654f22c819fb63d1183034a5162f&variables=%7B%22user_id%22%3A%221234567%22%2C%22include_chaining%22%3Afalse%2C%22include_reel%22%3Atrue%2C%22include_suggested_users%22%3Afalse%2C%22include_logged_out_extras%22%3Afalse%2C%22include_highlight_reels%22%3Afalse%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=7c16654f22c819fb63d1183034a5162f&variables=%7B%22user_id%22%3A%221234567%22%2C%22include_chaining%22%3Afalse%2C%22include_reel%22%3Atrue%2C%22include_suggested_users%22%3Afalse%2C%22include_logged_out_extras%22%3Afalse%2C%22include_highlight_reels%22%3Afalse%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=7c16654f22c819fb63d1183034a5162f&variables=%7B%22user_id%22%3A%221234567%22%2C%22include_chaining%22%3Afalse%2C%22include_reel%22%3Atrue%2C%22include_suggested_users%22%3Afalse%2C%22include_logged_out_extras%22%3Afalse%2C%22include_highlight_reels%22%3Afalse%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "testlogin2.py", line 6, in <module>
    profile = instaloader.Profile.from_id(L.context, int(user_id))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\instaloader\structures.py", line 905, in from_id
    data = context.graphql_query('7c16654f22c819fb63d1183034a5162f',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=7c16654f22c819fb63d1183034a5162f&variables=%7B%22user_id%22%3A%221234567%22%2C%22include_chaining%22%3Afalse%2C%22include_reel%22%3Atrue%2C%22include_suggested_users%22%3Afalse%2C%22include_logged_out_extras%22%3Afalse%2C%22include_highlight_reels%22%3Afalse%7D

```

**Comment by aandergr** [comment]
There isn’t much Instaloader can do if Instagram enforces login restrictions, which they do even on their official web interface. We can’t work around Instagram’s access limitations. However, we should improve Instaloader’s behavior so that if a profile-by-ID query can’t be performed anonymously, it fails quickly with a clear error message rather than repeatedly attempting the request.
