### ISSUE TITLE
Error with FrozenNodeIterator

### ISSUE THREAD

**Issue by zaitsevid** [instaloader/instaloader#2398]
**Describe the bug**
When using to download saved posts, error showing immediately.

**To Reproduce**
(e.g. Instaloader command line)

**Expected behavior**
Start to download posts

**Error messages and tracebacks**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/instaloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/__main__.py", line 563, in main
    exit_code = _main(loader,
                ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/__main__.py", line 258, in _main
    instaloader.download_saved_posts(fast_update=fast_update, max_count=max_count,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/instaloader.py", line 1145, in download_saved_posts
    self.posts_download_loop(node_iterator, ":saved",
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/instaloader.py", line 1034, in posts_download_loop
    with resumable_iteration(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/nodeiterator.py", line 308, in resumable_iteration
    fni = load(context, resume_file_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/structures.py", line 2191, in load_structure_from_file
    return load_structure(context, json_structure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/instaloader/structures.py", line 2169, in load_structure
    return FrozenNodeIterator(**json_structure['node'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FrozenNodeIterator.__new__() missing 1 required positional argument: 'doc_id'

**Instaloader version**
4.13.1

**Additional context**
Python 3.12, macOS Sequoia

**Comment by ekalin** [comment]
It's not 100% clear what you're trying to do. That's why we ask for the exact steps to reproduce, including the command-line.

You mention saved posts, so I guess you're using `:saved`. Is that right?

The stack trace shows that it's trying to resume a previously interrupted iteration, which is something you did not mention. Did you have a previous run that was interrupted?

Anyway, I could not reproduce this problem with
```
instaloder :saved
<Press Ctrl-C to interrupt>
instaloder :saved
```

It read the frozen iterator and continued from where it had stopped. (It could not actually download the posts, but that is an unrelated error.)

Perhaps you have a saved iterator from a previous version? Did you update recently?

Is there a file with a name like `iterator_Jq4jK4qQ.json.xz` (the letters and numbers vary) in the directory where the saved posts are downloaded to? Does it work if you delete this file?

**Comment by zaitsevid** [comment]
Sorry, my fault. Tried some self repairs and messed everything. Initial error is with "feedback_required" message, as in #2387
