### ISSUE TITLE
Highlights download error

### ISSUE THREAD

**Issue by Hydronicx** [instaloader/instaloader#2443]
**Describe the bug**
Downloading highlights fails with error.

**To Reproduce**
Example with public profile: instaloader laraoneilll --highlights --login=LOGIN

**Expected behavior**
Highlights should download with no error.

**Error messages and tracebacks**
Stored ID 56602259939 for profile laraoneilll.
[1/1] Downloading profile laraoneilll
Unable to fetch high quality profile pic: 'hd_profile_pic_url_info'
laraoneilll\2023-12-04_00-24-57_UTC_profile_pic.jpg
Retrieving highlights "UK" from profile laraoneilll
laraoneilll\UK\2022-12-05_22-25-25_UTC_cover.jpg
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\miniconda3\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\__main__.py", line 584, in main
    exit_code = _main(loader,
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\__main__.py", line 302, in _main
    instaloader.download_profiles(
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\instaloader.py", line 1531, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\instaloader.py", line 81, in call
    return func(instaloader, *args, **kwargs)
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\instaloader.py", line 980, in download_highlights
    for item in user_highlight.get_items():
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\structures.py", line 1808, in get_items
    self._fetch_iphone_struct()
  File "C:\Users\user\miniconda3\lib\site-packages\instaloader\structures.py", line 1796, in _fetch_iphone_struct
    self._iphone_struct_ = data['reels']['highlight:{}'.format(self.unique_id)]
KeyError: 'highlight:18016523071475927'

**Instaloader version**
4.14

**Additional context**
Tried with other profiles, all the same.

**Comment by aandergr** [comment]
I couldn't reproduce the issue; downloading highlights works for me.

**Comment by Hydronicx** [comment]
Clean environment install works with no issues, so it's definitely a package issue.

**Comment by Tinchox17** [comment]
How did you solve it? i have the same problem with highlights
