### ISSUE TITLE
How to get all posts from a location given?

### ISSUE THREAD

**Issue by Ding74** [instaloader/instaloader#2447]
I make sure that i login in, and the location is valid. The Code is followed below:
posts = L.get_location_posts(LOCATION)

However, i got a error message:
连接异常: JSON Query to explore/locations/362629379/: 201 Created when accessing https://www.instagram.com/explore/locations/362629379/?__a=1&__d=dis

Traceback (most recent call last):
  File "f:\Paper\task\CrawlIns\main.py", line 109, in <module>
    main()
  File "f:\Paper\task\CrawlIns\main.py", line 106, in main
    CrawlData(L)
  File "f:\Paper\task\CrawlIns\main.py", line 40, in CrawlData
  File "C:\opt\Anaconda3\envs\py39\lib\site-packages\instaloader\instaloader.py", line 1161, in get_location_posts
    yield from SectionIterator(
  File "C:\opt\Anaconda3\envs\py39\lib\site-packages\instaloader\sectioniterator.py", line 22, in __init__
    self._data = first_data or self._query()
  File "C:\opt\Anaconda3\envs\py39\lib\site-packages\instaloader\sectioniterator.py", line 32, in _query
    self._context.get_json(self._query_path, params={"__a": 1, "__d": "dis", **pagination_variables})
  File "C:\opt\Anaconda3\envs\py39\lib\site-packages\instaloader\instaloadercontext.py", line 481, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "C:\opt\Anaconda3\envs\py39\lib\site-packages\instaloader\instaloadercontext.py", line 481, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "C:\opt\Anaconda3\envs\py39\lib\site-packages\instaloader\instaloadercontext.py", line 469, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to explore/locations/362629379/: 201 Created when accessing https://www.instagram.com/explore/locations/362629379/?__a=1&__d=dis

**Comment by aandergr** [comment]
It seems like you might be encountering a bug. The error message "201 Created" suggests that the response from Instagram might be unexpected in this context, which could indicate an issue with how the request is being handled.

To help resolve this, please provide a proper bug report with the following details:
1. The exact version of `instaloader` you're using.
2. Any additional context or observations that might help diagnose the issue.

**Comment by DnanaDev** [comment]
I can report that this bug is still present. Please re-open the issue. 

Instaloader Version : 4.14.1

` instaloader --login=thistempaccforscrape --post-filter="date_utc >= datetime(2025, 1, 24)" %108859701253827
Only download posts with property "date_utc >= datetime(2025, 1, 24)".
Loaded session from C:\Users\<redacted>\AppData\Local\Instaloader\session-<redacted>.
Logged in as <redacted>.
Retrieving pictures for location 108859701253827...
JSON Query to explore/locations/108859701253827/: 201 Created when accessing https://www.instagram.com/explore/locations/108859701253827/?__a=1&__d=dis [retrying; skip with ^C]
JSON Query to explore/locations/108859701253827/: 201 Created when accessing https://www.instagram.com/explore/locations/108859701253827/?__a=1&__d=dis [retrying; skip with ^C]
%108859701253827: JSON Query to explore/locations/108859701253827/: 201 Created when accessing https://www.instagram.com/explore/locations/108859701253827/?__a=1&__d=dis
Saved session to C:\Users\anand\AppData\Local\Instaloader\session-thistempaccforscrape.

Errors or warnings occurred:
%108859701253827: JSON Query to explore/locations/108859701253827/: 201 Created when accessing https://www.instagram.com/explore/locations/108859701253827/?__a=1&__d=dis`
