### ISSUE TITLE
Another "Failed to establish a new connection: [Errno 11004] getaddrinfo failed"

### ISSUE THREAD

**Issue by torchinz** [instaloader/instaloader#251]
**Describe the bug**
Instaloader shows multiple errors (e.g. connection exceeded :443) and does not work.

**To Reproduce**
Instaloader commandline (Windows 10 x64)
instaloader -l #### -p ####
Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001483A2D4E80>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /web/__mid/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001483A2D4E80>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Instaloader\__main__.py", line 444, in <module>
  File "C:\Instaloader\__main__.py", line 440, in __main
  File "C:\Instaloader\__main__.py", line 415, in main
  File "C:\Instaloader\__main__.py", line 102, in _main
  File "C:\Instaloader\instaloader\instaloader.py", line 1068, in interactive_login
  File "C:\Instaloader\instaloader\instaloader.py", line 363, in login
  File "C:\Instaloader\instaloader\instaloadercontext.py", line 194, in login
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 521, in get
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
  File "C:\Users\Koch-\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 508, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /web/__mid/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001483A2D4E80>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
[12272] Failed to execute script __main__

**Expected behavior**
Instaloader has been behaving like this since last 7 days or so. I have cleared and reinstalled instaloader, updated python, to no avail.

**Error messages and tracebacks**
As shown previously.

**Instaloader version**
`instaloader --version` output - 4.2.1

**Additional context**
Screenshot: 
![image](https://user-images.githubusercontent.com/17811608/52189857-36552800-2861-11e9-82de-bb0366939130.png)

**Comment by torchinz** [comment]
Thanks a lot for pointing to the exact same issues. Up and running. (y)

**Comment by torchinz** [comment]
Solved :)

**Comment by JIACHENG135** [comment]
Hello torchinz,

can u give us a more clear solution of this bug?

Sincerely,
Jiacheng
