### ISSUE TITLE
KeyError: 'edges' and KeyError: 'edge_media_to_comment' ?

### ISSUE THREAD

**Issue by redcupperboi** [instaloader/instaloader#272]
Running 4.2.3 (latest) on the following on 12 accounts for archival. Every single one returns this error sequence. I've changed nothing on my end. It started doing this shortly after Instagram and Facebook recovered from being down the other day.

instaloader --login=[USERNAME] --password=[PW] --geotags --comments --stories --no-compress-json --max-connection-attempts=0 --fast-update [USER] --no-profile-pic
Session file does not exist yet - Logging in.
Logged in as [USERNAME]
Retrieving posts from profile [USER].
[  1/293] [USER]/2019-03-27_00-18-42_UTC_1.jpg [USER]/2019-03-27_00-18-42_UTC_2.jpg [The history of Constantine...] Traceback (most recent call last):
  File "instaloader\structures.py", line 150, in _field
KeyError: 'edges'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 442, in <module>
  File "__main__.py", line 438, in __main
  File "__main__.py", line 413, in main
  File "__main__.py", line 189, in _main
  File "instaloader\instaloader.py", line 985, in download_profiles
  File "instaloader\instaloader.py", line 466, in download_post
  File "instaloader\instaloader.py", line 254, in update_comments
  File "instaloader\instaloader.py", line 254, in <genexpr>
  File "instaloader\structures.py", line 303, in get_comments
  File "instaloader\structures.py", line 155, in _field
KeyError: 'edge_media_to_comment'
[3668] Failed to execute script __main__

**Comment by Showmaster3000** [comment]
I have the same problem. It occurs since about 2019-03-25 if you download the comments using --comments
There must be a change by Instagram.
Temporary workaround: remove the --comments parameter.
