### ISSUE TITLE
caption_mentions + location + caption_hashtags + tagged_users

### ISSUE THREAD

**Issue by snrkldetection** [instaloader/instaloader#288]
I am trying to download these through using instaloader as a module, I am a bit of a noob and keep getting KeyErrors on theses elements. I can download them fine on cli using the same keys that i am trying in my scraper
{caption_mentions}
{caption_hashtags}
{tagged_users}
{location} 

This is the code for my scraper. Any ideas what key to use for them please?

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import instaloader, mysql.connector, urllib, os, time, logging, ssl, socket, datetime

socket.setdefaulttimeout(2)
ssl._create_default_https_context = ssl._create_unverified_context
#urllib.request.install_opener(urllib.request.build_opener(urllib.request.ProxyHandler({'https': '192.168.1.234:8888'})))

dlusernames = 'usernames.txt'
dlpath = '/mnt/mouny'

connection = mysql.connector.connect(
	host = "host",
	user = "user",
	passwd = "pword",
	database = "db",
	charset = 'utf8',
)
cursor = connection.cursor()
cursor.execute('SET NAMES utf8mb4')
cursor.execute("SET CHARACTER SET utf8mb4")
cursor.execute("SET character_set_connection=utf8mb4")

logger = logging.getLogger('instadump')
logger.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(message)s')
fh = logging.FileHandler('instadump.' + datetime.datetime.now().strftime('%Y%m%d') + '.log')
fh.setFormatter(formatter)
logger.addHandler(fh)

ch = logging.StreamHandler()
ch.setFormatter(formatter)
logger.addHandler(ch)

instaload = instaloader.Instaloader()
logger.info('Instadump started')

with open(dlusernames, 'r') as fin:
	for username in fin:
		username = username.strip()

		cursor.execute('SELECT `username` FROM `owner` WHERE `username` = %s', (username,))

		if cursor.fetchone():
			logger.info('Profile %s already scraped', username)
			continue

		try:
			profile = instaloader.Profile.from_username(instaload.context, username)
			owner_data = profile._node

			logger.info('Profile %s', owner_data['username'])

			if not os.path.exists(os.path.join(dlpath, owner_data["id"])):
				logger.info('  creating directory %s for user %s', os.path.join(dlpath, owner_data["id"]), username)
				os.makedirs(os.path.join(dlpath, owner_data["id"]))

			for post in profile.get_posts():
				if os.path.exists(os.path.join(dlpath, owner_data["id"], post.shortcode + '.jpg')):
					logger.info('  %s - already exists [%s]', post.shortcode, os.path.join(dlpath, owner_data["id"], post.shortcode + '.jpg'))
					continue

				post_file = os.path.join(dlpath, owner_data["id"], post.shortcode + '.jpg')
				post_timestamp = time.mktime(post.date.timetuple())
				post_data = post._node
				post_thumbnail = next(thumb['src'] for thumb in post_data['thumbnail_resources'] if thumb['config_width'] == 640)

				while True:
					try:
						urllib.request.urlretrieve(post_thumbnail, post_file)
						os.utime(post_file, (post_timestamp, post_timestamp))

						cursor.execute('INSERT IGNORE INTO `media` (`id`, `owner_id`, `is_video`, `comments_disabled`, `shortcode`, `taken_at_timestamp`,`caption`, `liked_by`, `commented`,`media`, edge_follow, edge_followed_by, `dimensions-width`, `display_url`, `thumbnail_src`, caption_hashtags) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)', (
							post_data["id"],
							post_data["owner"]["id"],
							post_data["is_video"],
							post_data["comments_disabled"],
							post_data["shortcode"],
							post_data["taken_at_timestamp"],
							post_data["edge_media_to_caption"]["edges"][0]["node"]["text"] if post_data["edge_media_to_caption"]["edges"] else None,
							post_data["edge_media_preview_like"]["count"],
							post_data["edge_media_to_comment"]["count"],
							owner_data["edge_owner_to_timeline_media"]["count"],
 			                                owner_data["edge_follow"]["count"],
                         			        owner_data["edge_followed_by"]["count"],
							post_data["dimensions"]["width"],
							post_data["display_url"],
							post_data["thumbnail_src"],
							post_data["caption_mentions"],
						))
						connection.commit()

					except urllib.error.HTTPError as e:
						logger.warning('  %s - HTTP Error %s: %s', post.shortcode, e.code, e.reason)
						break
					except (ssl.SSLError, urllib.error.URLError) as e:
						logger.warning('  %s - Error %s', post.shortcode, e.reason)
						time.sleep(1)
						continue
					except socket.timeout as e:
						logger.warning('  %s', e)
						continue
					else:
						logger.info('  %s - downloaded [%s]', post.shortcode, post_file)
						break

#			scrape_at = datetime.datetime.now() + datetime.timedelta(hours = 1)
			cursor.execute('REPLACE INTO `owner` (`id`, `username`, `full_name`, `biography`, edge_follow, edge_followed_by, `is_business_account`, `business_category_name`, `external_url`, `external_url_linkshimmed`, `profile_pic_url`, `profile_pic_url_hd`, media) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)', (
				owner_data["id"],
				owner_data["username"],
				owner_data["full_name"],
				owner_data["biography"],
				owner_data["edge_follow"]["count"],
				owner_data["edge_followed_by"]["count"],
				owner_data["is_business_account"],
				owner_data["business_category_name"],
				owner_data["external_url"],
				owner_data["external_url_linkshimmed"],
				owner_data["profile_pic_url"],
				owner_data["profile_pic_url_hd"],
				owner_data["edge_owner_to_timeline_media"]["count"],
#				scrape_at.strftime('%Y-%m-%d %H:%M:%S'),
			))
			connection.commit()

		except instaloader.exceptions.ProfileNotExistsException:
			logger.info('Profile %s not found', username)

logger.info('Instadump finished')

```

**Comment by snrkldetection** [comment]
For more info i have managed to get "location" to work intermittently with the key
[location][slug]
I can download the first 12 posts of a profile and then get KeyError even though it imported the Location data into mysql no issues for the first 12 posts. The 13th post has a location as i thought it might be failing because of this.

2019-05-02 13:19:29,690 - Instadump started
2019-05-02 13:19:30,679 - Profile account
2019-05-02 13:19:30,789 -   creating directory /mnt/imagedump/284828194 for user accouny
2019-05-02 13:19:31,910 -   Bw9JQ2SlLoy - downloaded [/mnt/imagedump/284828194/Bw9JQ2SlLoy.jpg]
2019-05-02 13:19:32,908 -   Bw3zWDglXkF - downloaded [/mnt/imagedump/284828194/Bw3zWDglXkF.jpg]
2019-05-02 13:19:33,751 -   Bw1V6IXlIiq - downloaded [/mnt/imagedump/284828194/Bw1V6IXlIiq.jpg]
2019-05-02 13:19:34,777 -   BwyXqbHFaDN - downloaded [/mnt/imagedump/284828194/BwyXqbHFaDN.jpg]
2019-05-02 13:19:35,708 -   Bwv6wLbF707 - downloaded [/mnt/imagedump/284828194/Bwv6wLbF707.jpg]
2019-05-02 13:19:36,711 -   BwsIPAxlhc_ - downloaded [/mnt/imagedump/284828194/BwsIPAxlhc_.jpg]
2019-05-02 13:19:37,805 -   BwjfPp_l8sC - downloaded [/mnt/imagedump/284828194/BwjfPp_l8sC.jpg]
2019-05-02 13:19:38,843 -   BwesIQfl3ET - downloaded [/mnt/imagedump/284828194/BwesIQfl3ET.jpg]
2019-05-02 13:19:39,808 -   BwZLrJaFHNu - downloaded [/mnt/imagedump/284828194/BwZLrJaFHNu.jpg]
2019-05-02 13:19:40,757 -   BwWpp1LFOVy - downloaded [/mnt/imagedump/284828194/BwWpp1LFOVy.jpg]
2019-05-02 13:19:41,698 -   BwUEiq4FL04 - downloaded [/mnt/imagedump/284828194/BwUEiq4FL04.jpg]
2019-05-02 13:19:42,646 -   BwRCqnfl8XN - downloaded [/mnt/imagedump/284828194/BwRCqnfl8XN.jpg]
Traceback (most recent call last):
  File "./1.py", line 90, in <module>
    post_data["location"]["slug"],
KeyError: 'location'

For other accounts i get this error

2019-05-02 13:25:25,799 - Instadump started
2019-05-02 13:25:30,867 - Profile kellouhar
2019-05-02 13:25:30,867 -   creating directory /mnt/imagedump/219777478 for user kellouhar
2019-05-02 13:25:32,036 -   Bw6odrGnLaw - downloaded [/mnt/imagedump/219777478/Bw6odrGnLaw.jpg]
Traceback (most recent call last):
  File "./1.py", line 90, in <module>
    post_data["location"]["slug"],
TypeError: 'NoneType' object is not subscriptable
