### ISSUE TITLE
Bug on instaloader.download_hashtag

### ISSUE THREAD

**Issue by samsoncn** [instaloader/instaloader#298]
**Describe the bug**
I installed instaloader package in pycharm and currently import instaloader. I used the function download_hashtag and it was working well past few days, but it doesn't work at this moment. 
Therefore, what happen and what is error down below??

Thanks

Traceback (most recent call last):
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 157, in _field
    d = d[key]
KeyError: 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Samson Chan/Documents/project/web/hashtag.py", line 16, in <module>
    post.download_hashtag(no_hash)
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 844, in download_hashtag
    downloaded = self.download_post(post, target='#' + hashtag)
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 490, in download_post
    if self.download_geotags and post.location:
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 413, in location
    loc = self._field("location")
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 160, in _field
    d = self._full_metadata
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 142, in _full_metadata
    self._obtain_metadata()
  File "C:\Users\Samson Chan\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 135, in _obtain_metadata
    self._rhx_gis_str = pic_json['rhx_gis']
KeyError: 'rhx_gis'

**Comment by clb92** [comment]
> KeyError: 'rhx_gis'

This is related to #297 it seems.

**Comment by samsoncn** [comment]
@clb92 Thanks man
