### ISSUE TITLE
Cannot do anything (KeyError: 'rhx_gis')

### ISSUE THREAD

**Issue by adree67** [instaloader/instaloader#300]
I use ubuntu 19.10, python3.7, instaloader 4.2.4

This part of code worked perfectly a day ago, but now i got unexpected error.

```
from instaloader import Instaloader, Post

link = 'https://www.instagram.com/p/Bo5zFRLFqXb/'

L = Instaloader()
shortcode = link.split('/p/')[1].replace('/', '')
post = Post.from_shortcode(L.context, shortcode)
```
Output:
```
Traceback (most recent call last):
  File "/home/adrian/Documents/Instabot/instagram.py", line 98, in <module>
    print(inst.if_post_exists('https://www.instagram.com/p/Bo5zFRLFqXb/'))
  File "/home/adrian/Documents/Instabot/instagram.py", line 24, in if_post_exists
    Post.from_shortcode(self.L.context, shortcode)
  File "/home/adrian/Documents/Instabot/venv/lib/python3.7/site-packages/instaloader/structures.py", line 79, in from_shortcode
    post._node = post._full_metadata
  File "/home/adrian/Documents/Instabot/venv/lib/python3.7/site-packages/instaloader/structures.py", line 142, in _full_metadata
    self._obtain_metadata()
  File "/home/adrian/Documents/Instabot/venv/lib/python3.7/site-packages/instaloader/structures.py", line 135, in _obtain_metadata
    self._rhx_gis_str = pic_json['rhx_gis']
KeyError: 'rhx_gis'
```
And one more example
```
from instaloader import Instaloader, Profile

usernake = 'adree67'

L = Instaloader()
profile = Profile.from_username(L.context, username)
```
Output:
```
Traceback (most recent call last):
  File "/home/adrian/.local/lib/python3.7/site-packages/instaloader/structures.py", line 510, in _obtain_metadata
    self._rhx_gis = metadata['rhx_gis']
KeyError: 'rhx_gis'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adrian/Documents/Instabot/instagram.py", line 96, in <module>
    print(inst.if_user_exists('adree67'))
  File "/home/adrian/Documents/Instabot/instagram.py", line 15, in if_user_exists
    Profile.from_username(self.L.context, username)
  File "/home/adrian/.local/lib/python3.7/site-packages/instaloader/structures.py", line 465, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistException now in case username is invalid
  File "/home/adrian/.local/lib/python3.7/site-packages/instaloader/structures.py", line 512, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err
instaloader.exceptions.ProfileNotExistsException: Profile adree67 does not exist.
```
Actually, these post and user exist, so i have no idea what is wrong. pls help

**Comment by Showmaster3000** [comment]
Duplicate #297
