### ISSUE TITLE
Downlaod multiple accounts

### ISSUE THREAD

**Issue by nikartz** [instaloader/instaloader#313]
**Describe the bug**
Not really a bug. However I switched from using instaloader as a git-download to the installation now and I'm not able to download a list of accounts. My current code looks like this:

```
declare -a arr=("person1" "person2" "person3")

for i in "${arr[@]}"
do
cd /path/to/download/location
sudo instaloader --sessionfile=/home/pi/...../instaloader/instaloader-session --quiet --filename-pattern={date_utc}_{profile} --dirname-pattern=user_{profile} --login=MYACCOUNT --password=MYPASSWORD [ $i ] >> /path/to/logs/instaloader.txt 2>&1
```

However, the problem is, that instaloader downloads every profile I am following - instead of just those listed in the list.

**Expected behavior**
Download just those profiles in the list.

**Instaloader version**
4.2.7

Thanks in advance!

**Comment by e5150** [comment]
See [aandersgr's comment](https://github.com/instaloader/instaloader/issues/289#issuecomment-489673949). You don't need to loop through your list, just pass all profiles at once, and don't wrap them in `[ ]`. Also, why sudo? As long as the target directory is writable by your regular user there's no need to run instaloader as root.

**Comment by nikartz** [comment]
Thanks for your help!
I have now changed the code to:
```
cd /path/to/download/location
sudo instaloader --sessionfile=/home/pi/...../instaloader/instaloader-session --quiet --filename-pattern={date_utc}_{profile} --dirname-pattern=user_{profile} --login=MYACCOUNT --password=MYPASSWORD person1 person2 person3 >> /path/to/logs/instaloader.txt 2>&1
```
However, now instaloader downloads all profiles my account is following and after some time I also get:
```
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 1000, in download_profiles
    for post in profile.get_posts():
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 694, in get_posts
    self._metadata('edge_owner_to_timeline_media')))
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 688, in <genexpr>
    yield from (Post(self._context, node, self) for node in
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloadercontext.py", line 469, in graphql_node_list
    data = _query()
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloadercontext.py", line 451, in _query
    return edge_extractor(self.graphql_query(query_hash, query_variables, query_referer, rhx_gis))
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloadercontext.py", line 436, in graphql_query
    session=tmpsession)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloadercontext.py", line 381, in get_json
    resp_json = resp.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Unterminated string starting at: line 1 column 76865 (char 76864)
```
