### ISSUE TITLE
KeyError: 'edge_sidecar_to_children'

### ISSUE THREAD

**Issue by pinkrazorgoblin** [instaloader/instaloader#380]
**Describe the bug**

```
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.8', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 1017, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 462, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/usr/local/lib/python3.6/site-packages/instaloader/structures.py", line 226, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/usr/local/lib/python3.6/site-packages/instaloader/structures.py", line 159, in _field
    d = self._full_metadata
  File "/usr/local/lib/python3.6/site-packages/instaloader/structures.py", line 142, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.6/site-packages/instaloader/structures.py", line 134, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instaloader/structures.py", line 156, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'
```

**To Reproduce**
Instaloader command line

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).

**Error messages and tracebacks**
KeyError: 'edge_sidecar_to_children'

**Instaloader version**
4.2.8

**Additional context**

**Comment by hmbrg** [comment]
Any help with that? @Thammus

**Comment by davispuh** [comment]
Getting same error with `4.2.9`

````
[  1/ 49] Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.9', 'console_scripts', 'instaloader')()
  File "/usr/lib/python3.7/site-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/lib/python3.7/site-packages/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/lib/python3.7/site-packages/instaloader/instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/usr/lib/python3.7/site-packages/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/usr/lib/python3.7/site-packages/instaloader/structures.py", line 227, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/usr/lib/python3.7/site-packages/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/usr/lib/python3.7/site-packages/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/usr/lib/python3.7/site-packages/instaloader/structures.py", line 135, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
````

**Comment by mseguin** [comment]
I've got the same error. 
I've tested with multiples Instagram account and the bug seems to occur when instaloader have to download multiples images in one post.

`File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.9', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 1010, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 884, in download_tagged
    downloaded = self.download_post(post, target if target else Path(profile.username) / Path(':tagged'))
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 227, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 135, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
`

**Comment by calvinc64** [comment]
Well, New error:
```
Traceback (most recent call last):
  File "/storage/dockerdata/syncthing/instaloader/instaloader/structures.py", line 158, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/dockerdata/syncthing/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/storage/dockerdata/syncthing/instaloader/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/storage/dockerdata/syncthing/instaloader/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/storage/dockerdata/syncthing/instaloader/instaloader/instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/storage/dockerdata/syncthing/instaloader/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/storage/dockerdata/syncthing/instaloader/instaloader/structures.py", line 228, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/storage/dockerdata/syncthing/instaloader/instaloader/structures.py", line 161, in _field
    d = self._full_metadata
  File "/storage/dockerdata/syncthing/instaloader/instaloader/structures.py", line 144, in _full_metadata
    self._obtain_metadata()
  File "/storage/dockerdata/syncthing/instaloader/instaloader/structures.py", line 136, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
```

**Comment by calvinc64** [comment]
Edit, this is the content of the pic_json:
```{'config': {'csrf_token': 'vZjBrdMAIEJt5CdY4jPvkv3SlRsWfYV2', 'viewer': {'biography': 'Hobbyphotographer (Lumix GH4), Japanese Culture & Anime enthusiast, Linux User, Lvl20', 'external_url': 'https://calvin-c.photography/?src=ig', 'full_name': 'Calvin', 'has_phone_number': True, 'has_profile_pic': True, 'id': '1156575468', 'is_joined_recently': False, 'is_private': False, 'profile_pic_url': 'https://scontent-dus1-1.cdninstagram.com/vp/68998b21536d72ab6f56d8f9c69a6ceb/5E3489DE/t51.2885-19/s150x150/45291094_785502951790379_4519902365448404992_n.jpg?_nc_ht=scontent-dus1-1.cdninstagram.com', 'profile_pic_url_hd': 'https://scontent-dus1-1.cdninstagram.com/vp/58a45fceed3637e9ce255e2f85b14775/5E35112E/t51.2885-19/s320x320/45291094_785502951790379_4519902365448404992_n.jpg?_nc_ht=scontent-dus1-1.cdninstagram.com', 'username': 'calvin_thefreak', 'badge_count': '{"seq_id": 25533, "badge_count": 0, "badge_count_at_ms": 1569874169417}'}, 'viewerId': '1156575468'}, 'country_code': 'DE', 'language_code': 'en', 'locale': 'en_US', 'entry_data': {'PostPage': [{}]}, 'hostname': 'www.instagram.com', 'deployment_stage': 'c2', 'platform': 'web', 'nonce': '8sPZhhXgkxlqfmOf+Md/sg==', 'mid_pct': 85.36416, 'zero_data': {}, 'cache_schema_version': 3, 'server_checks': {'hfe': True}, 'knobx': {'4': False, '17': False, '18': True, '19': True}, 'to_cache': {'gatekeepers': {'4': True, '5': False, '6': False, '7': False, '8': False, '9': False, '10': False, '11': True, '12': False, '13': True, '14': True, '15': True, '16': False, '18': True, '19': False, '23': False, '24': False, '26': True, '27': False, '28': False, '29': True, '31': False, '32': True, '34': False, '35': False, '38': True, '40': True, '41': False, '43': False, '45': True, '59': True, '60': False, '61': False, '62': False, '63': False, '64': False, '65': False, '66': True, '67': False, '68': False, '69': False}, 'qe': {'app_upsell': {'g': '', 'p': {}}, 'igl_app_upsell': {'g': '', 'p': {}}, 'notif': {'g': '', 'p': {}}, 'log_cont': {'g': '', 'p': {}}, 'onetaplogin': {'g': 'control', 'p': {'after_login': 'true', 'storage_version': 'one_tap_storage_version'}}, 'multireg_iter': {'g': '', 'p': {}}, 'felix_clear_fb_cookie': {'g': 'control', 'p': {'is_enabled': 'true', 'blacklist': 'fbsr_124024574287414'}}, 'felix_creation_duration_limits': {'g': 'dogfooding', 'p': {'maximum_length_seconds': '3600', 'minimum_length_seconds': '60'}}, 'felix_creation_fb_crossposting': {'g': 'control', 'p': {'is_enabled': 'false'}}, 'felix_creation_fb_crossposting_v2': {'g': 'control', 'p': {'is_enabled': 'true', 'display_version': '2'}}, 'felix_creation_validation': {'g': 'control', 'p': {'edit_video_controls': 'true', 'description_maximum_length': '2200', 'max_video_size_in_bytes': '3600000000', 'minimum_length_for_feed_preview_seconds': '60', 'title_maximum_length': '75', 'valid_cover_mime_types': 'image/jpeg,image/png', 'valid_video_extensions': 'mp4,mov', 'valid_video_mime_types': 'video/mp4,video/quicktime'}}, 'mweb_topical_explore': {'g': '', 'p': {}}, 'post_options': {'g': 'control', 'p': {'enable_igtv_embed': 'true', 'use_refactor': 'true'}}, 'iglscioi': {'g': '', 'p': {}}, 'sticker_tray': {'g': '', 'p': {}}, 'web_sentry': {'g': 'test', 'p': {'show_feedback': 'true'}}, '0': {'p': {'4': True, '7': False, '8': False, '9': False}, 'qex': True}, '2': {'p': {'0': True}, 'qex': True}, '4': {'p': {'0': False}, 'qex': True}, '5': {'p': {'1': False}, 'qex': True}, '6': {'p': {'1': True, '5': False, '6': False, '7': False, '9': False, '10': False}, 'qex': True}, '7': {'p': {}, 'qex': True}, '10': {'p': {'2': False}, 'qex': True}, '12': {'p': {'0': 5}, 'qex': True}, '13': {'p': {'0': True}, 'qex': True}, '16': {'p': {'0': False}, 'qex': True}, '17': {'p': {'1': True}, 'qex': True}, '19': {'p': {'0': True}, 'qex': True}, '21': {'p': {'2': False}, 'qex': True}, '22': {'p': {'1': False, '2': 8.0, '3': 0.85, '4': 0.95, '5': 10.0, '10': 10.0}, 'qex': True}, '23': {'p': {'0': False, '1': False}, 'qex': True}, '25': {'p': {}, 'qex': True}, '26': {'p': {'0': ''}, 'qex': True}, '27': {'p': {'0': False}, 'qex': True}, '28': {'p': {'0': False}, 'qex': True}, '29': {'p': {}, 'qex': True}, '30': {'p': {'0': True}, 'qex': True}, '31': {'p': {}, 'qex': True}, '33': {'p': {}, 'qex': True}, '34': {'p': {'0': False}, 'qex': True}, '36': {'p': {'0': True, '1': False, '2': False, '3': False, '4': False}, 'qex': True}, '37': {'p': {'0': False}, 'qex': True}, '39': {'p': {'0': False, '2': False, '3': False, '4': False, '5': False}, 'qex': True}, '40': {'p': {'0': False}, 'qex': True}, '41': {'p': {'3': True}, 'qex': True}, '42': {'p': {'0': True}, 'qex': True}, '43': {'p': {'0': False, '1': False, '2': False}, 'qex': True}, '44': {'p': {'1': 'control', '2': 0.0}, 'qex': True}, '45': {'p': {'0': False, '1': 'not_now', '2': False, '4': 18, '5': False, '6': False, '7': True, '8': 4, '9': False, '10': 'default', '11': False, '12': False, '13': False, '14': False, '15': False, '16': 18, '17': 0}, 'qex': True}, '46': {'p': {'0': False}, 'qex': True}, '47': {'p': {'0': True, '1': False, '2': False, '3': False}, 'qex': True}, '48': {'p': {'0': False}, 'qex': True}, '49': {'p': {'0': False}, 'qex': True}, '50': {'p': {'0': False}, 'qex': True}, '51': {'p': {'0': False}, 'qex': True}, '52': {'p': {'0': False}, 'qex': True}, '53': {'p': {'0': 30}, 'qex': True}}, 'probably_has_app': True, 'cb': True}, 'device_id': None, 'rollout_hash': 'f73597121a9f', 'bundle_variant': 'metro', 'is_canary': False}```

**Comment by aandergr** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> Instaloader command line
> 

Is there a way to reproduce this issue? We run nightly tests where this issue never occured.

**Comment by calvinc64** [comment]
Well, seems like Instagram Api blocked some json keys to block my automated stuff.
I now have the cron from me set to run randomly within a 24h timeframe, that I get all the stories.

I think I hit a limit or so on the side of instagram API

**Comment by mseguin** [comment]
@aandergr 
I've reproduce it this morning and the error is only happening while downloading a post with multiples pics while I am logged.
`root@ns310023:~/test# instaloader anickdumontet --login testaccount
Loaded session from /tmp/.instaloader-root/session-testaccount.
Logged in as testaccount.
Stored ID 338019518 for profile anickdumontet.
anickdumontet/2018-07-16_18-35-20_UTC_profile_pic.jpg
Retrieving posts from profile anickdumontet.
[  1/448] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.9', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/usr/local/lib/python3.5/dist-packages/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 227, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.5/dist-packages/instaloader/structures.py", line 135, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
root@ns310023:~/test# instaloader --version
4.2.9
`
