### ISSUE TITLE
KeyError: 'graphql' when trying to collect location id (logged in user)

### ISSUE THREAD

**Issue by nickkuiper** [instaloader/instaloader#394]
I'm trying to get the posts from a location ID, however, currently getting the following bug.
I added the login prompt, but it's still happening.

How should I proceed?

Many thanks in advance

**Describe the bug**
```
Retrieving pictures for location 362629379...
[  1] %362629379 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: '__typename'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/__main__.py", line 148, in _main
    post_filter=post_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 49, in call
    return func(instaloader, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 805, in download_location
    downloaded = self.download_post(post, target='%' + location)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/instaloader.py", line 464, in download_post
    if post.typename == 'GraphSidecar':
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 222, in typename
    return self._field('__typename')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instaloader/structures.py", line 135, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
```

**Instaloader version**
4.2.9

**Comment by janez87** [comment]
I'm trying to do the same thing using a Jupyter notebook and I noticed this log appearing in the output

    HTTP redirect from https://www.instagram.com/explore/locations/116231/ to https://www.instagram.com/accounts/login/?next=/explore/locations/116231/

Maybe now being logged in is required to access posts by location?

**Comment by jansoepboer** [comment]
Same issue here.

**Comment by aandergr** [comment]
Is there a way to reproduce this bug? I'm trying downloading the same location ID with Instaloader 4.2.9 and it works fine.

> ```
> HTTP redirect from https://www.instagram.com/explore/locations/116231/ to https://www.instagram.com/accounts/login/?next=/explore/locations/116231/
> ```
> 
> Maybe now being logged in is required to access posts by location?

Yes, accessing posts by location requires to be logged in.

**Comment by V-Ma-lte-zos-FI** [comment]
anaconda3\lib\site-packages\instaloader\structures.py in _query(self, params)
   1309 
   1310     def _query(self, params):
-> 1311         return self._context.get_json("explore/tags/{0}/".format(self.name),
   1312                                       params)['graphql']["hashtag"]
   1313 

KeyError: 'graphql'

I have also the same problem and it is in structures.py file.

Instaloader versions tested 4.6 , 4.7.2
Python 3.8.5

Also tried to upgrade graphql, graphql-core ,cython and nothing.

I try to scrape hashtag-wise.
