### ISSUE TITLE
Instaloader not downloading (KeyErrors)

### ISSUE THREAD

**Issue by maddingamer** [instaloader/instaloader#429]
**Describe the bug**
Downloads interrupted since today

**To Reproduce**
```
python3 /instaloader/instaloader.py USER --login=LOGIN --stories --tagged --no-videos --no-captions --no-metadata-json --highlights --fast-update --dirname-pattern /downloads/{target}/ --sessionfile /settings/.instaloader-session
```

**Error messages and tracebacks**
```
Loaded session from /settings/.instaloader-session.
Logged in as LOGINUSER.
/downloads/X//X_profile_pic.jpg already exists
Retrieving tagged posts for profile DOWNLOADUSER.
Retrieving posts from profile DOWNLOADUSER.
[  1/  X] Traceback (most recent call last):
  File "/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/instaloader/instaloader.py", line 6, in <module>
    main()
  File "/instaloader/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/instaloader/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/instaloader/instaloader/instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/instaloader/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/instaloader/instaloader/structures.py", line 227, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/instaloader/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/instaloader/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/instaloader/instaloader/structures.py", line 135, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'
```

**Instaloader version**
v4.2.9

This Command I am using worked fine for the last months with no problem, so I guess Instagram changed something in their backend?!

**Comment by ungenio** [comment]
That error has already been corrected. You must update this file:

[https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py](url)

**Comment by maddingamer** [comment]
> That error has already been corrected. You must update this file:
> 
> [https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py](url)

Thanks! Haven't seen that there was an updated file. Fixed Error!

**Comment by shadow443** [comment]
@ungenio Hi, how can I solve this problem with windows 10? I install instaloader with "pip install" and I don't know where I should change instaloadercontext.py. Thank you.

I have the same problem: 

```
  File "instaloader\structures.py", line 157, in _field
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 446, in <module>
  File "__main__.py", line 442, in __main
  File "__main__.py", line 417, in main
  File "__main__.py", line 192, in _main
  File "instaloader\instaloader.py", line 1039, in download_profiles
  File "instaloader\instaloader.py", line 466, in download_post
  File "instaloader\structures.py", line 227, in get_sidecar_nodes
  File "instaloader\structures.py", line 160, in _field
  File "instaloader\structures.py", line 143, in _full_metadata
  File "instaloader\structures.py", line 135, in _obtain_metadata
KeyError: 'graphql'
[2632] Failed to execute script __main__
```

Instaloader version v4.2.9
Windows 10 64 Bit

**Comment by hgkmaxymus** [comment]
It seems it is probably on the folder you just run, inside of the "instaloader" folder should have a `instaloadercontext.py` file. I replaced mine with the one above and it worked just fine.

If the file above doesn't exist, mine was in:
```
/c/Users/<username>/AppData/Local/Programs/Python/<pythonversion>/lib/site-packages/instaloader/instaloadercontext.py
```

**Comment by nagualcode** [comment]
this problem still happens to me

**Comment by roboshim** [comment]
Thank you for this update!

**Comment by ungenio** [comment]
@shadow443 the update must be done manually. Download this file (right click on RAW and download):

`https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py`

and paste it here:

`C:\Users\<username>\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instaloader\instaloadercontext.py`

**Comment by shadow443** [comment]
@ungenio  Thank you. It is working for me.

**Comment by nagualcode** [comment]
@ungenio I am on linux. I performed a deep search for instaloadercontext.py (sudo find / -name instaloadercontext.py). Where I found this file in 2 places. To make sure, I replaced both files. Still, I am experiencing the problem with both video posts and multi-photo posts. I am downloading favorited posts by my user (instaloader :saved).
