### ISSUE TITLE
Unable to download certain people's profiles for some reason... Never had this issue before!

### ISSUE THREAD

**Issue by HornyHotSingles** [instaloader/instaloader#435]
**usage:
instaloader [--comments] [--geotags] [--stories] [--highlights] [--tagged]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %%location_id | :stories | :feed | :saved
instaloader --help

D:\Instaloader>instaloader --login=thehornyreaper elvien__
Loaded session from c:\users\nicho\appdata\local\temp/.instaloader-nicho/session-thehornyreaper.
Logged in as thehornyreaper.
elvien__/2019-10-25_00-31-35_UTC_profile_pic.jpg already exists
Retrieving posts from profile elvien__.
[  1/ 81] elvien__/2019-10-25_17-54-18_UTC.jpg exists [YAY I TURN 20 TODAYYYY] unchanged json
[  2/ 81] elvien__/2019-10-25_00-34-07_UTC.jpg exists [🐲] unchanged json
[  3/ 81] elvien__/2019-10-22_02-08-51_UTC.jpg exists json
[  4/ 81] Traceback (most recent call last):
  File "instaloader\structures.py", line 157, in _field
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 446, in <module>
  File "__main__.py", line 442, in __main
  File "__main__.py", line 417, in main
  File "__main__.py", line 192, in _main
  File "instaloader\instaloader.py", line 1039, in download_profiles
  File "instaloader\instaloader.py", line 466, in download_post
  File "instaloader\structures.py", line 227, in get_sidecar_nodes
  File "instaloader\structures.py", line 160, in _field
  File "instaloader\structures.py", line 143, in _full_metadata
  File "instaloader\structures.py", line 135, in _obtain_metadata
KeyError: 'graphql'
[8316] Failed to execute script __main__

D:\Instaloader>**

**Comment by DanielZhu03** [comment]
check this #429 
You must replace this file:
https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py
