### ISSUE TITLE
Highlight names (and possibly profiles) ending in a period get FileNotFoundError: [Errno 2] when downloading.

### ISSUE THREAD

**Issue by tdp4** [instaloader/instaloader#445]
**Describe the bug**
This happens on a windows share (aka, a filesystem that doesn't properly support folders ending in a '.').
In my case it was a highlight name ending in a period 'Galaxias.'.  It would create the folder no problem, but any attempt to make a file in that folder resulted in a 'FileNotFoundError: [Errno 2] No such file or directory'.  Manually attempting to touch this file in the filesystem resulted in the same/similar error.

**To Reproduce**
`
instaloader --login USERNAME --password "PASSWORD" chio_mei --fast-update --stories --highlights
`
Once it hits the offending highlight, it will error.

**Expected behavior**
It should write the file, it should continue.  Ideally to avoid this situation, allow for some sanitation of the foldernames.

**Error messages and tracebacks**
```
[  1/ 25] chio_mei/Galaxias./2019-10-04_19-35-18_UTC.jpg Traceback (most recent call last):
  File "/home/user/.local/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 1015, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 49, in call
    return func(instaloader, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 659, in download_highlights
    else Path(name) / Path(user_highlight.title))
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 591, in download_storyitem
    downloaded = self.download_pic(filename=filename, url=url, mtime=date_local)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 65, in call
    return func(instaloader, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 237, in download_pic
    self.context.get_and_write_raw(url, filename)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 543, in get_and_write_raw
    self.write_raw(self.get_raw(url), filename)
  File "/home/user/.local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 509, in write_raw
    with open(filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'chio_mei/Galaxias./2019-10-04_19-35-18_UTC.jpg'
```

**Instaloader version**
`
$ instaloader --version
4.2.9
`

**Additional context**
I realize this is more a system os layer issue.  I tried to get around the issue with --dirname-template and appending text to the end of {target}.  The results were less than ideal.  I vote it not a work-a-round.

**Comment by aandergr** [comment]
Very similar to #185, in that it refers to the Windows filesystem limitations.
