### ISSUE TITLE
KeyError: 'edge_sidecar_to_children' in 4.2.10

### ISSUE THREAD

**Issue by gituzzer** [instaloader/instaloader#451]
- Download a single profile, logged in. It starts downloading pics then stops with `KeyError: 'edge_sidecar_to_children'`
It's a rare ocurrence but reproducible. Example <PROFILE> = sophiadiamond.
If not logged in, it works fine.

Command:
```
python3 instaloader.py <PROFILE> --l <USER> -p <PASSWD> --no-captions --filename-pattern={date} --no-metadata-json
```

Version 4.2.10

TRACEBACK:
```
[  8/167] Traceback (most recent call last):
  File "/<PATH-TO-INSTALOADER>/instaloader/structures.py", line 157, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<PATH-TO-INSTALOADER>/instaloader.py", line 6, in <module>
    main()
  File "/<PATH-TO-INSTALOADER>/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/<PATH-TO-INSTALOADER>/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/<PATH-TO-INSTALOADER>/instaloader/instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/<PATH-TO-INSTALOADER>/instaloader/instaloader.py", line 466, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/<PATH-TO-INSTALOADER>/instaloader/structures.py", line 227, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/<PATH-TO-INSTALOADER>/instaloader/structures.py", line 160, in _field
    d = self._full_metadata
  File "/<PATH-TO-INSTALOADER>/instaloader/structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "/<PATH-TO-INSTALOADER>/instaloader/structures.py", line 137, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by PurpleViolentLocust** [comment]
I am having the same error.

**Comment by timlinden** [comment]
I received the same error but while trying :saved

`File "/usr/local/lib/python3.8/site-packages/instaloader/structures.py", line 157, in _field
d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/instaloader", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/site-packages/instaloader/__main__.py", line 401, in main
_main(loader,
File "/usr/local/lib/python3.8/site-packages/instaloader/__main__.py", line 155, in _main
instaloader.download_saved_posts(fast_update=fast_update, max_count=max_count,
File "/usr/local/lib/python3.8/site-packages/instaloader/instaloader.py", line 49, in call
return func(instaloader, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/instaloader/instaloader.py", line 742, in download_saved_posts
downloaded = self.download_post(post, target=':saved')
File "/usr/local/lib/python3.8/site-packages/instaloader/instaloader.py", line 466, in download_post
for sidecar_node in post.get_sidecar_nodes():
File "/usr/local/lib/python3.8/site-packages/instaloader/structures.py", line 227, in get_sidecar_nodes
for edge in self._field('edge_sidecar_to_children', 'edges'):
File "/usr/local/lib/python3.8/site-packages/instaloader/structures.py", line 160, in _field
d = self._full_metadata
File "/usr/local/lib/python3.8/site-packages/instaloader/structures.py", line 143, in _full_metadata
self._obtain_metadata()
File "/usr/local/lib/python3.8/site-packages/instaloader/structures.py", line 137, in _obtain_metadata
if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable`

**Comment by jhavens12** [comment]
I am seeing the same error while accessing :saved
