### ISSUE TITLE
Having issue trying to use it for the first time

### ISSUE THREAD

**Issue by ElusiveZatchmo** [instaloader/instaloader#465]
I'm using a Linux machine to run this. I installed using pip. And when I try to use it with a profile name I want to download, I only get the following:

`Traceback (most recent call last):
  File "./python3/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
  File "/{home}/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/{home}/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/{home}/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/{home}/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/{hoome}/python3/lib/python3.7/site-packages/instaloader/__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "/{home}/python3/lib/python3.7/site-packages/instaloader/instaloader.py", line 3, in <module>
    import lzma
  File "/{home}/python3/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'`

Please help.

**Comment by ledgreve** [comment]
are you trying to use the command line version or the Python module?

**Comment by ElusiveZatchmo** [comment]
I'm using it through the command line

**Comment by pjw91** [comment]
Where does the python interpreter come from?

If it's manually compiled, make sure the system package `xz-devel` (Debian) is installed (and re-compiled the python).
