### ISSUE TITLE
PermissionError via command line

### ISSUE THREAD

**Issue by ledgreve** [instaloader/instaloader#474]
Hello!

I am extracting instagram posts via the command line of my computer and it has worked fine this far. However, when I tried to download all posts with a specific hashtag this morning, I got a PermissionError:

`C:\>instaloader --no-pictures --no-videos --no-compress-json --no-profile-pic --post-metadata-txt="{owner_username}^{caption}^{date_local}^{date_utc}^{likes}^{comments}///" --filename-pattern={date_utc}_UTC_{profile} "#xxx"
Retrieving pictures with hashtag xxx...
[  1] #xxx Traceback (most recent call last):
  File "C:\Users\ledgreve\AppData\Local\Programs\Python\Python38-32\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
  File "c:\users\ledgreve\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\__main__.py", line 401, in main
    _main(loader,
  File "c:\users\ledgreve\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\__main__.py", line 142, in _main
    instaloader.download_hashtag(hashtag=target[1:], max_count=max_count, fast_update=fast_update,
  File "c:\users\ledgreve\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\instaloader.py", line 866, in download_hashtag
    downloaded = self.download_post(post, target='#' + hashtag)
  File "c:\users\ledgreve\appdata\local\programs\python\python38-32\lib\site-packages\instaloader\instaloader.py", line 458, in download_post
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "c:\users\ledgreve\appdata\local\programs\python\python38-32\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Toegang geweigerd: '#xxx'
`
The last line says (my translation) "PermissionError: [WinError 5] Access denied: '#xxx'".

Any ideas on what the problem might be and how I can solve it? I have never had this problem before and I am using the exact same command as before.
I _am_ working via a new computer, but Python and instaloader have both been installed without problems, so I don't get what the problem could be .

Kind regards

**Comment by aandergr** [comment]
Seems like an issue regarding the usage of Windows where we just cannot do anything.

**Comment by ashutoshvimal** [comment]
@Ledgrev  Hello, I am also facing the same issue. Did you find any solution?
