### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by petmi627** [instaloader/instaloader#503]
Dear Team,

I would like to download my saved pictures on Instagram but somehow after the 314 picture the porgramm teminate itself, I tried to remove the picture on my saved list but after sometime the error will come back on another picture

**To Reproduce**
This is the command, I typed in
```
instaloader --no-metadata-json --no-captions --no-video-thumbnails --filename-pattern={profile}_{date_utc}_UTC --login=[myusername] [myusername] :saved
```

**Error messages and tracebacks**
```python
[314] Traceback (most recent call last):
  File "C:\Users\petmi627\AppData\Local\Programs\Python\Python37-32\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\__main__.py", line 417, in main
    storyitem_filter_str=args.storyitem_filter)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\__main__.py", line 156, in _main
    post_filter=post_filter)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 49, in call
    return func(instaloader, *args, **kwargs)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 752, in download_saved_posts
    downloaded = self.download_post(post, target=':saved')
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 467, in download_post
    filename = dirname + '/' + self.format_filename(post, target=target)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 455, in format_filename
    return _PostPathFormatter(item).format(self.filename_pattern, target=target)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\string.py", line 186, in format
    return self.vformat(format_string, args, kwargs)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 108, in vformat
    ret = super().vformat(format_string, args, kwargs)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\string.py", line 190, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\string.py", line 230, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\string.py", line 295, in get_field
    obj = self.get_value(first, args, kwargs)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 116, in get_value
    ret = super().get_value(key, args, kwargs)
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\instaloader.py", line 90, in get_value
    if hasattr(self._item, key):
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\structures.py", line 212, in profile
    return self.owner_username
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\structures.py", line 183, in owner_username
    return self.owner_profile.username
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\structures.py", line 176, in owner_profile
    owner_struct = self._full_metadata['owner']
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\structures.py", line 143, in _full_metadata
    self._obtain_metadata()
  File "c:\users\petmi627\appdata\local\programs\python\python37-32\lib\site-packages\instaloader\structures.py", line 137, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable
```

**Instaloader version**
4.2.10

**Comment by tim54000** [comment]
You seem to be experiencing the same problem as issue #449 and possibly the same as me (#478).

**Comment by petmi627** [comment]
Yes seems like it

**Comment by aandergr** [comment]
No, #449 and #478 are different errors with different error messages and different tracebacks.

**Comment by christopherjanzen** [comment]
So I received this error too. I was downloading my "saved" posts. I looked at the last post that downloaded successfully and then removed from "saved" the post that seemed to cause the problem. After doing this I was able to finish downloading the rest of the "saved" posts. I'm not sure what in particular was wrong with the post and it was just a normal image.
