### ISSUE TITLE
Doesn't even work

### ISSUE THREAD

**Issue by fahamjv** [instaloader/instaloader#518]
**Describe the bug**
Doesn't work when i run "instaloader --login=usr  profile usr"

**To Reproduce**
instaloader --login=usr  profile usr

**Error messages and tracebacks**
Session file does not exist yet - Logging in.
Enter Instagram password for myusername: 
Logged in as myusername.
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
usr/2019-10-16_21-22-18_UTC_profile_pic.jpg already exists
Retrieving posts from profile usr.
[  1/ 39] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instaloader/structures.py", line 156, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.8', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.6/dist-packages/instaloader/__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.6/dist-packages/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.6/dist-packages/instaloader/instaloader.py", line 1017, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/usr/local/lib/python3.6/dist-packages/instaloader/instaloader.py", line 462, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/usr/local/lib/python3.6/dist-packages/instaloader/structures.py", line 226, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/usr/local/lib/python3.6/dist-packages/instaloader/structures.py", line 159, in _field
    d = self._full_metadata
  File "/usr/local/lib/python3.6/dist-packages/instaloader/structures.py", line 142, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.6/dist-packages/instaloader/structures.py", line 134, in _obtain_metadata
    self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
KeyError: 'graphql'

**Instaloader version**
4.2.8

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by aandergr** [comment]
> **Instaloader version**
> 4.2.8
> 
> **Additional context**
> Add any other context about the problem here.
> 
> (please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by fahamjv** [comment]
her @aandergr .  why  it is invalid ?

**Comment by aandergr** [comment]
> hey @aandergr . why it is invalid ?

Please try again with Instaloader 4.2.10 and 4.3a1.
