### ISSUE TITLE
EOFError not catched in Instaloader.check_if_committed()

### ISSUE THREAD

**Issue by voteforpresident** [instaloader/instaloader#524]
For some reason I get the *Could not find "window._sharedData" in html response* error.

All packages are up to date:
```
Requirement already satisfied: instaloader in /usr/local/lib/python3.6/site-packages (4.2.10)
Requirement already satisfied: requests>=2.4 in /usr/lib/python3.6/site-packages (from instaloader) (2.14.2)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.4->instaloader) (1.25.1)
```

The log looks like this:
```
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 414, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 189, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 1039, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 462, in download_post
    self._committed = self.check_if_committed(filename)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 1151, in check_if_committed
    load_structure_from_file(self.context, filename)
  File "/usr/local/lib/python3.6/site-packages/instaloader/structures.py", line 1094, in load_structure_from_file
    json_structure = json.load(fp)
  File "/usr/lib64/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.6/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by voteforpresident** [comment]
With the latest 4.3a1 I get the EOFError again.

Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.3a1', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 417, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 81, in _main
    instaloader.load_session_from_file(username, sessionfile)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 426, in load_session_from_file
    self.context.load_session_from_file(username, sessionfile)
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 177, in load_session_from_file
    session.cookies = requests.utils.cookiejar_from_dict(pickle.load(sessionfile))
EOFError: Ran out of input
