### ISSUE TITLE
No way to directly download images to CWD w/o creating subdirectory

### ISSUE THREAD

**Issue by fireattack** [instaloader/instaloader#530]
**Describe the bug**

Using 

```
instaloader --dirname-pattern "" instagram
```

will simply revert back to the default dir name ({target}), instead of bypassing creating folder.

`instaloader --dirname-pattern "/" instagram` doesn't work, either. 

```
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python37\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "c:\program files\python37\lib\site-packages\instaloader\__main__.py", line 401, in main
    _main(loader,
  File "c:\program files\python37\lib\site-packages\instaloader\__main__.py", line 159, in _main
    profile = instaloader.check_profile_id(target)
  File "c:\program files\python37\lib\site-packages\instaloader\instaloader.py", line 949, in check_profile_id
    self.save_profile_id(profile)
  File "c:\program files\python37\lib\site-packages\instaloader\instaloader.py", line 904, in save_profile_id
    with open(self._get_id_filename(profile.username), 'w') as text_file:
FileNotFoundError: [Errno 2] No such file or directory: '//instagram_id'
```

**To Reproduce**
(e.g. Instaloader command line)

See above.

**Instaloader version**
`instaloader --version` output.

4.3a1

**Comment by aandergr** [comment]
Hi! Thanks for your reports!

Does `--dirname-pattern="."` work?

**Comment by fireattack** [comment]
Ah yeah, that works.
