### ISSUE TITLE
Error: KeyError: 'edge_sidecar_to_children'

### ISSUE THREAD

**Issue by amd1105** [instaloader/instaloader#552]
I keep getting this error. I am not a developer. So I don't know what to do. I have multiple args_(insert kind).txt files. This only happens with one of them.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/structures.py", line 156, in _field
    d = d[key]
KeyError: 'edge_sidecar_to_children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.7', 'console_scripts', 'instaloader')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/__main__.py", line 186, in _main
    download_stories, fast_update, post_filter, storyitem_filter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloader.py", line 1017, in download_profiles
    downloaded = self.download_post(post, target=profile_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/instaloader.py", line 462, in download_post
    for sidecar_node in post.get_sidecar_nodes():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/structures.py", line 226, in get_sidecar_nodes
    for edge in self._field('edge_sidecar_to_children', 'edges'):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/structures.py", line 159, in _field
    d = self._full_metadata
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/structures.py", line 142, in _full_metadata
    self._obtain_metadata()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instaloader/structures.py", line 136, in _obtain_metadata
    if self.shortcode != self._full_metadata_dict['shortcode']:
TypeError: 'NoneType' object is not subscriptable

**Comment by aandergr** [comment]
This issue has already been fixed. You seem to be using an old Instaloader version. Please upgrade Instaloader and try again.

If you installed Instaloader with Pip, you can upgrade to the newest version using:
```
pip3 install --upgrade instaloader
```
