### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#575]
**Describe the bug**
Instaloader is unable to create a highlight folder on a raspberry pi. My guess is it's either # or emoji's fault.

**To Reproduce**
`instaloader banghana --no-posts --highlights -l login -p password`

**Expected behavior**
Instaloader downloading said 

**Error messages and tracebacks**
```
Retrieving highlights "#はなちゃれ 🏠💕" from profile banghana
Traceback (most recent call last):
  File "/home/pi/.local/bin/instaloader", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 426, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 195, in _main
    fast_update, post_filter, storyitem_filter)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 1084, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 49, in call
    return func(instaloader, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 679, in download_highlights
    self.download_highlight_cover(user_highlight, highlight_target)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 409, in download_highlight_cover
    self.download_title_pic(highlight.cover_url, target, 'cover', highlight.owner_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 65, in call
    return func(instaloader, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 395, in download_title_pic
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: 'banghana/#はなちゃれ 🏠💕'
```

**Instaloader version**
4.3.2

**Additional context**
Instaloader 4.3 on macos creates this folder just fine.

**Comment by e5150** [comment]
What is the filesystem type where your target directory is located? `findmnt -o FSTYPE -nT /instaloader/download/path`
If you get the same error by manually running `mkdir -p 'banghana/#はなちゃれ 🏠💕'`, you could determine which the offending char is. 
As a temporary workaround you could specify an output directory that won't include the name of the highlights, such as just `--dirname-pattern='{profile}'`.

**Comment by renox92** [comment]
> What is the filesystem type where your target directory is located?

Exfat. Turns out it was an emoji problem. Dowloading to ext4 works as expected.

**Comment by renox92** [comment]
I tried connecting drive to my mac and it creates folder there as well. So it's not a drive problem, not a fs problem and not an OS problem either since pi can create that folder inside home directory (ext4). Could it be an exfat driver problem then? I am using a nofuse one, not sure if the fuse one would work, but it wouldn't be worth the switch.
