### ISSUE TITLE
KeyError: graphql

### ISSUE THREAD

**Issue by blablable123456** [instaloader/instaloader#583]
**Describe the bug**
During the catching of igtv posts, sometimes it will crash randomly and other times it will work normally.

**To Reproduce**
instaloader -l XX -p YY --stories --no-posts --igtv --no-profile-pic --no-video-thumbnails --no-captions --no-metadata-json @XX

**Error messages and tracebacks**
[ 5/21] Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\structures.py", line 157, in _field
KeyError: 'video_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==4.3.1', 'console_scripts', 'instaloader')()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\__main__.py", line 412, in main
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\__main__.py", line 192, in _main
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\instaloader.py", line 1077, in download_profiles
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\instaloader.py", line 933, in download_igtv
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\instaloader.py", line 517, in download_post
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\structures.py", line 294, in video_url
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\structures.py", line 160, in _field
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\structures.py", line 143, in _full_metadata
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader-4.3.1-py3.8.egg\instaloader\structures.py", line 135, in _obtain_metadata
KeyError: 'graphql'

**Instaloader version**
4.3.1

**Comment by Showmaster3000** [comment]
Please upgrade to the latest version 4.3.2 which seems to solve your problem (related bug #449)
