### ISSUE TITLE
? in Highlights folder name causing crash

### ISSUE THREAD

**Issue by SP-Alex** [instaloader/instaloader#595]
**Describe the bug**

When I try to download highlights from a folder with a character that cannot be used in Windows folder/files names, like "?", Instaloader will crash.

**To Reproduce**
(e.g. Instaloader command line)

The problem can be replicated by using `instaloader --highlights` with any profile with a ? or similar character in one of their highlights folder names. Both of the examples I found are private profiles, however.

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).

I would expect Instaloader to either rename the folder locally or simply move on to the next highlights folder.

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

`Retrieving highlights "*****?" from profile **********
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\instaloader.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\instaloader\__main__.py", line 426, in main
    storyitem_filter_str=args.storyitem_filter)
  File "c:\python37\lib\site-packages\instaloader\__main__.py", line 195, in _main
    fast_update, post_filter, storyitem_filter)
  File "c:\python37\lib\site-packages\instaloader\instaloader.py", line 1084, in download_profiles
    self.download_highlights(profile, fast_update=fast_update, storyitem_filter=storyitem_filter)
  File "c:\python37\lib\site-packages\instaloader\instaloader.py", line 49, in call
    return func(instaloader, *args, **kwargs)
  File "c:\python37\lib\site-packages\instaloader\instaloader.py", line 679, in download_highlights
    self.download_highlight_cover(user_highlight, highlight_target)
  File "c:\python37\lib\site-packages\instaloader\instaloader.py", line 409, in download_highlight_cover
    self.download_title_pic(highlight.cover_url, target, 'cover', highlight.owner_profile)
  File "c:\python37\lib\site-packages\instaloader\instaloader.py", line 65, in call
    return func(instaloader, *args, **kwargs)
  File "c:\python37\lib\site-packages\instaloader\instaloader.py", line 395, in download_title_pic
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "c:\python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '**********\\*****?'`

**Instaloader version**
`instaloader --version` output.

`4.3.2`

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by Showmaster3000** [comment]
I would reference it to #576 where some other Windows related naming bugs are discussed.
