### ISSUE TITLE
from _lzma import * ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by ChocoTonic** [instaloader/instaloader#611]
**To Reproduce**
instaloader in command line
also tried running in Visual Studio Code using 3.8 64 bit and 2.7 64 bit

could it be because I have 2 installations of Python?

here is code I copy pasted as an example

```
from instaloader import Instaloader, Profile

PROFILE = "dudewithsign"  # Insert profile name here

L = Instaloader()

# Obtain profile
profile = Profile.from_username(L.context, PROFILE)

# Get all posts and sort them by their number of likes
posts_sorted_by_likes = sorted(
    profile.get_posts(), key=lambda post: post.likes, reverse=True
)

# Download the post with the most likes
for k in range(10):
    L.download_post(posts_sorted_by_likes[k], PROFILE)

```

**Expected behavior**
not sure what is expected, but not a traceback error

**Error messages and tracebacks**
Traceback (most recent call last):
  File "c:\Users\XXX\AppData\Local\Temp\ab4cb5cb039a97b73160ea13016a81089ef6a9f81589261934510tmp-16852B288663JC6QE.py\InstagramMostLikedDownloader.py", line 1, in <module>
    from instaloader import Instaloader, Profile
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 3, in <module>
    import lzma
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\lzma.py", line 53, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

**Instaloader version**
4.4

**Comment by ChocoTonic** [comment]
fixed by repairing Python installation
