### ISSUE TITLE
Instaloader Don't Working

### ISSUE THREAD

**Issue by fatihskara** [instaloader/instaloader#621]
Hello, After entering my Instagram password, I get the following output. Then the program stops running.

Version: 4.4.1
Python Version: 3.8

`instaloader --login=USERNAME
Session file does not exist yet - Logging in.
Enter Instagram password for USERNAME: 
Traceback (most recent call last):
  File "/home/rootz/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/rootz/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 421, in main
    _main(loader,
  File "/home/rootz/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 104, in _main
    instaloader.interactive_login(username)
  File "/home/rootz/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 1222, in interactive_login
    self.login(username, password)
  File "/home/rootz/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 462, in login
    self.context.login(user, passwd)
  File "/home/rootz/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 221, in login
    resp_json = login.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by u174458** [comment]
Duplicated thread from this one: https://github.com/instaloader/instaloader/issues/615

**Comment by Tom1380** [comment]
I'm having this same problem.
