### ISSUE TITLE
Highlights ending with ... has a missing folder/file error

### ISSUE THREAD

**Issue by mlalcevski** [instaloader/instaloader#710]
**Describe the bug**
One of the highlights is labeled "Something ...", the "..." does not work as a folder name in windows so it gets an error every time.

**To Reproduce**
Download any highlights ending in ...

**Expected behavior**
Well rename the folder and ignore the ..

**Error messages and tracebacks**
[Errno 2] No such file or directory

**Instaloader version**
4.4.4

**Additional context**

**Comment by aandergr** [comment]
Thanks for reporting. Indeed, creating a folder containing ".." or "..." in the name does not always work on Windows.

> **Expected behavior**
> Well rename the folder and ignore the ..

Maybe the dots in "..." should be replaced by another character that is not invalid in filenames and does not collide with characters that might occur in highlight titles, such as "-". There is also #576 with an idea of how we could approach this.

**Comment by psonnosp** [comment]
It just does not always work, it never works with dots at the end of a folder name in Windows.
I know nothing about whats talked about in that other issue, but is it a complicated thing to make Instaloader ignore dots or use _ instead in the ending of folder names? Cause this seems like kind of a basic thing to handle for a program that runs in Windows.

**Comment by psonnosp** [comment]
If this can't be fixed by replacing the dots would it be possible to make instaloader at least continue and not just quit with this error?
...\2019-05-23_11-39-37_UTC_cover.jpg Traceback (most recent call last):
  File "__main__.py", line 462, in <module>
  File "__main__.py", line 459, in __main
  File "__main__.py", line 429, in main
  File "__main__.py", line 203, in _main
  File "instaloader\instaloader.py", line 1150, in download_profiles
  File "instaloader\instaloader.py", line 63, in call
  File "instaloader\instaloader.py", line 708, in download_highlights
  File "instaloader\instaloader.py", line 429, in download_highlight_cover
  File "instaloader\instaloader.py", line 79, in call
  File "instaloader\instaloader.py", line 416, in download_title_pic
  File "instaloader\instaloadercontext.py", line 485, in write_raw
FileNotFoundError: [Errno 2] No such file or directory: ...\\2019-05-23_11-39-37_UTC_cover.jpg.temp'
[18116] Failed to execute script __main__
