### ISSUE TITLE
Unable to download the tagged pictures.

### ISSUE THREAD

**Issue by Goluvikar** [instaloader/instaloader#725]
Hi I am unable to download the tagged photos from instagram getting the below error.
[  1] Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/instaloader/__main__.py", line 423, in main
    _main(loader,
  File "/usr/local/lib/python3.8/dist-packages/instaloader/__main__.py", line 203, in _main
    instaloader.download_profiles(profiles,
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 1109, in download_profiles
    self.download_tagged(profile, fast_update=fast_update, post_filter=post_filter)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 959, in download_tagged
    self.posts_download_loop(profile.get_tagged_posts(),
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 768, in posts_download_loop
    downloaded = self.download_post(post, target=target)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloader.py", line 505, in download_post
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument:

The script used by me was
instaloader -l vikar1919_._ wow_vikar_wow --no-captions --no-metadata-json --no-compress-json --stories --highlights --igtv --tagged

**Comment by Showmaster3000** [comment]
You didn't use the issue template!

interesting infos needed:
- instaloader version (hope it is the latest version)
- operating system
btw. the profile you are trying to download does not exist.
