### ISSUE TITLE
Problem when using post-filter by date

### ISSUE THREAD

**Issue by nihelmasell** [instaloader/instaloader#753]
Hi, until March I used the following formula to download hashtags from a specific date on --post-filter="date_utc >= datetime(2020, 1, 1)" Now it doesn't seem to work anymore, I get the following error:

KeyError: 'date_utc'
Only download posts with property "date_utc >= datetime(2020, 1, 1)".
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 443, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 151, in _main
    profile_pic=download_profile_pic, posts=download_posts)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 969, in download_hashtag
    self.download_hashtag_profilepic(hashtag)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 435, in download_hashtag_profilepic
    self.download_title_pic(hashtag.profile_pic_url, '#' + hashtag.name, 'profile_pic', None)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 79, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 408, in download_title_pic
    filename = self.format_filename_within_target_path(target, owner_profile, pic_identifier, name_suffix, 'jpg')
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 382, in format_filename_within_target_path
    return os.path.join(self.dirname_pattern.format(profile=profile_str, target=target),
KeyError: 'date_utc'

**Comment by christopherjanzen** [comment]
I'm getting something similar albeit it seems more related to the fact that I'm requesting the date to be used in the filename
`Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 443, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 164, in _main
    post_filter=post_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 63, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 861, in download_saved_posts
    max_count=max_count, total_count=node_iterator.count)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 760, in posts_download_loop
    enabled=self.resume_prefix is not None
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/instaloader/nodeiterator.py", line 244, in resumable_iteration
    resume_file_path = format_path(iterator.magic)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 757, in <lambda>
    sanitized_target, owner_profile, self.resume_prefix or '', magic, 'json.xz'
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 382, in format_filename_within_target_path
    return os.path.join(self.dirname_pattern.format(profile=profile_str, target=target),
KeyError: 'date_utc'`

**Comment by christopherjanzen** [comment]
@nihelmasell you could try rolling back to 4.4.5 as, at least for me, the date_utc issue isn't a problem in that version.

**Comment by aandergr** [comment]
Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.
