### ISSUE TITLE
Login error?

### ISSUE THREAD

**Issue by jasli98** [instaloader/instaloader#76]
Hi, I received this message when I tried logging into private profile:

`Session file does not exist yet - Logging in.
Traceback (most recent call last):
  File "C:\Users\jasli\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.2.2', 'console_scripts', 'instaloader')()
  File "c:\users\jasli\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1656, in main
    filter_str=args.only_if)
  File "c:\users\jasli\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1438, in main
    self.login(username, password)
  File "c:\users\jasli\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 942, in login
    if user == self.test_login(session):
  File "c:\users\jasli\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 925, in test_login
    return data['graphql']['user']['username'] if 'graphql' in data else None
TypeError: 'NoneType' object is not subscriptable`

I tried logging in with my other private account and that worked, so I think it's specific to this account. I tried deleting the session file as advised in a similar error thread but that didn't work. I also tried uninstalling Instaloader and installing it again. This has worked previously for this account a few weeks back, but now it seems the session file is corrupted- even though I had deleted the session file in the Temp folder.

**Comment by naftis** [comment]
Kind of a difficult way of making this work but maybe this will help debugging the problem.
I created a session file manually by creating this script and running it:
https://gist.github.com/naftis/b7449d14c2386baddf611eb7dc74889e

Then I moved that session file to my `%temp%/.insta_loader-windowsusername`

Then from the instaloader.py library I modified `test_login` to always `return 'my_username'`.
After that, I disabled the script rewriting my session file by making `save_session_to_file` to always `return True`

**Comment by Thammus** [comment]
Fixed by commit 4628f1c.
