### ISSUE TITLE
Problem when using post-filter by date II

### ISSUE THREAD

**Issue by nihelmasell** [instaloader/instaloader#760]
1. I have the latest version of Instaloader installed
2. I found no valid solution in the Troubleshooting section
3. The bug was only reported by myself, not meeting the formal requirements for that report
4. All error messages and tracebacks:
$ instaloader --comments --tagged --fast-update --no-compress-json --max-connection-attempts 10 --dirname-pattern=/Instagram/Hashtags/{target}/{date_utc:%Y} --post-filter="date_utc >= datetime(2020, 3, 1)" "#myhashtag"

Only download posts with property "date_utc >= datetime(2020, 3, 1)".
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 443, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 151, in _main
    profile_pic=download_profile_pic, posts=download_posts)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 969, in download_hashtag
    self.download_hashtag_profilepic(hashtag)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 435, in download_hashtag_profilepic
    self.download_title_pic(hashtag.profile_pic_url, '#' + hashtag.name, 'profile_pic', None)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 79, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 408, in download_title_pic
    filename = self.format_filename_within_target_path(target, owner_profile, pic_identifier, name_suffix, 'jpg')
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 382, in format_filename_within_target_path
    return os.path.join(self.dirname_pattern.format(profile=profile_str, target=target),
KeyError: 'date_utc'
Only download posts with property "date_utc >= datetime(2020, 3, 1)".
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 443, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/usr/local/lib/python3.7/site-packages/instaloader/__main__.py", line 151, in _main
    profile_pic=download_profile_pic, posts=download_posts)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 969, in download_hashtag
    self.download_hashtag_profilepic(hashtag)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 435, in download_hashtag_profilepic
    self.download_title_pic(hashtag.profile_pic_url, '#' + hashtag.name, 'profile_pic', None)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 79, in call
    return func(instaloader, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 408, in download_title_pic
    filename = self.format_filename_within_target_path(target, owner_profile, pic_identifier, name_suffix, 'jpg')
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloader.py", line 382, in format_filename_within_target_path
    return os.path.join(self.dirname_pattern.format(profile=profile_str, target=target),
KeyError: 'date_utc'

- The program hangs after that

5. The behavior I expected was the progran to download Instagram post hashtagged "myhashtag" posted after March 1, 2020

6. Context: Mac mini 2014, Mojave, Python 3.7

**Comment by aandergr** [comment]
Please have a look at the documentation. `--dirname-pattern` supports the fields `{profile}` and `{target}`. Using `{date_utc}` in a dirname pattern is not supported and causes the described error.

To get the intended directory structure, you could instead invoke Instaloader as
```
$ instaloader --comments --tagged --fast-update --no-compress-json --max-connection-attempts 10 \
    --dirname-pattern=/Instagram/Hashtags/{target} \
    --filename-pattern={date_utc:%Y}/{date_utc}_UTC \
    --post-filter="date_utc >= datetime(2020, 3, 1)" "#myhashtag"
```

There is especially no *Problem when using post-filter by date*. This has nothing to do with your post-filter.
