### ISSUE TITLE
KeyError: 'user' when downloading profile

### ISSUE THREAD

**Issue by anseml** [instaloader/instaloader#81]
Hi after the new update I receive this error no matter what I try.

Traceback (most recent call last):
  File "/home/ad/.local/bin/instaloader", line 9, in <module>
    load_entry_point('instaloader==3.3', 'console_scripts', 'instaloader')()
  File "/home/ad/.local/lib/python3.5/site-packages/instaloader.py", line 1742, in main
    filter_str=args.only_if)
  File "/home/ad/.local/lib/python3.5/site-packages/instaloader.py", line 1568, in main
    filter_func=filter_func)
  File "/home/ad/.local/lib/python3.5/site-packages/instaloader.py", line 1428, in download_profile
    name_updated, profile_id = self.check_profile_id(name, profile_metadata)
  File "/home/ad/.local/lib/python3.5/site-packages/instaloader.py", line 1353, in check_profile_id
    (profile_id != int(profile_metadata['user']['id'])):
KeyError: 'user'

Thanks!

**Comment by aandergr** [comment]
Hi. Thanks for reporting! Instagram changed some metadata structures, which caused Instaloader to break.
Commit 83b3117 fixes this bug. We do some further double-checking and then release version 3.3.1.
