### ISSUE TITLE
Trying again anonymously, helps in case you are just blocked.

### ISSUE THREAD

**Issue by gnu-like** [instaloader/instaloader#86]
It means instagram blocked me,if it's true, why did block me? and what can I do?
thanks

**Comment by Thammus** [comment]
The message "Profile ... does not exist. Trying again anonymously, helps in case you are just blocked." just means that Instaloader is not able to find the specified profile. This is also the case if a user (not Instagram) has blocked you. If this profile is public, it can be downloaded anonymously which Instaloader automatically tries.

**Comment by gnu-like** [comment]
I upgraded ,I uninstalled and reinstalled again but after Trying again anonymously I receive:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fcf6b715dd8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='instagram.fhel2-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /vp/f17e-0i87yyuyy32e93cbf434ddc32bcd/5B6CCC7A/t51.2885-19/11906329_960233084022564_1448528159_a.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcf6b715dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==3.3.3', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1766, in main
    filter_str=args.only_if)
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1584, in main
    filter_func=filter_func)
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1452, in download_profile
    self.download_profilepic(name, profile_metadata)
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 909, in download_profilepic
    date_object = datetime.strptime(self._get_anonymous_session().head(url).headers["Last-Modified"],
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 543, in head
    return self.request('HEAD', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='instagram.fhel2-1.fna.fbcdn.net', port=443): Max retries exceeded with url: /vp/f1786rdf93cbf434qaddc3aa2bcd/5B6CCC7A/t51.2885-19/11906329_960233084022564_1448528159_a.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcf6b715dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

```

**Comment by Thammus** [comment]
These error messages seem to imply that there is a problem with DNS name resolution. Maybe Facebook is blocked in your country and therefore 'fbcdn.net' can not be resolved.

**Comment by gnu-like** [comment]
@Thammus Yes sir Facebook is blocked but google DNS work so I set 8.8.8.8 to /etc/resolve.conf but not solve my problem what can I do? except proxy using

**Comment by gnu-like** [comment]
I  couldn't solve this issue with using tor

**Comment by symbol3382** [comment]
I got this with different account even

> Traceback (most recent call last):
>   File "C:\Users\symbol\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 520, in _obtain_metadata
>     self._rhx_gis = metadata['rhx_gis']
> KeyError: 'rhx_gis'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "B.py", line 12, in <module>
>     profile = instaloader.Profile.from_username(obj.context, targetInstagramUsername)
>   File "C:\Users\symbol\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 475, in from_username
>     profile._obtain_metadata()  # to raise ProfileNotExistException now in case username is invalid
>   File "C:\Users\symbol\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 522, in _obtain_metadata
>     raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err
> instaloader.exceptions.ProfileNotExistsException: Profile dance1234it does not exist.

Here's my code

`import instaloader
# from includes import *
 
targetInstagramUsername = 'dance1234it'
 
username = 'dance1234it'
password = '' #obviously
 
obj = instaloader.Instaloader()
obj.login(username, password)
print('Login successfull')
profile = instaloader.Profile.from_username(obj.context, targetInstagramUsername)
print('Profile detected')
followers = set(profile.get_followers())
 
print('@' + targetInstagramUsername + ' has: ' + str(len(followers)) + ' followers\n')
 
for follower in followers:
    print(follower)
`
