### ISSUE TITLE
Schema update

### ISSUE THREAD

**Issue by tskho** [instaloader/instaloader#89]
version instaloader-3.3.4, installed from pip3.
Issue probably caused by changing api schema

```
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/home/vitaly/.local/lib/python3.5/site-packages/instaloader.py", line 1766, in main
    filter_str=args.only_if)
  File "/home/vitaly/.local/lib/python3.5/site-packages/instaloader.py", line 1584, in main
    filter_func=filter_func)
  File "/home/vitaly/.local/lib/python3.5/site-packages/instaloader.py", line 1489, in download_profile
    downloaded = self.download_post(post, target=name)
  File "/home/vitaly/.local/lib/python3.5/site-packages/instaloader.py", line 1064, in download_post
    location = post.get_location()
  File "/home/vitaly/.local/lib/python3.5/site-packages/instaloader.py", line 414, in get_location
    return location_json["location"]
KeyError: 'location'
```

**Comment by aandergr** [comment]
I just downloaded some posts with geotags and it worked fine. I noticed that your stack trace quotes an old version of line 414 in `instaloader.py`. We changed it in c5b60b8 with version 3.3.4. Are you sure you properly updated to Instaloader 3.3.4? Does `instaloader --version` print `3.3.4`?

**Comment by tskho** [comment]
My bad. I installed 3.3.4 into system while 3.3.3 was installed locally.
