### ISSUE TITLE
  File "/home/mona/anaconda3/lib/python3.7/site-packages/instaloader/instaloader.py", line 483, in login     self.context.login(user, passwd)   File "/home/mona/anaconda3/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 238, in login     "follow the instructions, then retry.".format(resp_json.get('checkpoint_url'))) instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/25013168396/z2B79pMtFK/ - follow the instructions, then retry.

### ISSUE THREAD

**Issue by monajalal** [instaloader/instaloader#897]
for the following piece of code:

```
import instaloader

loader= instaloader.Instaloader(download_comments=False,
                    download_videos=False,
                    download_geotags=False,
                    save_metadata=False)
loader.login('XYZ', 'ABC')
loader.download_hashtag('fashion', max_count=100, fast_update=False, profile_pic=False)
```

I get the following error:
```
(base) mona@mona:~/research/insta-scrape$ python instaloader_tester.py 
Traceback (most recent call last):
  File "instaloader_tester.py", line 7, in <module>
    loader.login('XYZ', 'ABC')
  File "/home/mona/anaconda3/lib/python3.7/site-packages/instaloader/instaloader.py", line 483, in login
    self.context.login(user, passwd)
  File "/home/mona/anaconda3/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 238, in login
    "follow the instructions, then retry.".format(resp_json.get('checkpoint_url')))
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/25013168396/z2B79pMtFK/ - follow the instructions, then retry.

```

I followed this URL, logged on, and entered the code sent to my phone, and ran the python command again and got the same error. So I am not sure what is meant by `then retry.".format(resp_json.get('checkpoint_url')))` since I am not sure where in the code I should exactly write it. Thanks for any tips.

```
$ instaloader --version
4.5.4
$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by AplhaSlayer1964** [comment]
use the session file to login not the login function. Instagram hates bots so manully logging in will break a lot of the times it seems. follow this to create a season file for your account: https://instaloader.github.io/troubleshooting.html
